var lots_annexe =
[
    [ "Génération 0 — Fondations numériques", "lots-annexe.html#autotoc_md4210", null ],
    [ "Génération 1 — Pont avec le jeu et observabilité", "lots-annexe.html#autotoc_md4211", null ],
    [ "Génération 2 — Premier agent fonctionnel (évolutionniste)", "lots-annexe.html#autotoc_md4212", null ],
    [ "Génération 3 — Apprentissage par gradient", "lots-annexe.html#autotoc_md4213", null ],
    [ "Génération 4 — Évaluation et robustesse", "lots-annexe.html#autotoc_md4214", null ],
    [ "Génération 5 — Intégration jeu et outillage", "lots-annexe.html#autotoc_md4215", null ],
    [ "LOT-ANNEXE-01 — Bibliothèque tensorielle et RNG maison", "lot-annexe-01.html", "lot-annexe-01" ],
    [ "LOT-ANNEXE-02 — Moteur d'autodiff maison", "lot-annexe-02.html", "lot-annexe-02" ],
    [ "LOT-ANNEXE-03 — Bibliothèque de réseaux de neurones maison", "lot-annexe-03.html", "lot-annexe-03" ],
    [ "LOT-ANNEXE-04 — Optimiseurs maison", "lot-annexe-04.html", "lot-annexe-04" ],
    [ "LOT-ANNEXE-05 — Environnement de simulation headless", "lot-annexe-05.html", "lot-annexe-05" ],
    [ "LOT-ANNEXE-06 — Encodage observation", "lot-annexe-06.html", "lot-annexe-06" ],
    [ "LOT-ANNEXE-07 — Espace d'action, décodage politique et format de rejeu v1", "lot-annexe-07.html", "lot-annexe-07" ],
    [ "LOT-ANNEXE-08 — Fonction de récompense et critères d'épisode", "lot-annexe-08.html", "lot-annexe-08" ],
    [ "LOT-ANNEXE-09 — Journalisation CSV des statistiques d'entraînement", "lot-annexe-09.html", "lot-annexe-09" ],
    [ "LOT-ANNEXE-10 — Algorithme évolutionniste maison", "lot-annexe-10.html", "lot-annexe-10" ],
    [ "LOT-ANNEXE-11 — Entraînement niveau-par-niveau et export de rejeu", "lot-annexe-11.html", "lot-annexe-11" ],
    [ "LOT-ANNEXE-12 — Policy gradient maison (REINFORCE)", "lot-annexe-12.html", "lot-annexe-12" ],
    [ "LOT-ANNEXE-13 — Réduction de variance : critique et avantage (acteur-critique)", "lot-annexe-13.html", "lot-annexe-13" ],
    [ "LOT-ANNEXE-14 — Algorithme avancé (PPO maison ou Q-learning à mémoire de rejeu)", "lot-annexe-14.html", "lot-annexe-14" ],
    [ "LOT-ANNEXE-15 — Harnais de benchmark multi-algorithmes", "lot-annexe-15.html", "lot-annexe-15" ],
    [ "LOT-ANNEXE-16 — Évaluation hors-niveau (transfert)", "lot-annexe-16.html", "lot-annexe-16" ],
    [ "LOT-ANNEXE-17 — Validation et stabilisation du format de rejeu", "lot-annexe-17.html", "lot-annexe-17" ],
    [ "LOT-ANNEXE-18 — Mode « regarder l'IA jouer » (intégration HMI)", "lot-annexe-18.html", "lot-annexe-18" ],
    [ "LOT-ANNEXE-19 — Outillage CLI", "lot-annexe-19.html", "lot-annexe-19" ],
    [ "LOT-ANNEXE-20 — Garde-fou CI", "lot-annexe-20.html", "lot-annexe-20" ],
    [ "LOT-ANNEXE-21 — Mode IA (IHM)", "lot-annexe-21.html", "lot-annexe-21" ]
];