var searchData=
[
  ['échantillonnage_20em_20nearest_20em_0',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20ref_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_1',['Échantillonner plutôt que réagir : \ref hmi::InputState &quot;hmi::InputState&quot;',['../guide-entrees.html#autotoc_md71',1,'']]],
  ['échec_2',['échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['écran_3',['écran',['../guide-rendu.html#autotoc_md155',1,'\ref hmi::SpriteRenderer &quot;hmi::SpriteRenderer&quot; : le pont ECS → écran'],['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-05-tache-04-camera-2d.html',1,'TACHE-04 — Caméra 2D (monde → écran)'],['../lot-05-tache-05-systeme-rendu-sprites.html',1,'TACHE-05 — Système de rendu des sprites (ECS → écran)'],['../lot-06-tache-07-integration-main.html',1,'TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)']]],
  ['écran_20éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_4',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['écran_20de_20menu_20principal_5',['TACHE-05 — Écran de menu principal',['../lot-06-tache-05-ecran-menu-principal.html',1,'lot-06']]],
  ['écran_20présentation_20redimensionnement_6',['TACHE-04 — Effacement écran, présentation &amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['écrans_7',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['écrans_20cibles_20jeu_20démo_20éditeur_20placeholder_8',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['écrans_20et_20navigation_9',['Écrans et navigation',['../guide-ecrans.html',1,'guide']]],
  ['écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_10',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['écrasement_11',['TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'lot-15']]],
  ['écrire_20jamais_20l_20inverse_12',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md65',1,'']]],
  ['éditer_20un_20niveau_20sans_20re_20coder_20le_20moteur_13',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md55',1,'']]],
  ['éditeur_14',['éditeur',['../spec-decors.html#autotoc_md202',1,'À la conception (éditeur)'],['../spec-interface-ihm.html#autotoc_md237',1,'2. Éditeur'],['../manuel-partager-niveau.html#autotoc_md1822',1,'2. Lancer l&apos;éditeur'],['../spec-decors.html#autotoc_md204',1,'3. Pipeline photo → pixel art (intégré à l&apos;éditeur)'],['../spec-editeur.html#autotoc_md212',1,'4bis. Décors &amp; pixel art (post-MVP, intégré à l&apos;éditeur)'],['../guide-editeur.html#autotoc_md64',1,'Essai immédiat : jouer sans quitter l&apos;éditeur'],['../lot-29.html',1,'LOT-29 — Remappage des touches (jeu + éditeur)'],['../lot-29-tache-02-integration-jeu-editeur.html',1,'TACHE-02 — Intégration jeu/éditeur'],['../lot-32-tache-03-repere-editeur.html',1,'TACHE-03 — Repère visuel de salles dans l&apos;éditeur']]],
  ['éditeur_20_3a_20docks_20palette_20peinture_20lot_2035_15',['Éditeur : docks, palette, peinture (LOT-35)',['../guide-ihm-qt.html#autotoc_md87',1,'']]],
  ['éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_16',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['éditeur_20de_20niveaux_17',['Éditeur de niveaux',['../spec-editeur.html',1,'specifications']]],
  ['éditeur_20de_20niveaux_20—_20tt_20test_5fparcours_5fedition_20cpp_20tt_202_18',['Éditeur de niveaux — &lt;tt&gt;test_parcours_edition.cpp&lt;/tt&gt; (2)',['../cahiertest.html#autotoc_md29',1,'']]],
  ['éditeur_20de_20niveaux_20_3a_20robustesse_20et_20confort_20d_20édition_19',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['éditeur_20de_20niveaux_20intégré_20',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['éditeur_20de_20niveaux_20intégré_20_3a_20édition_20de_20tuiles_20mécanismes_20essai_20immédiat_21',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['éditeur_20docking_20palette_20outils_20peinture_22',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['éditeur_20et_20jeu_23',['TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)',['../lot-16-tache-03-camera-niveau-entier.html',1,'lot-16']]],
  ['éditeur_20et_20jeu_20hmi_24',['TACHE-02 — Intégration éditeur et jeu (HMI)',['../lot-21-tache-02-integration-editeur-jeu.html',1,'lot-21']]],
  ['éditeur_20et_20niveau_20de_20démonstration_25',['TACHE-03 — Intégration éditeur et niveau de démonstration',['../lot-19-tache-03-editeur-niveau-demo.html',1,'lot-19']]],
  ['éditeur_20et_20rendu_26',['éditeur et rendu',['../lot-28-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-26-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-23-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-24-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu'],['../lot-22-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu']]],
  ['éditeur_20intégré_20»_27',['10. Contrainte « éditeur intégré »',['../spec-architecture.html#autotoc_md172',1,'']]],
  ['éditeur_20manette_28',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['éditeur_20mvp_29',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md213',1,'']]],
  ['éditeur_20organisée_20par_20catégories_30',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['éditeur_20palette_20rendu_20liaison_31',['TACHE-03 — Intégration éditeur (palette, rendu, liaison)',['../lot-31-tache-03-integration-editeur.html',1,'lot-31']]],
  ['éditeur_20placeholder_32',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['éditeur_20strong_20et_20strong_20jeu_33',['Le viewport partagé : éditeur &lt;strong&gt;et&lt;/strong&gt; jeu',['../guide-ecrans.html#autotoc_md42',1,'']]],
  ['édition_34',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['édition_20de_20tuiles_20mécanismes_20essai_20immédiat_35',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['édition_20lot_2015_36',['6. Robustesse et confort d&apos;édition (LOT-15)',['../spec-editeur.html#autotoc_md214',1,'']]],
  ['édition_20mutable_37',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['égalité_20approchée_38',['Égalité approchée',['../guide-maths.html#autotoc_md104',1,'']]],
  ['égalité_20stricte_20est_20dangereuse_39',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md107',1,'']]],
  ['épinglé_40',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['étapes_41',['Étapes',['../manuel-telecharger.html#autotoc_md1828',1,'']]],
  ['état_42',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md72',1,'']]],
  ['état_20en_20intention_20_3a_20ref_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_43',['Traduire l&apos;état en intention : \ref hmi::toPlayerInput &quot;hmi::toPlayerInput&quot;',['../guide-entrees.html#autotoc_md75',1,'']]],
  ['état_20erreurs_20documentation_20vérification_44',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['état_20partagé_45',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md85',1,'']]],
  ['état_20physique_20pas_20un_20état_20séparé_46',['L&apos;animation : une projection de l&apos;état physique, pas un état séparé',['../guide-rendu.html#autotoc_md154',1,'']]],
  ['états_20d_20application_20écrans_47',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['états_20de_20jeu_48',['5. États de jeu',['../spec-gameplay.html#autotoc_md234',1,'']]],
  ['événements_20qt_20vers_20l_20état_20partagé_49',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md85',1,'']]],
  ['éviter_20la_20racine_20carrée_50',['\ref core::Vector2::lengthSquared &quot;lengthSquared&quot; : éviter la racine carrée',['../guide-maths.html#autotoc_md103',1,'']]]
];
