var searchData=
[
  ['navigables_0',['TACHE-05 — Pages de lots navigables',['../lot-04-tache-05-pages-lots.html',1,'lot-04']]],
  ['navigables_20conventions_20incluses_1',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['navigation_2',['Écrans et navigation',['../guide-ecrans.html',1,'guide']]],
  ['nearest_3',['TACHE-02 — Pipeline de quads texturés (HLSL, blend, nearest)',['../lot-05-tache-02-pipeline-quads-textures.html',1,'lot-05']]],
  ['nettoyage_20documentaire_4',['TACHE-08 — Nettoyage documentaire',['../lot-15-tache-08-nettoyage-documentation.html',1,'lot-15']]],
  ['newtonienne_5',['TACHE-01 — Masse et chute newtonienne',['../lot-19-tache-01-masse-chute-newtonienne.html',1,'lot-19']]],
  ['newtonienne_20et_20plaque_20de_20pression_6',['LOT-19 — Physique newtonienne et plaque de pression',['../lot-19.html',1,'lots']]],
  ['niveau_7',['niveau',['../lot-07-tache-02-modele-niveau.html',1,'TACHE-02 — Modèle de tuiles et de niveau'],['../lot-07-tache-04-validation.html',1,'TACHE-04 — Validation du niveau']]],
  ['niveau_20éditeur_20et_20jeu_8',['TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)',['../lot-16-tache-03-camera-niveau-entier.html',1,'lot-16']]],
  ['niveau_20_3a_20molette_20et_20texte_20tapé_9',['TACHE-01 — Entrées bas niveau : molette et texte tapé',['../lot-15-tache-01-entrees-molette-texte.html',1,'lot-15']]],
  ['niveau_20de_20démo_20«_20parkour_20»_20preuve_20système_10',['TACHE-06 — Niveau de démo « parkour » + preuve système',['../lot-10-tache-06-niveau-parkour.html',1,'lot-10']]],
  ['niveau_20de_20démonstration_11',['niveau de démonstration',['../lot-19-tache-03-editeur-niveau-demo.html',1,'TACHE-03 — Intégration éditeur et niveau de démonstration'],['../lot-07-tache-05-niveau-demo.html',1,'TACHE-05 — Niveau de démonstration']]],
  ['niveau_20demo4_20preuves_12',['TACHE-04 — Intégration GameScreen + niveau demo4 + preuves',['../lot-12-tache-04-integration-puzzle.html',1,'lot-12']]],
  ['niveau_20intégration_20«_20charger_20niveau_20»_13',['TACHE-06 — Rendu du niveau + intégration « Charger niveau »',['../lot-07-tache-06-rendu-integration.html',1,'lot-07']]],
  ['niveau_20json_14',['TACHE-03 — Chargement du niveau (JSON)',['../lot-07-tache-03-chargement-json.html',1,'lot-07']]],
  ['niveau_20puzzle_20_3a_20mécanismes_20interrupteur_20porte_20budget_20de_20mouvements_15',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]],
  ['niveau_20sans_20ligne_20de_20commande_16',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['niveau_20succès_20échec_17',['TACHE-04 — Règles de fin de niveau (succès / échec)',['../lot-08-tache-04-regles-fin-niveau.html',1,'lot-08']]],
  ['niveaux_18',['niveaux',['../spec-editeur.html',1,'Éditeur de niveaux'],['../lot-09.html',1,'LOT-09 — Saut, game feel et enchaînement de niveaux']]],
  ['niveaux_20_3a_20modèle_20chargement_20mécanismes_20budgets_19',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['niveaux_20_3a_20modèle_20et_20chargement_20',['LOT-07 — Niveaux : modèle et chargement',['../lot-07.html',1,'lots']]],
  ['niveaux_20_3a_20robustesse_20et_20confort_20d_20édition_21',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['niveaux_20contenu_22',['Niveaux &amp; contenu',['../spec-niveaux.html',1,'specifications']]],
  ['niveaux_20de_20démo_20séquence_20dont_20saut_20requis_20preuve_23',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['niveaux_20de_20grande_20taille_24',['LOT-16 — Niveaux de grande taille',['../lot-16.html',1,'lots']]],
  ['niveaux_20de_20log_20interface_20logger_25',['TACHE-01 — Niveaux de log &amp; interface Logger',['../lot-02-tache-01-niveaux-logger.html',1,'lot-02']]],
  ['niveaux_20intégré_26',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['niveaux_20intégré_20_3a_20édition_20de_20tuiles_20mécanismes_20essai_20immédiat_27',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['niveaux_20preuves_20à_20la_20vraie_20taille_28',['TACHE-04 — Rééquilibrage des niveaux + preuves à la vraie taille',['../lot-11-tache-04-reequilibrage.html',1,'lot-11']]],
  ['niveaux_20séquence_20auto_20avance_20retour_20titre_29',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['nlohmann_20json_20épinglé_30',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['nommage_20renommage_20avertissement_20d_20écrasement_31',['TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'lot-15']]],
  ['non_20codeur_20git_32',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['non_20fonctionnelles_33',['Exigences non fonctionnelles',['../spec-exigences.html',1,'specifications']]]
];
