var searchData=
[
  ['mécaniques_20aériennes_20avancées_20_3a_20double_20saut_20wall_20jump_20dash_0',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['mécaniques_20et_20conception_1',['TACHE-01 — Inventaire des mécaniques et conception',['../lot-25-tache-01-inventaire-conception.html',1,'lot-25']]],
  ['mécaniques_20playerinput_20player_20physicsconfig_2',['TACHE-01 — Données des mécaniques (PlayerInput, Player, PhysicsConfig)',['../lot-10-tache-01-donnees.html',1,'lot-10']]],
  ['mécanismes_20budgets_3',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['mécanismes_20essai_20immédiat_4',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['mécanismes_20interrupteur_20porte_20budget_20de_20mouvements_5',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]],
  ['mécanismes_20interrupteur_20porte_20mechanismcontroller_6',['TACHE-02 — Mécanismes interrupteur/porte (MechanismController)',['../lot-12-tache-02-mecanismes.html',1,'lot-12']]],
  ['mécanismes_20redimensionnement_7',['TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'lot-14']]],
  ['mécanismes_20visuels_20traits_20flèches_8',['LOT-37 — Refonte IHM (Qt) : liens de mécanismes visuels (traits/flèches)',['../lot-37.html',1,'lots']]],
  ['mémoire_20erreurs_20de_20validation_20structurées_9',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['macros_20de_20log_20fichier_20ligne_20horodatage_10',['TACHE-03 — Macros de log (fichier/ligne, horodatage)',['../lot-02-tache-03-macros-log.html',1,'lot-02']]],
  ['magenta_11',['TACHE-03 — Texture de repli en damier magenta',['../lot-40-tache-03-damier-magenta.html',1,'lot-40']]],
  ['main_20boucle_20pilotée_20par_20l_20écran_12',['TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)',['../lot-06-tache-07-integration-main.html',1,'lot-06']]],
  ['main_20documentation_13',['TACHE-05 — Intégration dans main &amp; documentation',['../lot-02-tache-05-integration.html',1,'lot-02']]],
  ['main_20vérification_14',['TACHE-05 — Intégration main &amp; vérification',['../lot-01-tache-05-integration.html',1,'lot-01']]],
  ['mainpage_15',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]],
  ['maison_20fenêtre_20win32_20ancienne_20boucle_16',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['manette_17',['manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette'],['../lot-30-tache-01-modele-bindings-manette.html',1,'TACHE-01 — Modèle de bindings manette'],['../lot-38-tache-02-options-remappage-qt.html',1,'TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette']]],
  ['manette_20et_20câblage_18',['TACHE-03 — UI de remappage manette et câblage',['../lot-30-tache-03-ui-remappage-manette.html',1,'lot-30']]],
  ['manette_20et_20menu_20d_20options_19',['LOT-20 — Manette et menu d&apos;options',['../lot-20.html',1,'lots']]],
  ['manette_20jeu_20',['LOT-30 — Remappage manette (jeu)',['../lot-30.html',1,'lots']]],
  ['manette_20xinput_21',['TACHE-01 — Intégration manette (XInput)',['../lot-20-tache-01-integration-manette.html',1,'lot-20']]],
  ['manuel_20utilisateur_22',['Manuel utilisateur',['../manuel.html',1,'index']]],
  ['manuel_20utilisateur_20squelette_20première_20page_23',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['manuels_24',['TACHE-04 — Caméra : pan et zoom manuels',['../lot-15-tache-04-camera-pan-zoom.html',1,'lot-15']]],
  ['mapping_20du_20dash_20direction_20de_20visée_20orientation_25',['TACHE-02 — Mapping du dash + direction de visée / orientation',['../lot-10-tache-02-mapping-dash.html',1,'lot-10']]],
  ['mapping_20du_20saut_20espace_20w_20→_20intention_26',['TACHE-02 — Mapping du saut (Espace/W → intention)',['../lot-09-tache-02-mapping-saut.html',1,'lot-09']]],
  ['mapping_20touches_20→_20intention_27',['TACHE-05 — Actions logiques d&apos;entrée (mapping touches → intention)',['../lot-08-tache-05-actions-logiques.html',1,'lot-08']]],
  ['markdown_28',['TACHE-02 — Configuration Doxygen pour le Markdown',['../lot-04-tache-02-config-doxygen-markdown.html',1,'lot-04']]],
  ['masse_20et_20chute_20newtonienne_29',['TACHE-01 — Masse et chute newtonienne',['../lot-19-tache-01-masse-chute-newtonienne.html',1,'lot-19']]],
  ['mathématiques_20core_30',['LOT-03 — Fondation ECS &amp; mathématiques Core',['../lot-03.html',1,'lots']]],
  ['mathématiques_20de_20core_31',['TACHE-01 — Types mathématiques de Core',['../lot-03-tache-01-math-core.html',1,'lot-03']]],
  ['mathématiques_20du_20moteur_32',['Mathématiques du moteur',['../guide-maths.html',1,'guide']]],
  ['mechanismcontroller_33',['TACHE-02 — Mécanismes interrupteur/porte (MechanismController)',['../lot-12-tache-02-mecanismes.html',1,'lot-12']]],
  ['menu_20d_20options_34',['menu d options',['../lot-20.html',1,'LOT-20 — Manette et menu d&apos;options'],['../lot-20-tache-02-menu-options.html',1,'TACHE-02 — Menu d&apos;options']]],
  ['menu_20options_20contrôles_20vérification_35',['TACHE-04 — Nettoyage des tests, documentation (menu/options/contrôles) &amp; vérification',['../lot-38-tache-04-nettoyage-tests-doc.html',1,'lot-38']]],
  ['menu_20principal_36',['menu principal',['../lot-06.html',1,'LOT-06 — Menu principal'],['../lot-06-tache-05-ecran-menu-principal.html',1,'TACHE-05 — Écran de menu principal']]],
  ['menu_20principal_20qt_20navigation_20remplace_20iscreen_20screenmanager_37',['TACHE-01 — Menu principal Qt + navigation (remplace `IScreen`/`ScreenManager`)',['../lot-38-tache-01-menu-navigation-qt.html',1,'lot-38']]],
  ['menu_20tests_20système_20guide_20non_20codeur_20git_38',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['menus_20options_20remappage_20retrait_20du_20legacy_20ui_39',['LOT-38 — Refonte IHM (Qt) : menus, options, remappage &amp; retrait du legacy UI',['../lot-38.html',1,'lots']]],
  ['messages_40',['TACHE-01 — Fenêtre Win32 &amp; pompe de messages',['../lot-01-tache-01-fenetre-win32.html',1,'lot-01']]],
  ['modèle_20chargement_20mécanismes_20budgets_41',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['modèle_20d_20édition_20mutable_42',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['modèle_20de_20bindings_20et_20persistance_20json_43',['TACHE-01 — Modèle de bindings et persistance JSON',['../lot-29-tache-01-modele-bindings.html',1,'lot-29']]],
  ['modèle_20de_20bindings_20manette_44',['TACHE-01 — Modèle de bindings manette',['../lot-30-tache-01-modele-bindings-manette.html',1,'lot-30']]],
  ['modèle_20de_20bloc_20réduit_45',['TACHE-01 — Modèle de bloc réduit',['../lot-24-tache-01-modele-bloc-reduit.html',1,'lot-24']]],
  ['modèle_20de_20tuile_20et_20fonction_20de_20hauteur_46',['TACHE-01 — Modèle de tuile et fonction de hauteur',['../lot-22-tache-01-modele-tuile-pente.html',1,'lot-22']]],
  ['modèle_20de_20tuile_20et_20formule_20de_20courbe_47',['TACHE-01 — Modèle de tuile et formule de courbe',['../lot-23-tache-01-modele-tuile-arrondie.html',1,'lot-23']]],
  ['modèle_20de_20tuile_20et_20formule_20de_20courbe_20concave_48',['TACHE-01 — Modèle de tuile et formule de courbe concave',['../lot-28-tache-01-modele-physique-concave.html',1,'lot-28']]],
  ['modèle_20de_20tuile_20et_20physique_20de_20suivi_49',['TACHE-01 — Modèle de tuile et physique de suivi',['../lot-26-tache-01-modele-physique-plafond.html',1,'lot-26']]],
  ['modèle_20de_20tuiles_20et_20de_20niveau_50',['TACHE-02 — Modèle de tuiles et de niveau',['../lot-07-tache-02-modele-niveau.html',1,'lot-07']]],
  ['modèle_20et_20chargement_51',['LOT-07 — Niveaux : modèle et chargement',['../lot-07.html',1,'lots']]],
  ['modèle_20et_20contrôleur_20core_52',['TACHE-01 — Modèle et contrôleur (Core)',['../lot-21-tache-01-controleur-blocs.html',1,'lot-21']]],
  ['modèle_20fichiers_20liste_20recherche_20filtre_53',['TACHE-01 — Panneau « Niveaux » (modèle fichiers + liste + recherche/filtre)',['../lot-36-tache-01-panneau-niveaux-recherche.html',1,'lot-36']]],
  ['modèle_20types_20format_20généralisation_20des_20liaisons_54',['TACHE-01 — Modèle (types, format, généralisation des liaisons)',['../lot-31-tache-01-modele-dangers-avances.html',1,'lot-31']]],
  ['mode_20«_20définition_20des_20textures_20»_20_3a_20aperçu_20isolé_20par_20calque_55',['LOT-45 — Mode « définition des textures » : aperçu isolé par calque',['../lot-45.html',1,'lots']]],
  ['model_20latence_20réduite_56',['TACHE-02 — Présentation flip-model (latence réduite)',['../lot-33-tache-02-presentation-flip.html',1,'lot-33']]],
  ['molette_20et_20texte_20tapé_57',['TACHE-01 — Entrées bas niveau : molette et texte tapé',['../lot-15-tache-01-entrees-molette-texte.html',1,'lot-15']]],
  ['monde_20→_20écran_58',['TACHE-04 — Caméra 2D (monde → écran)',['../lot-05-tache-04-camera-2d.html',1,'lot-05']]],
  ['moteur_59',['Mathématiques du moteur',['../guide-maths.html',1,'guide']]],
  ['moteur_20entrées_20nerveuses_20présentation_20flip_20interpolation_60',['LOT-33 — Fluidité du moteur (entrées nerveuses, présentation flip, interpolation)',['../lot-33.html',1,'lots']]],
  ['mouvement_20démo_61',['TACHE-06 — Composant Transform + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['mouvements_62',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]],
  ['multi_20composants_63',['TACHE-04 — Requêtes / vues multi-composants',['../lot-03-tache-04-vues-requetes.html',1,'lot-03']]],
  ['multi_20textures_64',['LOT-40 — Fondations : registre de textures indépendantes + rendu multi-textures',['../lot-40.html',1,'lots']]],
  ['mutable_65',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]]
];
