var searchData=
[
  ['câblage_20du_20world_20dans_20la_20boucle_20scène_20de_20démo_0',['TACHE-06 — Câblage du `World` dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['cadrage_20fixe_20succès_20échec_1',['TACHE-06 — Intégration jouable dans `GameScreen` (cadrage fixe, succès / échec)',['../lot-08-tache-06-integration-jouable.html',1,'lot-08']]],
  ['cahier_20de_20test_2',['Cahier de test',['../cahiertest.html',1,'']]],
  ['caméra_3',['LOT-05 — Rendu 2D : atlas, sprites &amp; caméra',['../lot-05.html',1,'lots']]],
  ['caméra_202d_20monde_20→_20écran_4',['TACHE-04 — Caméra 2D (monde → écran)',['../lot-05-tache-04-camera-2d.html',1,'lot-05']]],
  ['caméra_20_3a_20englober_20tout_20le_20niveau_20éditeur_20et_20jeu_5',['TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)',['../lot-16-tache-03-camera-niveau-entier.html',1,'lot-16']]],
  ['caméra_20_3a_20pan_20et_20zoom_20manuels_6',['TACHE-04 — Caméra : pan et zoom manuels',['../lot-15-tache-04-camera-pan-zoom.html',1,'lot-15']]],
  ['catalogue_20de_20traduction_20i18n_7',['TACHE-03 — Catalogue de traduction (i18n)',['../lot-06-tache-03-catalogue-traduction.html',1,'lot-06']]],
  ['chargement_8',['LOT-07 — Niveaux : modèle et chargement',['../lot-07.html',1,'lots']]],
  ['chargement_20du_20niveau_20json_9',['TACHE-03 — Chargement du niveau (JSON)',['../lot-07-tache-03-chargement-json.html',1,'lot-07']]],
  ['chargement_20mécanismes_20budgets_10',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['charger_20niveau_20»_11',['TACHE-06 — Rendu du niveau + intégration « Charger niveau »',['../lot-07-tache-06-rendu-integration.html',1,'lot-07']]],
  ['ci_12',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['ci_20documentation_20warn_5fas_5ferror_20déploiement_13',['TACHE-07 — CI documentation (WARN_AS_ERROR &amp; déploiement)',['../lot-04-tache-07-ci-docs.html',1,'lot-04']]],
  ['cible_20technique_14',['Rendu &amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['cibles_20jeu_20démo_20éditeur_20placeholder_15',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['clavier_20souris_16',['TACHE-01 — Entrées clavier &amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['cliquable_20palette_20de_20tuiles_17',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['code_18',['Conventions de code',['../spec-conventions.html',1,'specifications']]],
  ['codeur_20git_19',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['coller_20',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['collisions_21',['collisions',['../lot-08.html',1,'LOT-08 — Gameplay personnage : déplacement, gravité et collisions'],['../lot-08-tache-03-physique-personnage.html',1,'TACHE-03 — Physique du personnage (gravité + déplacement + collisions)']]],
  ['commande_22',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['composant_20et_20système_20d_20animation_23',['TACHE-01 — Composant et système d&apos;animation',['../lot-18-tache-01-composant-systeme-animation.html',1,'lot-18']]],
  ['composant_20sprite_20données_20pures_24',['TACHE-01 — Composant `Sprite` (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['composant_20transform_20système_20de_20mouvement_20démo_25',['TACHE-06 — Composant `Transform` + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['composants_26',['TACHE-04 — Requêtes / vues multi-composants',['../lot-03-tache-04-vues-requetes.html',1,'lot-03']]],
  ['composants_20du_20personnage_20intention_20d_20entrée_27',['TACHE-01 — Composants du personnage &amp; intention d&apos;entrée',['../lot-08-tache-01-composants-personnage.html',1,'lot-08']]],
  ['composants_20sparse_20set_20typé_28',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['composants_20systèmes_29',['ECS : entités, composants, systèmes',['../guide-ecs.html',1,'guide']]],
  ['configuration_20doxygen_20pour_20le_20markdown_30',['TACHE-02 — Configuration Doxygen pour le Markdown',['../lot-04-tache-02-config-doxygen-markdown.html',1,'lot-04']]],
  ['confort_20d_20édition_31',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['consolidation_20de_20la_20documentation_32',['LOT-13 — Consolidation de la documentation',['../lot-13.html',1,'lots']]],
  ['contenu_33',['Niveaux &amp; contenu',['../spec-niveaux.html',1,'specifications']]],
  ['contrôles_20entrées_34',['Contrôles &amp; entrées',['../spec-controles.html',1,'specifications']]],
  ['contre_20la_20grille_20géométrie_20pure_35',['TACHE-02 — Balayage AABB contre la grille (géométrie pure)',['../lot-08-tache-02-balayage-aabb.html',1,'lot-08']]],
  ['conventions_20de_20code_36',['Conventions de code',['../spec-conventions.html',1,'specifications']]],
  ['conventions_20incluses_37',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['copier_20coller_38',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['core_39',['core',['../lot-03.html',1,'LOT-03 — Fondation ECS &amp; mathématiques `Core`'],['../lot-03-tache-01-math-core.html',1,'TACHE-01 — Types mathématiques de `Core`']]],
  ['course_20saut_40',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['coyote_20time_20jump_20buffering_41',['TACHE-04 — Coyote time + jump buffering',['../lot-09-tache-04-coyote-buffering.html',1,'lot-09']]],
  ['créer_20et_20partager_20un_20niveau_20sans_20ligne_20de_20commande_42',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['ctrl_20r_43',['TACHE-02 — Boîte de dialogue de redimensionnement (`Ctrl+R`)',['../lot-16-tache-02-boite-dialogue-redimensionnement.html',1,'lot-16']]],
  ['cycle_20de_20vie_44',['TACHE-02 — Entités : handles générationnels &amp; cycle de vie',['../lot-03-tache-02-entites.html',1,'lot-03']]]
];
