var searchData=
[
  ['b_0',['TACHE-01 — Exécution croisée (modèle de A exécuté sur B)',['../lot-annexe-16-tache-01-execution-croisee.html',1,'lot-annexe-16']]],
  ['back_20buffer_1',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['backward_2',['TACHE-01 — Couche dense (poids + biais, forward/backward)',['../lot-annexe-03-tache-01-couche-dense.html',1,'lot-annexe-03']]],
  ['backward_20_3a_20parcours_20topologique_20inverse_3',['TACHE-03 — `backward()` : parcours topologique inverse',['../lot-annexe-02-tache-03-retropropagation.html',1,'lot-annexe-02']]],
  ['balayage_20aabb_20contre_20la_20grille_20géométrie_20pure_4',['TACHE-02 — Balayage AABB contre la grille (géométrie pure)',['../lot-08-tache-02-balayage-aabb.html',1,'lot-08']]],
  ['balayage_20continu_20swept_20aabb_5',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md198',1,'']]],
  ['balayage_20horizontal_6',['Le piège du mur adjacent (correction du balayage horizontal)',['../guide-physique.html#autotoc_md207',1,'']]],
  ['balayage_20par_20axe_20avec_20clamp_20direct_7',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md201',1,'']]],
  ['banque_20d_20assets_8',['Banque d&apos;assets',['../lot-65-tache-00-preparation-assets-niveaux.html#autotoc_md3053',1,'']]],
  ['banque_20d_20assets_20renforcée_20et_20remise_20à_20zéro_20des_20niveaux_9',['TACHE-00 — Préparation : banque d&apos;assets renforcée et remise à zéro des niveaux',['../lot-65-tache-00-preparation-assets-niveaux.html',1,'lot-65']]],
  ['barre_20d_20état_20_3a_20état_20permanent_20et_20aide_20contextuelle_10',['TACHE-01 — Barre d&apos;état : état permanent et aide contextuelle',['../lot-57-tache-01-barre-etat.html',1,'lot-57']]],
  ['barre_20d_20état_20structurée_11',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md84',1,'']]],
  ['barre_20d_20outils_20à_20actions_12',['TACHE-04 — Icônes dessinées par code et barre d&apos;outils à actions',['../lot-56-tache-04-icones-barre-outils.html',1,'lot-56']]],
  ['barre_20d_20outils_20état_20et_20historique_20visuel_13',['TACHE-04 — Actions, barre d&apos;outils, état et historique visuel',['../lot-54-tache-04-actions-barre-outils.html',1,'lot-54']]],
  ['barre_20d_20outils_20aide_20libellés_20liaisons_20lisibles_14',['TACHE-06 — Découvrabilité : barre d&apos;outils, aide, libellés, liaisons lisibles',['../lot-15-tache-06-decouvrabilite.html',1,'lot-15']]],
  ['barre_20d_20outils_20peinture_20viewport_20→_20leveldraft_20undo_20redo_20copier_20coller_15',['TACHE-03 — Barre d&apos;outils + peinture viewport → `LevelDraft` (undo/redo, copier/coller)',['../lot-35-tache-03-outils-peinture-viewport.html',1,'lot-35']]],
  ['bas_20niveau_20_3a_20molette_20et_20texte_20tapé_16',['TACHE-01 — Entrées bas niveau : molette et texte tapé',['../lot-15-tache-01-entrees-molette-texte.html',1,'lot-15']]],
  ['bascule_200_201_200_20et_20vérification_20finale_17',['TACHE-04 — Bascule `0.1.0` et vérification finale',['../lot-66-tache-04-bascule-0-1-0.html',1,'lot-66']]],
  ['bascule_20physique_20texture_20f8_20non_20remappable_18',['LOT-41 — Bascule Physique/Texture (`F8`, non remappable)',['../lot-41.html',1,'lots']]],
  ['base_19',['TACHE-02 — Opérations différentiables de base',['../lot-annexe-02-tache-02-operations-differentiables.html',1,'lot-annexe-02']]],
  ['base_20_3a_20gpu_20swap_20chain_20back_20buffer_20',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['base_20de_20comparaison_20baseline_21',['2. L&apos;idée : soustraire une base de comparaison (&lt;em&gt;baseline&lt;/em&gt;)',['../guide-annexe-acteur-critique.html#autotoc_md265',1,'']]],
  ['baseline_22',['2. L&apos;idée : soustraire une base de comparaison (&lt;em&gt;baseline&lt;/em&gt;)',['../guide-annexe-acteur-critique.html#autotoc_md265',1,'']]],
  ['batcher_20»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_23',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md224',1,'']]],
  ['batterie_20de_20tests_20de_20croisement_24',['Batterie de tests de croisement',['../lot-65-tache-06-croisements-mecaniques.html#autotoc_md3104',1,'']]],
  ['bellman_20et_20l_20apprentissage_20par_20différence_20temporelle_25',['2.2. L&apos;équation de Bellman et l&apos;apprentissage par différence temporelle',['../guide-annexe-ppo-dqn.html#autotoc_md341',1,'']]],
  ['benchmark_20multi_20algorithmes_26',['LOT-ANNEXE-15 — Harnais de benchmark multi-algorithmes',['../lot-annexe-15.html',1,'lots-annexe']]],
  ['bfs_20au_20lieu_20de_20la_20distance_20euclidienne_27',['Amendement : distance de grille (BFS) au lieu de la distance euclidienne',['../lot-annexe-08.html#autotoc_md3678',1,'']]],
  ['biais_28',['TACHE-02 — Adam (moments d&apos;ordre 1/2, correction de biais)',['../lot-annexe-04-tache-02-adam.html',1,'lot-annexe-04']]],
  ['biais_20forward_20backward_29',['TACHE-01 — Couche dense (poids + biais, forward/backward)',['../lot-annexe-03-tache-01-couche-dense.html',1,'lot-annexe-03']]],
  ['biais_20round_20trip_30',['TACHE-04 — Tests : couverture, absence de biais, round-trip',['../lot-annexe-07-tache-04-tests.html',1,'lot-annexe-07']]],
  ['bibliothèque_31',['bibliothèque',['../lot-03.html#autotoc_md548',1,'⚠️ Décision préalable : ECS maison vs bibliothèque'],['../lot-34-tache-01-provisionnement-qt-build.html',1,'TACHE-01 — Provisionnement Qt (local + CI/release) &amp; intégration CMake ; `HMI` en bibliothèque']]],
  ['bibliothèque_20d_20assets_20_3a_20vignettes_20import_20rechargement_20à_20chaud_32',['LOT-43 — Bibliothèque d&apos;assets : vignettes, import, rechargement à chaud',['../lot-43.html',1,'lots']]],
  ['bibliothèque_20de_20réseaux_20de_20neurones_20maison_33',['LOT-ANNEXE-03 — Bibliothèque de réseaux de neurones maison',['../lot-annexe-03.html',1,'lots-annexe']]],
  ['bibliothèque_20exécutable_20legacy_20conservé_34',['1. &lt;span class=&quot;tt&quot;&gt;HMI&lt;/span&gt; : exécutable → bibliothèque + exécutable legacy conservé',['../lot-34-tache-01-provisionnement-qt-build.html#autotoc_md1817',1,'']]],
  ['bibliothèque_20tensorielle_20et_20rng_20maison_35',['LOT-ANNEXE-01 — Bibliothèque tensorielle et RNG maison',['../lot-annexe-01.html',1,'lots-annexe']]],
  ['binaryop_36',['9. Pourquoi une fabrique générique d&apos;opérations (&lt;span class=&quot;tt&quot;&gt;unaryOp&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;binaryOp&lt;/span&gt;)',['../guide-annexe-autodiff.html#autotoc_md318',1,'']]],
  ['bindings_20et_20persistance_20json_37',['TACHE-01 — Modèle de bindings et persistance JSON',['../lot-29-tache-01-modele-bindings.html',1,'lot-29']]],
  ['bindings_20manette_38',['TACHE-01 — Modèle de bindings manette',['../lot-30-tache-01-modele-bindings-manette.html',1,'lot-30']]],
  ['bitmap_39',['TACHE-02 — Rendu de texte (police bitmap)',['../lot-06-tache-02-rendu-texte-bitmap.html',1,'lot-06']]],
  ['bitmap_20_3a_20atlas_20de_20glyphes_20et_20métriques_40',['TACHE-01 — Police bitmap : atlas de glyphes et métriques',['../lot-52-tache-01-police-bitmap.html',1,'lot-52']]],
  ['bitmap_20et_20affichage_20tête_20haute_41',['LOT-52 — Texte, police bitmap et affichage tête haute',['../lot-52.html',1,'lots']]],
  ['blend_20nearest_42',['TACHE-02 — Pipeline de quads texturés (HLSL, blend, nearest)',['../lot-05-tache-02-pipeline-quads-textures.html',1,'lot-05']]],
  ['bloc_20poussable_43',['LOT-21 — Bloc poussable',['../lot-21.html',1,'lots']]],
  ['bloc_20réduit_44',['TACHE-01 — Modèle de bloc réduit',['../lot-24-tache-01-modele-bloc-reduit.html',1,'lot-24']]],
  ['bloc_20réduit_20—_20test_5fbloc_5freduit_20cpp_202_45',['Bloc Réduit — &lt;span class=&quot;tt&quot;&gt;test_bloc_reduit.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md34',1,'']]],
  ['blocage_46',['TACHE-03 — Budget de pas et mesure de progression (blocage)',['../lot-annexe-05-tache-03-budget-pas-detection-blocage.html',1,'lot-annexe-05']]],
  ['blocs_20à_20taille_20fractionnaire_47',['LOT-24 — Blocs à taille fractionnaire',['../lot-24.html',1,'lots']]],
  ['blocs_20à_20taille_20réduite_20×0_205_20×0_2025_48',['Blocs à taille réduite (&lt;span class=&quot;tt&quot;&gt;×0.5&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;×0.25&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md189',1,'']]],
  ['blocs_20de_20danger_20avancés_49',['LOT-31 — Blocs de danger avancés',['../lot-31.html',1,'lots']]],
  ['blocs_20poussables_50',['Blocs poussables',['../guide-niveaux.html#autotoc_md188',1,'']]],
  ['blocs_20réduits_51',['TACHE-03 — Ombres des silhouettes et des blocs réduits',['../lot-55-tache-03-ombres-silhouettes.html',1,'lot-55']]],
  ['bloquant_52',['bloquant',['../lot-58-tache-03-clang-tidy.html',1,'TACHE-03 — `clang-tidy` câblé, trié, puis bloquant'],['../lot-annexe-04-tache-03-tests-convergence.html',1,'TACHE-03 — Tests de convergence sur fonctions jouets (bloquant)']]],
  ['boîte_53',['TACHE-02 — Collision boîte-contre-boîte',['../lot-24-tache-02-collision-boite-boite.html',1,'lot-24']]],
  ['boîte_20contre_20boîte_54',['TACHE-02 — Collision boîte-contre-boîte',['../lot-24-tache-02-collision-boite-boite.html',1,'lot-24']]],
  ['boîte_20de_20dialogue_20de_20redimensionnement_20ctrl_20r_55',['TACHE-02 — Boîte de dialogue de redimensionnement (Ctrl+R)',['../lot-16-tache-02-boite-dialogue-redimensionnement.html',1,'lot-16']]],
  ['boîte_20englobante_20alignée_20aux_20axes_56',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md172',1,'']]],
  ['bonnes_20pratiques_57',['7. Bonnes pratiques',['../spec-conventions.html#autotoc_md395',1,'']]],
  ['bonus_20de_20complétion_20pénalités_58',['TACHE-01 — Récompense de progression, bonus de complétion, pénalités',['../lot-annexe-08-tache-01-recompense-progression-bonus-penalites.html',1,'lot-annexe-08']]],
  ['bootstrap_20réel_20_3a_20sinks_20différents_20en_20développement_20et_20en_20release_59',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md166',1,'']]],
  ['bords_60',['TACHE-04 — Tests : déterminisme et stabilité dimensionnelle aux bords',['../lot-annexe-06-tache-04-tests-determinisme-dimension.html',1,'lot-annexe-06']]],
  ['bornée_20et_20seulement_20là_20où_20la_20caméra_20défile_61',['Parallaxe : portée par le plan, bornée, et seulement là où la caméra défile',['../guide-rendu.html#autotoc_md242',1,'']]],
  ['boucle_62',['boucle',['../guide-ecrans.html#autotoc_md101',1,'Où ça s&apos;insère dans la boucle'],['../lot-38-tache-03-retrait-legacy-ui.html',1,'TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)']]],
  ['boucle_20à_20pas_20de_20temps_20fixe_20testable_63',['TACHE-03 — Boucle à pas de temps fixe (testable)',['../lot-01-tache-03-boucle-pas-fixe.html',1,'lot-01']]],
  ['boucle_20_3a_20qt_20pilote_20le_20pas_20fixe_20est_20préservé_64',['La boucle : Qt pilote, le pas fixe est préservé',['../guide-ihm-qt.html#autotoc_md149',1,'']]],
  ['boucle_20d_20entraînement_20par_20épisodes_20et_20journalisation_65',['TACHE-04 — Boucle d&apos;entraînement par épisodes et journalisation',['../lot-annexe-12-tache-04-boucle-entrainement.html',1,'lot-annexe-12']]],
  ['boucle_20d_20entraînement_20pour_20un_20niveau_20et_20critère_20d_20arrêt_66',['TACHE-01 — Boucle d&apos;entraînement pour un niveau et critère d&apos;arrêt',['../lot-annexe-11-tache-01-boucle-entrainement.html',1,'lot-annexe-11']]],
  ['boucle_20d_20interaction_67',['1. Agent, environnement, boucle d&apos;interaction',['../guide-annexe-apprentissage-renforcement.html#autotoc_md291',1,'']]],
  ['boucle_20de_20génération_68',['TACHE-04 — Boucle de génération',['../lot-annexe-10-tache-04-boucle-generation.html',1,'lot-annexe-10']]],
  ['boucle_20de_20gameplay_69',['Boucle de gameplay',['../spec-vision.html#autotoc_md461',1,'']]],
  ['boucle_20de_20jeu_70',['boucle de jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../guide-boucle.html#autotoc_md66',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?']]],
  ['boucle_20de_20jeu_20complète_20_3a_20pause_20fin_20de_20niveau_20progression_71',['LOT-59 — Boucle de jeu complète : pause, fin de niveau, progression',['../lot-59.html',1,'lots']]],
  ['boucle_20de_20jeu_20direct3d_2011_72',['LOT-01 — Fenêtre &amp;amp; boucle de jeu (Direct3D 11)',['../lot-01.html',1,'lots']]],
  ['boucle_20de_20jeu_20et_20pas_20de_20temps_20fixe_73',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['boucle_20de_20rendu_20pilotée_20qt_74',['Boucle de rendu pilotée Qt',['../lot-34-tache-03-boucle-entrees-qt.html#autotoc_md1836',1,'']]],
  ['boucle_20de_20rendu_20qt_20pas_20fixe_20interpolation_20entrées_20qt_20→_20inputstate_75',['TACHE-03 — Boucle de rendu Qt (pas fixe, interpolation) + entrées Qt → `InputState`',['../lot-34-tache-03-boucle-entrees-qt.html',1,'lot-34']]],
  ['boucle_20pilotée_20par_20l_20écran_76',['TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)',['../lot-06-tache-07-integration-main.html',1,'lot-06']]],
  ['boucle_20scène_20de_20démo_77',['TACHE-06 — Câblage du World dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['boucle_20simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_78',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md35',1,'']]],
  ['boucle_20temps_79',['3. Boucle &amp;amp; temps',['../spec-rendu-technique.html#autotoc_md454',1,'']]],
  ['boutons_20_3a_20hmi_3a_3agamekeybindings_20gamekeybindings_20hmi_3a_3aeditorkeybindings_20editorkeybindings_20lot_2029_20hmi_3a_3agamepadbindings_20gamepadbindings_20lot_2030_80',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md143',1,'']]],
  ['branche_20fix_20clang_20tidy_20triage_20hors_20budget_20initial_20de_20ce_20lot_81',['Complément (branche &lt;span class=&quot;tt&quot;&gt;fix/clang-tidy-triage&lt;/span&gt;, hors budget initial de ce lot)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2745',1,'']]],
  ['bref_82',['En bref',['../index.html#autotoc_md1',1,'']]],
  ['brique_20gpu_83',['Vérification (visuelle, pas de test unitaire — brique GPU)',['../lot-11-tache-03-personnage-humanoide.html#autotoc_md1021',1,'']]],
  ['brouillon_84',['TACHE-01 — Route multi-points dans le modele, le format et le brouillon',['../lot-67-tache-01-route-multi-points.html',1,'lot-67']]],
  ['brouillon_20annulable_85',['TACHE-03 — Modèle de plan, format de niveau et brouillon annulable',['../lot-69-tache-03-modele-plan.html',1,'lot-69']]],
  ['brouillon_20initial_86',['Réalisé (écarts par rapport au brouillon initial)',['../lot-63-tache-04-integration-editeur-habillage.html#autotoc_md2985',1,'']]],
  ['bruit_20d_20observation_87',['TACHE-03 — Test de robustesse au bruit d&apos;observation',['../lot-annexe-15-tache-03-robustesse-bruit.html',1,'lot-annexe-15']]],
  ['bruitages_88',['LOT-60 — Audio : socle et bruitages',['../lot-60.html',1,'lots']]],
  ['brut_89',['TACHE-04 — Comparaison chiffrée de convergence vs REINFORCE brut',['../lot-annexe-13-tache-04-comparaison-convergence.html',1,'lot-annexe-13']]],
  ['brut_20dans_20la_20perte_20de_20politique_90',['TACHE-02 — Avantage remplaçant le retour brut dans la perte de politique',['../lot-annexe-13-tache-02-avantage.html',1,'lot-annexe-13']]],
  ['budget_20de_20mémoire_20de_20texture_91',['TACHE-09 — Budget de mémoire de texture',['../lot-69-tache-09-budget-memoire.html',1,'lot-69']]],
  ['budget_20de_20mouvements_92',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]],
  ['budget_20de_20mouvements_20et_20capacités_20du_20tableau_93',['Budget de mouvements et capacités du tableau',['../guide-niveaux.html#autotoc_md191',1,'']]],
  ['budget_20de_20pas_20et_20mesure_20de_20progression_20blocage_94',['TACHE-03 — Budget de pas et mesure de progression (blocage)',['../lot-annexe-05-tache-03-budget-pas-detection-blocage.html',1,'lot-annexe-05']]],
  ['budget_20de_20rendu_20mesuré_95',['LOT-62 — Budget de rendu mesuré',['../lot-62.html',1,'lots']]],
  ['budget_20de_20rendu_20mesuré_20lot_2062_96',['Budget de rendu mesuré (&lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt;)',['../guide-rendu.html#autotoc_md254',1,'']]],
  ['budget_20de_20sauts_20dashs_20dans_20la_20physique_97',['TACHE-03 — Budget de sauts/dashs dans la physique',['../lot-12-tache-03-budget.html',1,'lot-12']]],
  ['budget_20initial_20de_20ce_20lot_98',['Complément (branche &lt;span class=&quot;tt&quot;&gt;fix/clang-tidy-triage&lt;/span&gt;, hors budget initial de ce lot)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2745',1,'']]],
  ['budget_20player_20level_20levelloader_99',['TACHE-01 — Données : budget (Player, Level, LevelLoader)',['../lot-12-tache-01-donnees.html',1,'lot-12']]],
  ['budgets_100',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['budgets_20et_20tableau_20courant_101',['TACHE-03 — Affichage tête haute : budgets et tableau courant',['../lot-52-tache-03-hud.html',1,'lot-52']]],
  ['buffer_102',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['buffer_20et_20réseau_20cible_103',['2.3. Mémoire de rejeu (&lt;em&gt;replay buffer&lt;/em&gt;) et réseau cible',['../guide-annexe-ppo-dqn.html#autotoc_md342',1,'']]],
  ['buffering_104',['TACHE-04 — Coyote time + jump buffering',['../lot-09-tache-04-coyote-buffering.html',1,'lot-09']]],
  ['bugs_20pas_20des_20erreurs_20à_20gérer_105',['6. Pourquoi les erreurs de forme sont des bugs, pas des erreurs à gérer',['../guide-annexe-algebre-tensorielle.html#autotoc_md279',1,'']]],
  ['build_20dépendances_106',['6. Build &amp;amp; dépendances',['../spec-exigences.html#autotoc_md426',1,'']]],
  ['build_20test_20coverage_107',['4. Provisionnement CI (&lt;span class=&quot;tt&quot;&gt;.github/workflows/ci.yml&lt;/span&gt;, job &lt;span class=&quot;tt&quot;&gt;build-test-coverage&lt;/span&gt;)',['../lot-34-tache-01-provisionnement-qt-build.html#autotoc_md1820',1,'']]],
  ['buildlevelscene_108',['De la grille aux entités : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#a671cc58bea9439fdb3ea23009b0da54b&quot; title=&quot;core::buildLevelScene&quot;&gt;buildLevelScene&lt;/a&gt;',['../guide-niveaux.html#autotoc_md185',1,'']]],
  ['burst_20durée_20recharge_20au_20sol_109',['TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)',['../lot-10-tache-05-dash.html',1,'lot-10']]]
];
