var searchData=
[
  ['échec_0',['échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['écran_1',['écran',['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-05-tache-04-camera-2d.html',1,'TACHE-04 — Caméra 2D (monde → écran)'],['../lot-05-tache-05-systeme-rendu-sprites.html',1,'TACHE-05 — Système de rendu des sprites (ECS → écran)'],['../lot-06-tache-07-integration-main.html',1,'TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)']]],
  ['écran_20éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_2',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['écran_20de_20menu_20principal_3',['TACHE-05 — Écran de menu principal',['../lot-06-tache-05-ecran-menu-principal.html',1,'lot-06']]],
  ['écran_20présentation_20redimensionnement_4',['TACHE-04 — Effacement écran, présentation &amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['écrans_5',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['écrans_20cibles_20jeu_20démo_20éditeur_20placeholder_6',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['écrans_20et_20navigation_7',['Écrans et navigation',['../guide-ecrans.html',1,'guide']]],
  ['écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_8',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['écrasement_9',['TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'lot-15']]],
  ['éditeur_10',['éditeur',['../lot-29.html',1,'LOT-29 — Remappage des touches (jeu + éditeur)'],['../lot-29-tache-02-integration-jeu-editeur.html',1,'TACHE-02 — Intégration jeu/éditeur'],['../lot-32-tache-03-repere-editeur.html',1,'TACHE-03 — Repère visuel de salles dans l&apos;éditeur']]],
  ['éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_11',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['éditeur_20de_20niveaux_12',['Éditeur de niveaux',['../spec-editeur.html',1,'specifications']]],
  ['éditeur_20de_20niveaux_20_3a_20robustesse_20et_20confort_20d_20édition_13',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['éditeur_20de_20niveaux_20intégré_14',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['éditeur_20de_20niveaux_20intégré_20_3a_20édition_20de_20tuiles_20mécanismes_20essai_20immédiat_15',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['éditeur_20de_20texture_20pixel_20art_20intégré_16',['LOT-48 — Éditeur de texture pixel art intégré',['../lot-48.html',1,'lots']]],
  ['éditeur_20docking_20palette_20outils_20peinture_17',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['éditeur_20et_20jeu_18',['TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)',['../lot-16-tache-03-camera-niveau-entier.html',1,'lot-16']]],
  ['éditeur_20et_20jeu_20hmi_19',['TACHE-02 — Intégration éditeur et jeu (HMI)',['../lot-21-tache-02-integration-editeur-jeu.html',1,'lot-21']]],
  ['éditeur_20et_20niveau_20de_20démonstration_20',['TACHE-03 — Intégration éditeur et niveau de démonstration',['../lot-19-tache-03-editeur-niveau-demo.html',1,'lot-19']]],
  ['éditeur_20et_20rendu_21',['éditeur et rendu',['../lot-23-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-26-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-28-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-22-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu'],['../lot-24-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu']]],
  ['éditeur_20manette_22',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['éditeur_20organisée_20par_20catégories_23',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['éditeur_20palette_20rendu_20liaison_24',['TACHE-03 — Intégration éditeur (palette, rendu, liaison)',['../lot-31-tache-03-integration-editeur.html',1,'lot-31']]],
  ['éditeur_20placeholder_25',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['édition_26',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['édition_20de_20tuiles_20mécanismes_20essai_20immédiat_27',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['édition_20mutable_28',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['épinglé_29',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['état_20erreurs_20documentation_20vérification_30',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['états_20d_20application_20écrans_31',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]]
];
