var searchData=
[
  ['f8_20non_20remappable_0',['LOT-41 — Bascule Physique/Texture (`F8`, non remappable)',['../lot-41.html',1,'lots']]],
  ['façon_20celeste_1',['LOT-32 — Niveaux à salles (façon Celeste)',['../lot-32.html',1,'lots']]],
  ['fall_2',['TACHE-02 — Gravité asymétrique + apex hang + fast-fall',['../lot-11-tache-02-gravite-asymetrique.html',1,'lot-11']]],
  ['fast_20fall_3',['TACHE-02 — Gravité asymétrique + apex hang + fast-fall',['../lot-11-tache-02-gravite-asymetrique.html',1,'lot-11']]],
  ['feel_20et_20enchaînement_20de_20niveaux_4',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['feel_20taille_20placement_20du_20personnage_5',['TACHE-01 — Données : réglages de *feel* + taille/placement du personnage',['../lot-11-tache-01-donnees.html',1,'lot-11']]],
  ['fenêtre_20boucle_20de_20jeu_20direct3d_2011_6',['LOT-01 — Fenêtre &amp; boucle de jeu (Direct3D 11)',['../lot-01.html',1,'lots']]],
  ['fenêtre_20qt_20viewport_20qwindow_20embarqué_20→_20graphicsdevice_7',['TACHE-02 — Fenêtre Qt + viewport `QWindow` embarqué → `GraphicsDevice`',['../lot-34-tache-02-viewport-d3d11-embarque.html',1,'lot-34']]],
  ['fenêtre_20win32_20ancienne_20boucle_8',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['fenêtre_20win32_20pompe_20de_20messages_9',['TACHE-01 — Fenêtre Win32 &amp; pompe de messages',['../lot-01-tache-01-fenetre-win32.html',1,'lot-01']]],
  ['fichier_20interface_20conservée_20repli_20procédural_10',['TACHE-02 — `TextureAtlas` sur atlas fichier (interface conservée, repli procédural)',['../lot-39-tache-02-texture-atlas-fichier.html',1,'lot-39']]],
  ['fichier_20ligne_20horodatage_11',['TACHE-03 — Macros de log (fichier/ligne, horodatage)',['../lot-02-tache-03-macros-log.html',1,'lot-02']]],
  ['fichiers_12',['LOT-36 — Refonte IHM (Qt) : gestion des niveaux (liste, recherche, fichiers)',['../lot-36.html',1,'lots']]],
  ['fichiers_20créer_20renommer_20dupliquer_20supprimer_20couche_20testable_13',['TACHE-02 — Opérations fichiers (créer/renommer/dupliquer/supprimer) + couche testable',['../lot-36-tache-02-operations-fichiers.html',1,'lot-36']]],
  ['fichiers_20liste_20recherche_20filtre_14',['TACHE-01 — Panneau « Niveaux » (modèle fichiers + liste + recherche/filtre)',['../lot-36-tache-01-panneau-niveaux-recherche.html',1,'lot-36']]],
  ['fichiers_20loader_20assets_15',['LOT-39 — Refonte IHM (Qt) : textures depuis fichiers (loader + assets)',['../lot-39.html',1,'lots']]],
  ['filtre_16',['TACHE-01 — Panneau « Niveaux » (modèle fichiers + liste + recherche/filtre)',['../lot-36-tache-01-panneau-niveaux-recherche.html',1,'lot-36']]],
  ['fin_20de_20niveau_17',['TACHE-02 — Intégration jeu (contrôleurs, résolution de fin de niveau)',['../lot-31-tache-02-integration-jeu.html',1,'lot-31']]],
  ['fin_20de_20niveau_20succès_20échec_18',['TACHE-04 — Règles de fin de niveau (succès / échec)',['../lot-08-tache-04-regles-fin-niveau.html',1,'lot-08']]],
  ['finitions_19',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['fixe_20',['fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../lot-03-tache-05-systemes-world.html',1,'TACHE-05 — Systèmes &amp; World (orchestration au pas fixe)']]],
  ['fixe_20interpolation_20entrées_20qt_20→_20inputstate_21',['TACHE-03 — Boucle de rendu Qt (pas fixe, interpolation) + entrées Qt → `InputState`',['../lot-34-tache-03-boucle-entrees-qt.html',1,'lot-34']]],
  ['fixe_20succès_20échec_22',['TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)',['../lot-08-tache-06-integration-jouable.html',1,'lot-08']]],
  ['fixe_20testable_23',['TACHE-03 — Boucle à pas de temps fixe (testable)',['../lot-01-tache-03-boucle-pas-fixe.html',1,'lot-01']]],
  ['flèche_20pipeline_20géométrie_20des_20traits_20logique_20testable_24',['TACHE-01 — Primitive de ligne/flèche (pipeline) + géométrie des traits (logique testable)',['../lot-37-tache-01-primitive-ligne-geometrie.html',1,'lot-37']]],
  ['flèches_25',['LOT-37 — Refonte IHM (Qt) : liens de mécanismes visuels (traits/flèches)',['../lot-37.html',1,'lots']]],
  ['flip_20interpolation_26',['LOT-33 — Fluidité du moteur (entrées nerveuses, présentation flip, interpolation)',['../lot-33.html',1,'lots']]],
  ['flip_20model_20latence_20réduite_27',['TACHE-02 — Présentation flip-model (latence réduite)',['../lot-33-tache-02-presentation-flip.html',1,'lot-33']]],
  ['fluidité_20du_20moteur_20entrées_20nerveuses_20présentation_20flip_20interpolation_28',['LOT-33 — Fluidité du moteur (entrées nerveuses, présentation flip, interpolation)',['../lot-33.html',1,'lots']]],
  ['focus_20sondage_20manette_29',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]],
  ['fonction_20de_20hauteur_30',['TACHE-01 — Modèle de tuile et fonction de hauteur',['../lot-22-tache-01-modele-tuile-pente.html',1,'lot-22']]],
  ['fonctionnelles_31',['Exigences non fonctionnelles',['../spec-exigences.html',1,'specifications']]],
  ['fond_32',['LOT-46 — Ombres du plan physique sur le fond',['../lot-46.html',1,'lots']]],
  ['fond_20de_20niveau_33',['LOT-43 — Fond de niveau',['../lot-43.html',1,'lots']]],
  ['fondation_20ecs_20mathématiques_20core_34',['LOT-03 — Fondation ECS &amp; mathématiques Core',['../lot-03.html',1,'lots']]],
  ['fondations_20_3a_20registre_20de_20textures_20indépendantes_20rendu_20multi_20textures_35',['LOT-40 — Fondations : registre de textures indépendantes + rendu multi-textures',['../lot-40.html',1,'lots']]],
  ['format_20généralisation_20des_20liaisons_36',['TACHE-01 — Modèle (types, format, généralisation des liaisons)',['../lot-31-tache-01-modele-dangers-avances.html',1,'lot-31']]],
  ['formule_20de_20courbe_37',['TACHE-01 — Modèle de tuile et formule de courbe',['../lot-23-tache-01-modele-tuile-arrondie.html',1,'lot-23']]],
  ['formule_20de_20courbe_20concave_38',['TACHE-01 — Modèle de tuile et formule de courbe concave',['../lot-28-tache-01-modele-physique-concave.html',1,'lot-28']]],
  ['fou_20dirty_20indicateurs_20d_20état_20erreurs_20documentation_20vérification_39',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['fous_20_3a_20redimensionnement_20destructeur_20quitter_20sans_20enregistrer_40',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['fractionnaire_41',['LOT-24 — Blocs à taille fractionnaire',['../lot-24.html',1,'lots']]],
  ['fronts_20non_20perdus_20focus_20sondage_20manette_42',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]]
];
