var searchData=
[
  ['décisions_20dimensionnantes_0',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['décors_20pipeline_20pixel_20art_1',['Décors &amp; pipeline pixel art',['../spec-decors.html',1,'specifications']]],
  ['démo_2',['TACHE-06 — Composant `Transform` + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['déploiement_3',['TACHE-07 — CI documentation (WARN_AS_ERROR &amp; déploiement)',['../lot-04-tache-07-ci-docs.html',1,'lot-04']]],
  ['d_20accueil_20du_20projet_20mainpage_4',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]],
  ['dans_20main_20documentation_5',['TACHE-05 — Intégration dans `main` &amp; documentation',['../lot-02-tache-05-integration.html',1,'lot-02']]],
  ['de_20code_6',['Conventions de code',['../spec-conventions.html',1,'specifications']]],
  ['de_20composants_20sparse_20set_20typé_7',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['de_20core_8',['TACHE-01 — Types mathématiques de `Core`',['../lot-03-tache-01-math-core.html',1,'lot-03']]],
  ['de_20jeu_20direct3d_2011_9',['LOT-01 — Fenêtre &amp; boucle de jeu (Direct3D 11)',['../lot-01.html',1,'lots']]],
  ['de_20l_20arborescence_20documentaire_10',['de l arborescence documentaire',['../lot-04.html',1,'LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire'],['../lot-04-tache-01-reorganisation-arbo.html',1,'TACHE-01 — Réorganisation de l&apos;arborescence documentaire']]],
  ['de_20log_20fichier_20ligne_20horodatage_11',['TACHE-03 — Macros de log (fichier/ligne, horodatage)',['../lot-02-tache-03-macros-log.html',1,'lot-02']]],
  ['de_20log_20interface_20logger_12',['TACHE-01 — Niveaux de log &amp; interface `Logger`',['../lot-02-tache-01-niveaux-logger.html',1,'lot-02']]],
  ['de_20lots_20navigables_13',['TACHE-05 — Pages de lots navigables',['../lot-04-tache-05-pages-lots.html',1,'lot-04']]],
  ['de_20messages_14',['TACHE-01 — Fenêtre Win32 &amp; pompe de messages',['../lot-01-tache-01-fenetre-win32.html',1,'lot-01']]],
  ['de_20mouvement_20démo_15',['TACHE-06 — Composant `Transform` + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['de_20niveaux_16',['Éditeur de niveaux',['../spec-editeur.html',1,'specifications']]],
  ['de_20spécification_20navigables_20conventions_20incluses_17',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['de_20temps_20fixe_20testable_18',['TACHE-03 — Boucle à pas de temps fixe (testable)',['../lot-01-tache-03-boucle-pas-fixe.html',1,'lot-01']]],
  ['de_20vie_19',['TACHE-02 — Entités : handles générationnels &amp; cycle de vie',['../lot-03-tache-02-entites.html',1,'lot-03']]],
  ['des_20exigences_20ids_20stables_20ancres_20doxygen_20lint_20ci_20',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['diagnostics_21',['LOT-02 — Journalisation &amp; diagnostics',['../lot-02.html',1,'lots']]],
  ['dimensionnantes_22',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['direct3d_2011_23',['LOT-01 — Fenêtre &amp; boucle de jeu (Direct3D 11)',['../lot-01.html',1,'lots']]],
  ['direct3d_2011_20raii_24',['TACHE-02 — Initialisation Direct3D 11 (RAII)',['../lot-01-tache-02-init-direct3d11.html',1,'lot-01']]],
  ['documentaire_25',['documentaire',['../lot-04.html',1,'LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire'],['../lot-04-tache-01-reorganisation-arbo.html',1,'TACHE-01 — Réorganisation de l&apos;arborescence documentaire']]],
  ['documentation_26',['TACHE-05 — Intégration dans `main` &amp; documentation',['../lot-02-tache-05-integration.html',1,'lot-02']]],
  ['documentation_20doxygen_20réorganisation_20de_20l_20arborescence_20documentaire_27',['LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire',['../lot-04.html',1,'lots']]],
  ['documentation_20warn_5fas_5ferror_20déploiement_28',['TACHE-07 — CI documentation (WARN_AS_ERROR &amp; déploiement)',['../lot-04-tache-07-ci-docs.html',1,'lot-04']]],
  ['doxygen_20lint_20ci_29',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['doxygen_20pour_20le_20markdown_30',['TACHE-02 — Configuration Doxygen pour le Markdown',['../lot-04-tache-02-config-doxygen-markdown.html',1,'lot-04']]],
  ['doxygen_20réorganisation_20de_20l_20arborescence_20documentaire_31',['LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire',['../lot-04.html',1,'lots']]],
  ['du_20projet_20mainpage_32',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]]
];
