var searchData=
[
  ['périmètre_0',['Vision &amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['page_1',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['page_20d_20accueil_20du_20projet_20mainpage_2',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]],
  ['pages_20de_20lots_20navigables_3',['TACHE-05 — Pages de lots navigables',['../lot-04-tache-05-pages-lots.html',1,'lot-04']]],
  ['pages_20de_20spécification_20navigables_20conventions_20incluses_4',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['palette_20de_20l_20éditeur_20organisée_20par_20catégories_5',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['palette_20de_20tuiles_6',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['palette_20de_20tuiles_20qtreeview_20taxonomie_20lot_2027_20reliée_20à_20la_20sélection_7',['TACHE-02 — Palette de tuiles `QTreeView` (taxonomie `LOT-27`) reliée à la sélection',['../lot-35-tache-02-palette-arbre.html',1,'lot-35']]],
  ['palette_20en_20accordéon_20à_20trois_20niveaux_8',['TACHE-01 — Palette en accordéon à trois niveaux',['../lot-27-tache-01-palette-accordeon.html',1,'lot-27']]],
  ['palette_20outils_20peinture_9',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['palette_20rendu_20liaison_10',['TACHE-03 — Intégration éditeur (palette, rendu, liaison)',['../lot-31-tache-03-integration-editeur.html',1,'lot-31']]],
  ['pan_20et_20zoom_20manuels_11',['TACHE-04 — Caméra : pan et zoom manuels',['../lot-15-tache-04-camera-pan-zoom.html',1,'lot-15']]],
  ['panneau_20«_20liens_20»_20liste_20surbrillance_20suppression_20documentation_20vérification_12',['TACHE-03 — Panneau « Liens » (liste, surbrillance, suppression) ; documentation &amp; vérification',['../lot-37-tache-03-panneau-liens-doc.html',1,'lot-37']]],
  ['panneau_20«_20niveaux_20»_20modèle_20fichiers_20liste_20recherche_20filtre_13',['TACHE-01 — Panneau « Niveaux » (modèle fichiers + liste + recherche/filtre)',['../lot-36-tache-01-panneau-niveaux-recherche.html',1,'lot-36']]],
  ['par_20catégories_14',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['par_20l_20écran_15',['TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)',['../lot-06-tache-07-integration-main.html',1,'lot-06']]],
  ['par_20salle_20en_20jeu_20coupure_20nette_16',['TACHE-02 — Caméra par salle en jeu (coupure nette)',['../lot-32-tache-02-camera-salle-jeu.html',1,'lot-32']]],
  ['parkour_20»_20preuve_20système_17',['TACHE-06 — Niveau de démo « parkour » + preuve système',['../lot-10-tache-06-niveau-parkour.html',1,'lot-10']]],
  ['partager_20un_20niveau_20sans_20ligne_20de_20commande_18',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['partition_20en_20salles_20roomgrid_20logique_20pure_19',['TACHE-01 — Partition en salles (`RoomGrid`, logique pure)',['../lot-32-tache-01-partition-salles.html',1,'lot-32']]],
  ['pas_20de_20temps_20fixe_20',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['pas_20de_20temps_20fixe_20testable_21',['TACHE-03 — Boucle à pas de temps fixe (testable)',['../lot-01-tache-03-boucle-pas-fixe.html',1,'lot-01']]],
  ['pas_20fixe_22',['TACHE-05 — Systèmes &amp; World (orchestration au pas fixe)',['../lot-03-tache-05-systemes-world.html',1,'lot-03']]],
  ['pas_20fixe_20interpolation_20entrées_20qt_20→_20inputstate_23',['TACHE-03 — Boucle de rendu Qt (pas fixe, interpolation) + entrées Qt → `InputState`',['../lot-34-tache-03-boucle-entrees-qt.html',1,'lot-34']]],
  ['peinture_24',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['peinture_20viewport_20→_20leveldraft_20undo_20redo_20copier_20coller_25',['TACHE-03 — Barre d&apos;outils + peinture viewport → `LevelDraft` (undo/redo, copier/coller)',['../lot-35-tache-03-outils-peinture-viewport.html',1,'lot-35']]],
  ['pente_26',['TACHE-02 — Collision et suivi de pente',['../lot-22-tache-02-collision-suivi-pente.html',1,'lot-22']]],
  ['pentes_20et_20arrondis_20de_20plafond_27',['LOT-26 — Pentes et arrondis de plafond',['../lot-26.html',1,'lots']]],
  ['pentes_20réelles_28',['LOT-22 — Pentes réelles',['../lot-22.html',1,'lots']]],
  ['perdus_20focus_20sondage_20manette_29',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]],
  ['persistance_20json_30',['TACHE-01 — Modèle de bindings et persistance JSON',['../lot-29-tache-01-modele-bindings.html',1,'lot-29']]],
  ['persistance_20qsettings_20de_20la_20disposition_31',['TACHE-01 — `QMainWindow` à docks + persistance `QSettings` de la disposition',['../lot-35-tache-01-fenetre-docks-persistance.html',1,'lot-35']]],
  ['personnage_32',['personnage',['../guide-physique.html',1,'Physique du personnage'],['../lot-11-tache-01-donnees.html',1,'TACHE-01 — Données : réglages de *feel* + taille/placement du personnage']]],
  ['personnage_20_3a_20déplacement_20gravité_20et_20collisions_33',['LOT-08 — Gameplay personnage : déplacement, gravité et collisions',['../lot-08.html',1,'lots']]],
  ['personnage_20dans_20l_20atlas_34',['TACHE-01 — Silhouette du personnage dans l&apos;atlas',['../lot-17-tache-01-silhouette-personnage.html',1,'lot-17']]],
  ['personnage_20gravité_20déplacement_20collisions_35',['TACHE-03 — Physique du personnage (gravité + déplacement + collisions)',['../lot-08-tache-03-physique-personnage.html',1,'lot-08']]],
  ['personnage_20humanoïde_20gravité_20asymétrique_20finitions_36',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['personnage_20humanoïde_20spawn_200_204×0_208_20sprite_37',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['personnage_20intention_20d_20entrée_38',['TACHE-01 — Composants du personnage &amp; intention d&apos;entrée',['../lot-08-tache-01-composants-personnage.html',1,'lot-08']]],
  ['personnage_20repos_20course_20saut_39',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['personnage_20statique_40',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['physicsconfig_41',['physicsconfig',['../lot-10-tache-01-donnees.html',1,'TACHE-01 — Données des mécaniques (PlayerInput, Player, PhysicsConfig)'],['../lot-09-tache-01-donnees-saut.html',1,'TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig']]],
  ['physique_42',['TACHE-03 — Budget de sauts/dashs dans la physique',['../lot-12-tache-03-budget.html',1,'lot-12']]],
  ['physique_20de_20suivi_43',['TACHE-01 — Modèle de tuile et physique de suivi',['../lot-26-tache-01-modele-physique-plafond.html',1,'lot-26']]],
  ['physique_20du_20personnage_44',['Physique du personnage',['../guide-physique.html',1,'guide']]],
  ['physique_20du_20personnage_20gravité_20déplacement_20collisions_45',['TACHE-03 — Physique du personnage (gravité + déplacement + collisions)',['../lot-08-tache-03-physique-personnage.html',1,'lot-08']]],
  ['physique_20newtonienne_20et_20plaque_20de_20pression_46',['LOT-19 — Physique newtonienne et plaque de pression',['../lot-19.html',1,'lots']]],
  ['pilotée_20par_20l_20écran_47',['TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)',['../lot-06-tache-07-integration-main.html',1,'lot-06']]],
  ['pipeline_20de_20quads_20texturés_20hlsl_20blend_20nearest_48',['TACHE-02 — Pipeline de quads texturés (HLSL, blend, nearest)',['../lot-05-tache-02-pipeline-quads-textures.html',1,'lot-05']]],
  ['pipeline_20géométrie_20des_20traits_20logique_20testable_49',['TACHE-01 — Primitive de ligne/flèche (pipeline) + géométrie des traits (logique testable)',['../lot-37-tache-01-primitive-ligne-geometrie.html',1,'lot-37']]],
  ['pipeline_20pixel_20art_50',['Décors &amp; pipeline pixel art',['../spec-decors.html',1,'specifications']]],
  ['pixel_20art_51',['Décors &amp; pipeline pixel art',['../spec-decors.html',1,'specifications']]],
  ['placeholder_52',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['placement_20du_20personnage_53',['TACHE-01 — Données : réglages de *feel* + taille/placement du personnage',['../lot-11-tache-01-donnees.html',1,'lot-11']]],
  ['plafond_54',['LOT-26 — Pentes et arrondis de plafond',['../lot-26.html',1,'lots']]],
  ['plafond_20de_20taille_20et_20validation_20«_20largeur_20x_20hauteur_20»_55',['TACHE-01 — Plafond de taille et validation « largeur x hauteur »',['../lot-16-tache-01-plafond-validation-taille.html',1,'lot-16']]],
  ['plaque_20de_20pression_56',['plaque de pression',['../lot-19.html',1,'LOT-19 — Physique newtonienne et plaque de pression'],['../lot-19-tache-02-plaque-de-pression.html',1,'TACHE-02 — Plaque de pression']]],
  ['player_20level_20levelloader_57',['TACHE-01 — Données : budget (Player, Level, LevelLoader)',['../lot-12-tache-01-donnees.html',1,'lot-12']]],
  ['player_20physicsconfig_58',['player physicsconfig',['../lot-10-tache-01-donnees.html',1,'TACHE-01 — Données des mécaniques (PlayerInput, Player, PhysicsConfig)'],['../lot-09-tache-01-donnees-saut.html',1,'TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig']]],
  ['playerinput_20player_20physicsconfig_59',['playerinput player physicsconfig',['../lot-10-tache-01-donnees.html',1,'TACHE-01 — Données des mécaniques (PlayerInput, Player, PhysicsConfig)'],['../lot-09-tache-01-donnees-saut.html',1,'TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig']]],
  ['police_20bitmap_60',['TACHE-02 — Rendu de texte (police bitmap)',['../lot-06-tache-02-rendu-texte-bitmap.html',1,'lot-06']]],
  ['pompe_20de_20messages_61',['TACHE-01 — Fenêtre Win32 &amp; pompe de messages',['../lot-01-tache-01-fenetre-win32.html',1,'lot-01']]],
  ['porte_20budget_20de_20mouvements_62',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]],
  ['porte_20mechanismcontroller_63',['TACHE-02 — Mécanismes interrupteur/porte (MechanismController)',['../lot-12-tache-02-mecanismes.html',1,'lot-12']]],
  ['pour_20le_20markdown_64',['TACHE-02 — Configuration Doxygen pour le Markdown',['../lot-04-tache-02-config-doxygen-markdown.html',1,'lot-04']]],
  ['poussable_65',['LOT-21 — Bloc poussable',['../lot-21.html',1,'lots']]],
  ['présentation_20flip_20interpolation_66',['LOT-33 — Fluidité du moteur (entrées nerveuses, présentation flip, interpolation)',['../lot-33.html',1,'lots']]],
  ['présentation_20flip_20model_20latence_20réduite_67',['TACHE-02 — Présentation flip-model (latence réduite)',['../lot-33-tache-02-presentation-flip.html',1,'lot-33']]],
  ['présentation_20redimensionnement_68',['TACHE-04 — Effacement écran, présentation &amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['première_20page_69',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['pression_70',['pression',['../lot-19.html',1,'LOT-19 — Physique newtonienne et plaque de pression'],['../lot-19-tache-02-plaque-de-pression.html',1,'TACHE-02 — Plaque de pression']]],
  ['preuve_71',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['preuve_20système_72',['TACHE-06 — Niveau de démo « parkour » + preuve système',['../lot-10-tache-06-niveau-parkour.html',1,'lot-10']]],
  ['preuves_73',['TACHE-04 — Intégration GameScreen + niveau demo4 + preuves',['../lot-12-tache-04-integration-puzzle.html',1,'lot-12']]],
  ['preuves_20à_20la_20vraie_20taille_74',['TACHE-04 — Rééquilibrage des niveaux + preuves à la vraie taille',['../lot-11-tache-04-reequilibrage.html',1,'lot-11']]],
  ['primitive_20de_20ligne_20flèche_20pipeline_20géométrie_20des_20traits_20logique_20testable_75',['TACHE-01 — Primitive de ligne/flèche (pipeline) + géométrie des traits (logique testable)',['../lot-37-tache-01-primitive-ligne-geometrie.html',1,'lot-37']]],
  ['principal_76',['principal',['../lot-06.html',1,'LOT-06 — Menu principal'],['../lot-06-tache-05-ecran-menu-principal.html',1,'TACHE-05 — Écran de menu principal']]],
  ['principal_20qt_20navigation_20remplace_20iscreen_20screenmanager_77',['TACHE-01 — Menu principal Qt + navigation (remplace `IScreen`/`ScreenManager`)',['../lot-38-tache-01-menu-navigation-qt.html',1,'lot-38']]],
  ['procédural_78',['procédural',['../lot-39-tache-02-texture-atlas-fichier.html',1,'TACHE-02 — `TextureAtlas` sur atlas fichier (interface conservée, repli procédural)'],['../lot-05-tache-03-atlas-procedural.html',1,'TACHE-03 — Atlas de textures procédural']]],
  ['projectgaming_79',['ProjectGaming',['../index.html',1,'']]],
  ['projectgaming_5fassert_80',['TACHE-04 — Assertions PROJECTGAMING_ASSERT',['../lot-02-tache-04-assertions.html',1,'lot-02']]],
  ['projet_20mainpage_81',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]],
  ['provisionnement_20qt_20local_20ci_20release_20intégration_20cmake_20hmi_20en_20bibliothèque_82',['TACHE-01 — Provisionnement Qt (local + CI/release) &amp; intégration CMake ; `HMI` en bibliothèque',['../lot-34-tache-01-provisionnement-qt-build.html',1,'lot-34']]],
  ['pure_83',['pure',['../lot-32-tache-01-partition-salles.html',1,'TACHE-01 — Partition en salles (`RoomGrid`, logique pure)'],['../lot-08-tache-02-balayage-aabb.html',1,'TACHE-02 — Balayage AABB contre la grille (géométrie pure)']]],
  ['pures_84',['TACHE-01 — Composant Sprite (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['puzzle_20_3a_20mécanismes_20interrupteur_20porte_20budget_20de_20mouvements_85',['LOT-12 — Niveau puzzle : mécanismes interrupteur/porte + budget de mouvements',['../lot-12.html',1,'lots']]]
];
