var searchData=
[
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_0',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md75',1,'']]],
  ['écran_20éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_1',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['écran_20de_20menu_20principal_2',['TACHE-05 — Écran de menu principal',['../lot-06-tache-05-ecran-menu-principal.html',1,'lot-06']]],
  ['écrans_20cibles_20jeu_20démo_20éditeur_20placeholder_3',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['écrans_20et_20navigation_4',['Écrans et navigation',['../guide-ecrans.html',1,'guide']]],
  ['éditeur_5',['2. Éditeur',['../spec-interface-ihm.html#autotoc_md252',1,'']]],
  ['éditeur_20_3a_20docks_20palette_20peinture_20lot_2035_6',['Éditeur : docks, palette, peinture (LOT-35)',['../guide-ihm-qt.html#autotoc_md91',1,'']]],
  ['éditeur_20de_20niveaux_7',['Éditeur de niveaux',['../spec-editeur.html',1,'specifications']]],
  ['éditeur_20de_20niveaux_20—_20test_5fparcours_5fedition_20cpp_202_8',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md31',1,'']]],
  ['éditeur_20de_20niveaux_20_3a_20robustesse_20et_20confort_20d_20édition_9',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['éditeur_20de_20niveaux_20intégré_10',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['éditeur_20de_20niveaux_20intégré_20_3a_20édition_20de_20tuiles_20mécanismes_20essai_20immédiat_11',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['éditeur_20et_20rendu_12',['Éditeur et rendu',['../lot-23-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-26-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-28-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-22-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu'],['../lot-24-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu']]],
  ['égalité_20approchée_13',['Égalité approchée',['../guide-maths.html#autotoc_md108',1,'']]],
  ['émetteur_20de_20particules_20déterministe_14',['TACHE-01 — Émetteur de particules déterministe',['../lot-53-tache-01-emetteur-deterministe.html',1,'lot-53']]],
  ['étapes_15',['Étapes',['../manuel-telecharger.html#autotoc_md2536',1,'']]],
  ['états_20d_20application_20écrans_16',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['états_20de_20jeu_17',['5. États de jeu',['../spec-gameplay.html#autotoc_md249',1,'']]],
  ['états_20visuels_20des_20mécanismes_18',['LOT-47 — États visuels des mécanismes',['../lot-47.html',1,'lots']]],
  ['échantillonnage_20nearest_19',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['échec_20',['échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['échelle_20d_20affichage_21',['TACHE-05 — Netteté des vignettes à toute échelle d&apos;affichage',['../lot-56-tache-05-nettete-dpi.html',1,'lot-56']]],
  ['écran_22',['écran',['../guide-rendu.html#autotoc_md163',1,'&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteRenderer.html&quot; title=&quot;hmi::SpriteRenderer&quot;&gt;hmi::SpriteRenderer&lt;/a&gt; : le pont ECS → écran'],['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-53-tache-03-rendu-secousse.html',1,'TACHE-03 — Rendu des particules et secousse d&apos;écran'],['../lot-05-tache-04-camera-2d.html',1,'TACHE-04 — Caméra 2D (monde → écran)'],['../lot-05-tache-05-systeme-rendu-sprites.html',1,'TACHE-05 — Système de rendu des sprites (ECS → écran)'],['../lot-06-tache-07-integration-main.html',1,'TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)']]],
  ['écran_20présentation_20redimensionnement_23',['TACHE-04 — Effacement écran, présentation &amp;amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['écrans_24',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_25',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['écrasement_26',['écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement'],['../lot-54-tache-05-ouvrir-enregistrer.html',1,'TACHE-05 — Ouvrir, créer, enregistrer et garde-fou d&apos;écrasement']]],
  ['écrire_20jamais_20l_20inverse_27',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md68',1,'']]],
  ['éditer_20un_20niveau_20sans_20re_20coder_20le_20moteur_28',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md57',1,'']]],
  ['éditeur_29',['éditeur',['../spec-decors.html#autotoc_md216',1,'À la conception (éditeur)'],['../manuel-partager-niveau.html#autotoc_md2530',1,'2. Lancer l&apos;éditeur'],['../spec-decors.html#autotoc_md218',1,'3. Pipeline photo → pixel art (intégré à l&apos;éditeur)'],['../spec-editeur.html#autotoc_md226',1,'4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)'],['../guide-editeur.html#autotoc_md67',1,'Essai immédiat : jouer sans quitter l&apos;éditeur'],['../lot-29.html',1,'LOT-29 — Remappage des touches (jeu + éditeur)'],['../lot-50.html',1,'LOT-50 — Décors : placement et manipulation dans l&apos;éditeur'],['../lot-57.html',1,'LOT-57 — Architecture de l&apos;information de l&apos;éditeur'],['../lot-29-tache-02-integration-jeu-editeur.html',1,'TACHE-02 — Intégration jeu/éditeur'],['../lot-32-tache-03-repere-editeur.html',1,'TACHE-03 — Repère visuel de salles dans l&apos;éditeur'],['../lot-57-tache-04-deduplication-raccourcis.html',1,'TACHE-04 — Déduplication des commandes et raccourcis d&apos;éditeur'],['../lot-56-tache-06-theme-clair-sombre.html',1,'TACHE-06 — Thème clair et sombre de l&apos;éditeur']]],
  ['éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_30',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['éditeur_20docking_20palette_20outils_20peinture_31',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['éditeur_20et_20jeu_32',['éditeur et jeu',['../guide-ecrans.html#autotoc_md44',1,'Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu'],['../lot-16-tache-03-camera-niveau-entier.html',1,'TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)']]],
  ['éditeur_20et_20jeu_20hmi_33',['TACHE-02 — Intégration éditeur et jeu (HMI)',['../lot-21-tache-02-integration-editeur-jeu.html',1,'lot-21']]],
  ['éditeur_20et_20niveau_20de_20démonstration_34',['TACHE-03 — Intégration éditeur et niveau de démonstration',['../lot-19-tache-03-editeur-niveau-demo.html',1,'lot-19']]],
  ['éditeur_20fidèle_20au_20mode_20de_20rendu_35',['TACHE-05 — Palette de l&apos;éditeur fidèle au mode de rendu',['../lot-42-tache-05-palette-fidele.html',1,'lot-42']]],
  ['éditeur_20intégré_20»_36',['10. Contrainte « éditeur intégré »',['../spec-architecture.html#autotoc_md186',1,'']]],
  ['éditeur_20lot_2037_20ex_20ihm_20030_20ex_20ihm_20031_37',['Lier des mécanismes dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-IHM-030&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;EX-IHM-031&lt;/span&gt;)',['../guide-editeur.html#autotoc_md60',1,'']]],
  ['éditeur_20lot_2050_38',['Manipulation de décors dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-50&lt;/span&gt;)',['../guide-rendu.html#autotoc_md169',1,'']]],
  ['éditeur_20lot_2057_39',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-57)',['../spec-interface-ihm.html#autotoc_md257',1,'']]],
  ['éditeur_20manette_40',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['éditeur_20mvp_41',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md227',1,'']]],
  ['éditeur_20organisée_20par_20catégories_42',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['éditeur_20palette_20rendu_20liaison_43',['TACHE-03 — Intégration éditeur (palette, rendu, liaison)',['../lot-31-tache-03-integration-editeur.html',1,'lot-31']]],
  ['éditeur_20placeholder_44',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['édition_45',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['édition_20de_20tuiles_20mécanismes_20essai_20immédiat_46',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['édition_20lot_2015_47',['6. Robustesse et confort d&apos;édition (LOT-15)',['../spec-editeur.html#autotoc_md228',1,'']]],
  ['édition_20mutable_48',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['égalité_20stricte_20est_20dangereuse_49',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md111',1,'']]],
  ['épinglé_50',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['état_51',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md76',1,'']]],
  ['état_20_3a_20état_20permanent_20et_20aide_20contextuelle_52',['TACHE-01 — Barre d&apos;état : état permanent et aide contextuelle',['../lot-57-tache-01-barre-etat.html',1,'lot-57']]],
  ['état_20du_20personnage_53',['TACHE-02 — Déclencheurs depuis les transitions d&apos;état du personnage',['../lot-53-tache-02-declencheurs.html',1,'lot-53']]],
  ['état_20en_20intention_20_3a_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_54',['Traduire l&apos;état en intention : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a2c3341857c60f0bef0a01a6cd10ce5f7&quot; title=&quot;hmi::toPlayerInput&quot;&gt;hmi::toPlayerInput&lt;/a&gt;',['../guide-entrees.html#autotoc_md79',1,'']]],
  ['état_20erreurs_20documentation_20vérification_55',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp;amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['état_20et_20historique_20visuel_56',['TACHE-04 — Actions, barre d&apos;outils, état et historique visuel',['../lot-54-tache-04-actions-barre-outils.html',1,'lot-54']]],
  ['état_20logique_20→_20clip_57',['TACHE-01 — Correspondance état logique → clip',['../lot-47-tache-01-correspondance-etat-clip.html',1,'lot-47']]],
  ['état_20partagé_58',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md89',1,'']]],
  ['état_20permanent_20et_20aide_20contextuelle_59',['TACHE-01 — Barre d&apos;état : état permanent et aide contextuelle',['../lot-57-tache-01-barre-etat.html',1,'lot-57']]],
  ['états_20de_20gameplay_20livrés_60',['TACHE-02 — Clips couvrant les états de gameplay livrés',['../lot-48-tache-02-nouveaux-clips.html',1,'lot-48']]],
  ['événements_20qt_20vers_20l_20état_20partagé_61',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md89',1,'']]],
  ['éviter_20la_20racine_20carrée_62',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md107',1,'']]]
];
