var searchData=
[
  ['écart_20assumé_20par_20rapport_20au_20cadrage_20initial_0',['Écart assumé par rapport au cadrage initial',['../lot-69-tache-03-modele-plan.html#autotoc_md3278',1,'']]],
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_1',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md136',1,'']]],
  ['écran_20éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_2',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['écran_20aimodescreen_20trois_20onglets_3',['TACHE-02 — Écran AiModeScreen (trois onglets)',['../lot-annexe-21-tache-02-ai-mode-screen.html',1,'lot-annexe-21']]],
  ['écran_20de_20fin_20de_20niveau_20et_20de_20fin_20de_20séquence_4',['TACHE-03 — Écran de fin de niveau et de fin de séquence',['../lot-59-tache-03-ecran-fin-niveau.html',1,'lot-59']]],
  ['écran_20de_20menu_20principal_5',['TACHE-05 — Écran de menu principal',['../lot-06-tache-05-ecran-menu-principal.html',1,'lot-06']]],
  ['écran_20de_20pause_20et_20suspension_20du_20pas_20fixe_6',['TACHE-02 — Écran de pause et suspension du pas fixe',['../lot-59-tache-02-ecran-pause.html',1,'lot-59']]],
  ['écrans_20cibles_20jeu_20démo_20éditeur_20placeholder_7',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['écrans_20navigation_20et_20boucle_20de_20jeu_8',['Écrans, navigation et boucle de jeu',['../guide-ecrans.html',1,'guide']]],
  ['écrire_20un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_9',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md50',1,'']]],
  ['éditeur_10',['2. Éditeur',['../spec-interface-ihm.html#autotoc_md443',1,'']]],
  ['éditeur_20_3a_20docks_20palette_20peinture_20lot_2035_11',['Éditeur : docks, palette, peinture (LOT-35)',['../guide-ihm-qt.html#autotoc_md152',1,'']]],
  ['éditeur_20de_20niveaux_12',['Éditeur de niveaux',['../spec-editeur.html',1,'specifications']]],
  ['éditeur_20de_20niveaux_20—_20test_5fparcours_5fedition_20cpp_204_13',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (4)',['../cahiertest.html#autotoc_md46',1,'']]],
  ['éditeur_20de_20niveaux_20_3a_20robustesse_20et_20confort_20d_20édition_14',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['éditeur_20de_20niveaux_20intégré_15',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['éditeur_20de_20niveaux_20intégré_20_3a_20édition_20de_20tuiles_20mécanismes_20essai_20immédiat_16',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['éditeur_20et_20rendu_17',['Éditeur et rendu',['../lot-23-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-26-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-28-tache-02-editeur-rendu.html',1,'TACHE-02 — Éditeur et rendu'],['../lot-22-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu'],['../lot-24-tache-03-editeur-rendu.html',1,'TACHE-03 — Éditeur et rendu']]],
  ['édition_18',['2. Édition',['../spec-decors.html#autotoc_md403',1,'']]],
  ['égalité_20approchée_19',['Égalité approchée',['../guide-maths.html#autotoc_md171',1,'']]],
  ['émetteur_20de_20particules_20déterministe_20',['TACHE-01 — Émetteur de particules déterministe',['../lot-53-tache-01-emetteur-deterministe.html',1,'lot-53']]],
  ['épisode_20horizon_21',['7. Épisode, horizon',['../guide-annexe-apprentissage-renforcement.html#autotoc_md305',1,'']]],
  ['étapes_22',['Étapes',['../manuel-telecharger.html#autotoc_md4244',1,'']]],
  ['état_23',['État',['../lot-59-tache-01-machine-etats-ecrans.html#autotoc_md2792',1,'État'],['../lot-59-tache-02-ecran-pause.html#autotoc_md2800',1,'État'],['../lot-59-tache-03-ecran-fin-niveau.html#autotoc_md2808',1,'État'],['../lot-59-tache-04-sequence-en-donnee.html#autotoc_md2816',1,'État'],['../lot-59-tache-05-progression-persistee.html#autotoc_md2824',1,'État'],['../lot-59-tache-06-selection-niveau.html#autotoc_md2832',1,'État'],['../lot-59-tache-07-documentation-verification.html#autotoc_md2840',1,'État'],['../lot-60-tache-01-socle-qt-multimedia.html#autotoc_md2857',1,'État'],['../lot-60-tache-02-catalogue-sons.html#autotoc_md2865',1,'État'],['../lot-60-tache-03-declencheurs.html#autotoc_md2873',1,'État'],['../lot-60-tache-04-volume-options.html#autotoc_md2881',1,'État'],['../lot-60-tache-05-documentation-verification.html#autotoc_md2889',1,'État']]],
  ['état_20de_20la_20mesure_20lot_2058_24',['État de la mesure (LOT-58)',['../lot-58-tache-05-couverture.html#autotoc_md2765',1,'']]],
  ['état_20de_20la_20vérification_20lot_2058_20—_20mode_20local_20sans_20pr_20ni_20push_25',['État de la vérification (LOT-58) — mode local, sans PR ni push',['../lot-58-tache-06-documentation-verification.html#autotoc_md2773',1,'']]],
  ['état_20des_20mécanismes_20actifs_20dans_20la_20fenêtre_26',['TACHE-03 — État des mécanismes actifs dans la fenêtre',['../lot-annexe-06-tache-03-etat-mecanismes-fenetre.html',1,'lot-annexe-06']]],
  ['état_20du_20triage_20lot_2058_20passe_20complète_20sur_20129_20fichiers_20source_20cpp_20hors_20source_20test_27',['État du triage (LOT-58, passe complète sur 129 fichiers &lt;span class=&quot;tt&quot;&gt;Source/*.cpp&lt;/span&gt; hors &lt;span class=&quot;tt&quot;&gt;Source/Test&lt;/span&gt;)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2749',1,'']]],
  ['état_20initial_20constaté_28',['État initial constaté',['../lot-65-tache-01-inventaire-garde-fou.html#autotoc_md3070',1,'État initial constaté'],['../lot-65-tache-05-doctrine-gardes-fous-profondeur.html#autotoc_md3103',1,'État initial constaté']]],
  ['état_20observation_29',['2. État, observation',['../guide-annexe-apprentissage-renforcement.html#autotoc_md292',1,'']]],
  ['états_20d_20application_20écrans_30',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['états_20de_20jeu_31',['5. États de jeu',['../spec-gameplay.html#autotoc_md435',1,'']]],
  ['états_20visuels_20des_20mécanismes_32',['LOT-47 — États visuels des mécanismes',['../lot-47.html',1,'lots']]],
  ['évaluation_20de_20fitness_33',['TACHE-02 — Évaluation de fitness',['../lot-annexe-10-tache-02-evaluation-fitness.html',1,'lot-annexe-10']]],
  ['évaluation_20et_20reproductibilité_20en_20rl_34',['Évaluation et reproductibilité en RL',['../guide-annexe-evaluation-rl.html',1,'guide-annexe']]],
  ['évaluation_20et_20robustesse_35',['Évaluation et robustesse',['../spec-ia.html#autotoc_md440',1,'4. Évaluation et robustesse'],['../lots-annexe.html#autotoc_md4220',1,'Génération 4 — Évaluation et robustesse']]],
  ['évaluation_20hors_20niveau_20transfert_36',['Évaluation hors niveau transfert',['../lot-annexe-16.html',1,'LOT-ANNEXE-16 — Évaluation hors-niveau (transfert)'],['../lot-annexe-16-resultats-transfert.html',1,'Résultats — Évaluation hors-niveau (transfert)']]],
  ['écarts_20par_20rapport_20au_20brouillon_20initial_37',['Réalisé (écarts par rapport au brouillon initial)',['../lot-63-tache-04-integration-editeur-habillage.html#autotoc_md2990',1,'']]],
  ['échantillonnage_20nearest_38',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md226',1,'']]],
  ['échec_39',['échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['échelle_40',['3.3. Mettre les grandeurs continues à la même échelle',['../guide-annexe-apprentissage-renforcement.html#autotoc_md296',1,'']]],
  ['échelle_20d_20affichage_41',['échelle d affichage',['../guide-design-ihm.html#autotoc_md81',1,'Netteté à toute échelle d&apos;affichage'],['../lot-56-tache-05-nettete-dpi.html',1,'TACHE-05 — Netteté des vignettes à toute échelle d&apos;affichage']]],
  ['échelle_20lot_2068_42',['Deux identités, deux règles d&apos;échelle (LOT-68)',['../guide-design-ihm.html#autotoc_md87',1,'']]],
  ['écran_43',['écran',['../guide-rendu.html#autotoc_md234',1,'&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteRenderer.html&quot; title=&quot;hmi::SpriteRenderer&quot;&gt;hmi::SpriteRenderer&lt;/a&gt; : le pont ECS → écran'],['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-59-tache-01-machine-etats-ecrans.html',1,'TACHE-01 — Machine à états d&apos;écran'],['../lot-53-tache-03-rendu-secousse.html',1,'TACHE-03 — Rendu des particules et secousse d&apos;écran'],['../lot-05-tache-04-camera-2d.html',1,'TACHE-04 — Caméra 2D (monde → écran)'],['../lot-05-tache-05-systeme-rendu-sprites.html',1,'TACHE-05 — Système de rendu des sprites (ECS → écran)'],['../lot-06-tache-07-integration-main.html',1,'TACHE-07 — Intégration main (boucle pilotée par l&apos;écran)']]],
  ['écran_20hmi_3a_3acamera2d_44',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md251',1,'']]],
  ['écran_20lot_2053_45',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md248',1,'']]],
  ['écran_20présentation_20redimensionnement_46',['TACHE-04 — Effacement écran, présentation &amp;amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['écrans_47',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['écrans_20du_20jeu_20lot_2068_48',['8. Identité visuelle des écrans du jeu (LOT-68)',['../spec-interface-ihm.html#autotoc_md449',1,'']]],
  ['écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_49',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['écrasement_50',['écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement'],['../lot-54-tache-05-ouvrir-enregistrer.html',1,'TACHE-05 — Ouvrir, créer, enregistrer et garde-fou d&apos;écrasement']]],
  ['écrire_20jamais_20l_20inverse_51',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md124',1,'']]],
  ['écriture_20relecture_20stabilité_20du_20format_52',['TACHE-05 — Tests : écriture/relecture, stabilité du format',['../lot-annexe-09-tache-05-tests.html',1,'lot-annexe-09']]],
  ['éditables_53',['LOT-67 — Trajectoires et règles de tableau éditables',['../lot-67.html',1,'lots']]],
  ['éditer_20un_20niveau_20sans_20re_20coder_20le_20moteur_54',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['éditeur_55',['éditeur',['../manuel-partager-niveau.html#autotoc_md4236',1,'2. Lancer l&apos;éditeur'],['../spec-decors.html#autotoc_md404',1,'3. Pipeline photo → pixel art (intégré à l&apos;éditeur)'],['../spec-editeur.html#autotoc_md412',1,'4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)'],['../guide-editeur.html#autotoc_md123',1,'Essai immédiat : jouer sans quitter l&apos;éditeur'],['../lot-29.html',1,'LOT-29 — Remappage des touches (jeu + éditeur)'],['../lot-50.html',1,'LOT-50 — Décors : placement et manipulation dans l&apos;éditeur'],['../lot-57.html',1,'LOT-57 — Architecture de l&apos;information de l&apos;éditeur'],['../lot-29-tache-02-integration-jeu-editeur.html',1,'TACHE-02 — Intégration jeu/éditeur'],['../lot-64-tache-03-choix-previsualisation-editeur.html',1,'TACHE-03 — Choix et prévisualisation du cadrage dans l&apos;éditeur'],['../lot-32-tache-03-repere-editeur.html',1,'TACHE-03 — Repère visuel de salles dans l&apos;éditeur'],['../lot-57-tache-04-deduplication-raccourcis.html',1,'TACHE-04 — Déduplication des commandes et raccourcis d&apos;éditeur'],['../lot-56-tache-06-theme-clair-sombre.html',1,'TACHE-06 — Thème clair et sombre de l&apos;éditeur']]],
  ['éditeur_20_3a_20grille_20cliquable_20palette_20de_20tuiles_56',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['éditeur_20docking_20palette_20outils_20peinture_57',['LOT-35 — Refonte IHM (Qt) : éditeur (docking, palette, outils, peinture)',['../lot-35.html',1,'lots']]],
  ['éditeur_20et_20habillage_58',['TACHE-04 — Intégration éditeur et habillage',['../lot-63-tache-04-integration-editeur-habillage.html',1,'lot-63']]],
  ['éditeur_20et_20jeu_59',['éditeur et jeu',['../guide-ecrans.html#autotoc_md94',1,'Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu'],['../lot-16-tache-03-camera-niveau-entier.html',1,'TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)']]],
  ['éditeur_20et_20jeu_20hmi_60',['TACHE-02 — Intégration éditeur et jeu (HMI)',['../lot-21-tache-02-integration-editeur-jeu.html',1,'lot-21']]],
  ['éditeur_20et_20niveau_20de_20démonstration_61',['TACHE-03 — Intégration éditeur et niveau de démonstration',['../lot-19-tache-03-editeur-niveau-demo.html',1,'lot-19']]],
  ['éditeur_20fidèle_20au_20mode_20de_20rendu_62',['TACHE-05 — Palette de l&apos;éditeur fidèle au mode de rendu',['../lot-42-tache-05-palette-fidele.html',1,'lot-42']]],
  ['éditeur_20intégré_20»_63',['10. Contrainte « éditeur intégré »',['../spec-architecture.html#autotoc_md374',1,'']]],
  ['éditeur_20lot_2037_20ex_20ihm_20030_20ex_20ihm_20031_64',['Lier des mécanismes dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-IHM-030&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;EX-IHM-031&lt;/span&gt;)',['../guide-editeur.html#autotoc_md115',1,'']]],
  ['éditeur_20lot_2057_65',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-57)',['../spec-interface-ihm.html#autotoc_md448',1,'']]],
  ['éditeur_20manette_66',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['éditeur_20mvp_67',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md413',1,'']]],
  ['éditeur_20organisée_20par_20catégories_68',['LOT-27 — Palette de l&apos;éditeur organisée par catégories',['../lot-27.html',1,'lots']]],
  ['éditeur_20palette_20rendu_20liaison_69',['TACHE-03 — Intégration éditeur (palette, rendu, liaison)',['../lot-31-tache-03-integration-editeur.html',1,'lot-31']]],
  ['éditeur_20placeholder_70',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['édition_71',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['édition_20de_20tuiles_20mécanismes_20essai_20immédiat_72',['LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat',['../lot-14.html',1,'lots']]],
  ['édition_20lot_2015_73',['6. Robustesse et confort d&apos;édition (LOT-15)',['../spec-editeur.html#autotoc_md414',1,'']]],
  ['édition_20mutable_74',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['égalité_20stricte_20est_20dangereuse_75',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md174',1,'']]],
  ['élément_76',['3. Opérations élémentaires (élément par élément)',['../guide-annexe-algebre-tensorielle.html#autotoc_md276',1,'']]],
  ['élément_20mobile_77',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md119',1,'']]],
  ['élément_20par_20élément_78',['3. Opérations élémentaires (élément par élément)',['../guide-annexe-algebre-tensorielle.html#autotoc_md276',1,'']]],
  ['élémentaires_20élément_20par_20élément_79',['3. Opérations élémentaires (élément par élément)',['../guide-annexe-algebre-tensorielle.html#autotoc_md276',1,'']]],
  ['élémentaires_20et_20réductions_80',['TACHE-03 — Opérations élémentaires et réductions',['../lot-annexe-01-tache-03-operations-reductions.html',1,'lot-annexe-01']]],
  ['élitisme_81',['TACHE-03 — Sélection, croisement, mutation, élitisme',['../lot-annexe-10-tache-03-selection-croisement-mutation.html',1,'lot-annexe-10']]],
  ['émetteur_20dans_20core_20déterministe_20core_3a_3aparticlesystem_82',['L&apos;émetteur, dans &lt;span class=&quot;tt&quot;&gt;Core&lt;/span&gt;, déterministe (&lt;span class=&quot;tt&quot;&gt;core::ParticleSystem&lt;/span&gt;)',['../guide-rendu.html#autotoc_md249',1,'']]],
  ['épinglé_83',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['épinglé_20sur_20les_20trois_20environnements_84',['TACHE-01 — Qt épinglé sur les trois environnements',['../lot-66-tache-01-qt-epingle.html',1,'lot-66']]],
  ['épisode_85',['épisode',['../lot-annexe-08.html',1,'LOT-ANNEXE-08 — Fonction de récompense et critères d&apos;épisode'],['../lot-annexe-08-tache-02-detection-fin-episode.html',1,'TACHE-02 — Détection de fin d&apos;épisode']]],
  ['épisode_20complet_86',['TACHE-01 — Collecte de trajectoires sur un épisode complet',['../lot-annexe-12-tache-01-collecte-trajectoires.html',1,'lot-annexe-12']]],
  ['épisodes_20et_20journalisation_87',['TACHE-04 — Boucle d&apos;entraînement par épisodes et journalisation',['../lot-annexe-12-tache-04-boucle-entrainement.html',1,'lot-annexe-12']]],
  ['équation_20de_20bellman_20et_20l_20apprentissage_20par_20différence_20temporelle_88',['2.2. L&apos;équation de Bellman et l&apos;apprentissage par différence temporelle',['../guide-annexe-ppo-dqn.html#autotoc_md341',1,'']]],
  ['étanches_89',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md77',1,'']]],
  ['état_90',['état',['../guide-entrees.html#autotoc_md137',1,'Détecter les fronts, pas seulement l&apos;état'],['../lot-annexe-13-tache-01-reseau-critique.html',1,'TACHE-01 — Réseau critique (estimation de la valeur d&apos;état)'],['../lot-60-tache-03-declencheurs.html',1,'TACHE-03 — Déclencheurs depuis les transitions d&apos;état']]],
  ['état_20_3a_20état_20permanent_20et_20aide_20contextuelle_91',['TACHE-01 — Barre d&apos;état : état permanent et aide contextuelle',['../lot-57-tache-01-barre-etat.html',1,'lot-57']]],
  ['état_20du_20personnage_92',['TACHE-02 — Déclencheurs depuis les transitions d&apos;état du personnage',['../lot-53-tache-02-declencheurs.html',1,'lot-53']]],
  ['état_20en_20intention_20_3a_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_93',['Traduire l&apos;état en intention : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a2c3341857c60f0bef0a01a6cd10ce5f7&quot; title=&quot;hmi::toPlayerInput&quot;&gt;hmi::toPlayerInput&lt;/a&gt;',['../guide-entrees.html#autotoc_md140',1,'']]],
  ['état_20erreurs_20documentation_20vérification_94',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp;amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['état_20et_20historique_20visuel_95',['TACHE-04 — Actions, barre d&apos;outils, état et historique visuel',['../lot-54-tache-04-actions-barre-outils.html',1,'lot-54']]],
  ['état_20joueur_96',['TACHE-02 — Vecteur d&apos;état joueur',['../lot-annexe-06-tache-02-vecteur-etat-joueur.html',1,'lot-annexe-06']]],
  ['état_20logique_20→_20clip_97',['TACHE-01 — Correspondance état logique → clip',['../lot-47-tache-01-correspondance-etat-clip.html',1,'lot-47']]],
  ['état_20partagé_98',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md150',1,'']]],
  ['état_20permanent_20et_20aide_20contextuelle_99',['TACHE-01 — Barre d&apos;état : état permanent et aide contextuelle',['../lot-57-tache-01-barre-etat.html',1,'lot-57']]],
  ['état_20structurée_100',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md84',1,'']]],
  ['état_20un_20contrôle_101',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md86',1,'']]],
  ['états_20_3a_20hmi_3a_3ascreenflow_102',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md91',1,'']]],
  ['états_20d_20écran_103',['TACHE-01 — Machine à états d&apos;écran',['../lot-59-tache-01-machine-etats-ecrans.html',1,'lot-59']]],
  ['états_20de_20gameplay_20livrés_104',['TACHE-02 — Clips couvrant les états de gameplay livrés',['../lot-48-tache-02-nouveaux-clips.html',1,'lot-48']]],
  ['étendue_20et_20seuil_105',['TACHE-05 — Couverture étendue et seuil',['../lot-58-tache-05-couverture.html',1,'lot-58']]],
  ['événements_20qt_20vers_20l_20état_20partagé_106',['Les entrées : événements Qt vers l&apos;état partagé',['../guide-ihm-qt.html#autotoc_md150',1,'']]],
  ['évaluation_20ou_20à_20l_20export_107',['5. Pourquoi le critique n&apos;est jamais utilisé à l&apos;évaluation ou à l&apos;export',['../guide-annexe-acteur-critique.html#autotoc_md268',1,'']]],
  ['éviter_20la_20racine_20carrée_108',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md170',1,'']]],
  ['évolutionniste_109',['évolutionniste',['../guide-annexe-evaluation-rl.html#autotoc_md323',1,'3. Un cas particulier instructif : la politique évolutionniste'],['../lots-annexe.html#autotoc_md4218',1,'Génération 2 — Premier agent fonctionnel (évolutionniste)']]],
  ['évolutionniste_20maison_110',['LOT-ANNEXE-10 — Algorithme évolutionniste maison',['../lot-annexe-10.html',1,'lots-annexe']]],
  ['évolutionnistes_111',['Algorithmes évolutionnistes',['../guide-annexe-algorithmes-evolutionnistes.html',1,'guide-annexe']]]
];
