var searchData=
[
  ['sélecteur_20de_20langue_0',['TACHE-08 — Sélecteur de langue',['../lot-06-tache-08-selecteur-langue.html',1,'lot-06']]],
  ['sélection_20copier_20coller_1',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['séquence_20auto_20avance_20retour_20titre_2',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['séquence_20dont_20saut_20requis_20preuve_3',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['séquence_20et_20tests_20système_4',['TACHE-03 — Intégration séquence et tests système',['../lot-25-tache-03-integration-sequence-tests.html',1,'lot-25']]],
  ['sérialisation_20json_20modèle_20d_20édition_20mutable_5',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['salle_20en_20jeu_20coupure_20nette_6',['TACHE-02 — Caméra par salle en jeu (coupure nette)',['../lot-32-tache-02-camera-salle-jeu.html',1,'lot-32']]],
  ['salles_20dans_20l_20éditeur_7',['TACHE-03 — Repère visuel de salles dans l&apos;éditeur',['../lot-32-tache-03-repere-editeur.html',1,'lot-32']]],
  ['salles_20façon_20celeste_8',['LOT-32 — Niveaux à salles (façon Celeste)',['../lot-32.html',1,'lots']]],
  ['salles_20roomgrid_20logique_20pure_9',['TACHE-01 — Partition en salles (`RoomGrid`, logique pure)',['../lot-32-tache-01-partition-salles.html',1,'lot-32']]],
  ['sans_20enregistrer_10',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['sans_20ligne_20de_20commande_11',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['saut_12',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['saut_20_3a_20playerinput_20player_20physicsconfig_13',['TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig',['../lot-09-tache-01-donnees-saut.html',1,'lot-09']]],
  ['saut_20au_20sol_20hauteur_20variable_14',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['saut_20espace_20w_20→_20intention_15',['TACHE-02 — Mapping du saut (Espace/W → intention)',['../lot-09-tache-02-mapping-saut.html',1,'lot-09']]],
  ['saut_20game_20feel_20et_20enchaînement_20de_20niveaux_16',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['saut_20requis_20preuve_17',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['saut_20sauts_20aériens_20rechargés_20au_20sol_18',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['saut_20wall_20jump_20dash_19',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['sauts_20aériens_20rechargés_20au_20sol_20',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['sauts_20dashs_20dans_20la_20physique_21',['TACHE-03 — Budget de sauts/dashs dans la physique',['../lot-12-tache-03-budget.html',1,'lot-12']]],
  ['scène_20de_20démo_22',['TACHE-06 — Câblage du World dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['set_20typé_23',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['silhouette_20du_20personnage_20dans_20l_20atlas_24',['TACHE-01 — Silhouette du personnage dans l&apos;atlas',['../lot-17-tache-01-silhouette-personnage.html',1,'lot-17']]],
  ['sinks_20enfichables_25',['TACHE-02 — Sinks enfichables',['../lot-02-tache-02-sinks.html',1,'lot-02']]],
  ['slide_26',['TACHE-04 — Wall jump + wall slide',['../lot-10-tache-04-wall-jump.html',1,'lot-10']]],
  ['sol_27',['sol',['../lot-10-tache-03-double-saut.html',1,'TACHE-03 — Double saut (sauts aériens rechargés au sol)'],['../lot-10-tache-05-dash.html',1,'TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)']]],
  ['sol_20hauteur_20variable_28',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['sondage_20manette_29',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]],
  ['sortie_20liaison_20de_20mécanismes_20redimensionnement_30',['TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'lot-14']]],
  ['souris_31',['TACHE-01 — Entrées clavier &amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['spécification_20navigables_20conventions_20incluses_32',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['spécifications_33',['Spécifications',['../specifications.html',1,'index']]],
  ['spécifications_20et_20vérification_34',['TACHE-04 — Documentation, spécifications et vérification',['../lot-33-tache-04-documentation-verification.html',1,'lot-33']]],
  ['sparse_20set_20typé_35',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['spawn_200_204×0_208_20sprite_36',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['sprite_37',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['sprite_20données_20pures_38',['TACHE-01 — Composant Sprite (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['sprite_20du_20personnage_20statique_39',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['sprites_20caméra_40',['LOT-05 — Rendu 2D : atlas, sprites &amp; caméra',['../lot-05.html',1,'lots']]],
  ['sprites_20ecs_20→_20écran_41',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['squelette_20première_20page_42',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['stables_20ancres_20doxygen_20lint_20ci_43',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['statique_44',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['stockage_20de_20composants_20sparse_20set_20typé_45',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['structurées_46',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['succès_20échec_47',['succès échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['suivi_48',['TACHE-01 — Modèle de tuile et physique de suivi',['../lot-26-tache-01-modele-physique-plafond.html',1,'lot-26']]],
  ['suivi_20de_20pente_49',['TACHE-02 — Collision et suivi de pente',['../lot-22-tache-02-collision-suivi-pente.html',1,'lot-22']]],
  ['système_50',['système',['../lot-25-tache-03-integration-sequence-tests.html',1,'TACHE-03 — Intégration séquence et tests système'],['../lot-10-tache-06-niveau-parkour.html',1,'TACHE-06 — Niveau de démo « parkour » + preuve système']]],
  ['système_20d_20animation_51',['TACHE-01 — Composant et système d&apos;animation',['../lot-18-tache-01-composant-systeme-animation.html',1,'lot-18']]],
  ['système_20de_20mouvement_20démo_52',['TACHE-06 — Composant Transform + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['système_20de_20rendu_20des_20sprites_20ecs_20→_20écran_53',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['système_20guide_20non_20codeur_20git_54',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['systèmes_55',['ECS : entités, composants, systèmes',['../guide-ecs.html',1,'guide']]],
  ['systèmes_20world_20orchestration_20au_20pas_20fixe_56',['TACHE-05 — Systèmes &amp; World (orchestration au pas fixe)',['../lot-03-tache-05-systemes-world.html',1,'lot-03']]]
];
