var searchData=
[
  ['câblage_20du_20world_20dans_20la_20boucle_20scène_20de_20démo_0',['TACHE-06 — Câblage du `World` dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['caméra_1',['LOT-05 — Rendu 2D : atlas, sprites &amp; caméra',['../lot-05.html',1,'lots']]],
  ['caméra_202d_20monde_20→_20écran_2',['TACHE-04 — Caméra 2D (monde → écran)',['../lot-05-tache-04-camera-2d.html',1,'lot-05']]],
  ['catalogue_20de_20traduction_20i18n_3',['TACHE-03 — Catalogue de traduction (i18n)',['../lot-06-tache-03-catalogue-traduction.html',1,'lot-06']]],
  ['chargement_4',['LOT-07 — Niveaux : modèle et chargement',['../lot-07.html',1,'lots']]],
  ['chargement_20du_20niveau_20json_5',['TACHE-03 — Chargement du niveau (JSON)',['../lot-07-tache-03-chargement-json.html',1,'lot-07']]],
  ['charger_20niveau_20»_6',['TACHE-06 — Rendu du niveau + intégration « Charger niveau »',['../lot-07-tache-06-rendu-integration.html',1,'lot-07']]],
  ['ci_7',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['ci_20documentation_20warn_5fas_5ferror_20déploiement_8',['TACHE-07 — CI documentation (WARN_AS_ERROR &amp; déploiement)',['../lot-04-tache-07-ci-docs.html',1,'lot-04']]],
  ['cible_20technique_9',['Rendu &amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['cibles_20jeu_20démo_20éditeur_20placeholder_10',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['clavier_20souris_11',['TACHE-01 — Entrées clavier &amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['code_12',['Conventions de code',['../spec-conventions.html',1,'specifications']]],
  ['composant_20sprite_20données_20pures_13',['TACHE-01 — Composant `Sprite` (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['composant_20transform_20système_20de_20mouvement_20démo_14',['TACHE-06 — Composant `Transform` + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['composants_15',['TACHE-04 — Requêtes / vues multi-composants',['../lot-03-tache-04-vues-requetes.html',1,'lot-03']]],
  ['composants_20sparse_20set_20typé_16',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['configuration_20doxygen_20pour_20le_20markdown_17',['TACHE-02 — Configuration Doxygen pour le Markdown',['../lot-04-tache-02-config-doxygen-markdown.html',1,'lot-04']]],
  ['contenu_18',['Niveaux &amp; contenu',['../spec-niveaux.html',1,'specifications']]],
  ['contrôles_20entrées_19',['Contrôles &amp; entrées',['../spec-controles.html',1,'specifications']]],
  ['conventions_20de_20code_20',['Conventions de code',['../spec-conventions.html',1,'specifications']]],
  ['conventions_20incluses_21',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['core_22',['core',['../lot-03.html',1,'LOT-03 — Fondation ECS &amp; mathématiques `Core`'],['../lot-03-tache-01-math-core.html',1,'TACHE-01 — Types mathématiques de `Core`']]],
  ['cycle_20de_20vie_23',['TACHE-02 — Entités : handles générationnels &amp; cycle de vie',['../lot-03-tache-02-entites.html',1,'lot-03']]]
];
