var searchData=
[
  ['sélecteur_20de_20jeu_20de_20skins_0',['TACHE-03 — Section « Fond » et sélecteur de jeu de skins',['../lot-44-tache-03-section-fond.html',1,'lot-44']]],
  ['sélecteur_20de_20langue_1',['TACHE-08 — Sélecteur de langue',['../lot-06-tache-08-selecteur-langue.html',1,'lot-06']]],
  ['sélection_2',['TACHE-02 — Palette de tuiles `QTreeView` (taxonomie `LOT-27`) reliée à la sélection',['../lot-35-tache-02-palette-arbre.html',1,'lot-35']]],
  ['sélection_20copier_20coller_3',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['sélection_20de_20niveau_20côté_20joueur_4',['TACHE-06 — Sélection de niveau côté joueur',['../lot-59-tache-06-selection-niveau.html',1,'lot-59']]],
  ['sélection_20poignées_20et_20aimantation_5',['TACHE-03 — Rendu de la sélection, poignées et aimantation',['../lot-50-tache-03-selection-poignees.html',1,'lot-50']]],
  ['séparés_20du_20canevas_6',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md85',1,'']]],
  ['séquence_7',['TACHE-03 — Écran de fin de niveau et de fin de séquence',['../lot-59-tache-03-ecran-fin-niveau.html',1,'lot-59']]],
  ['séquence_20auto_20avance_20retour_20titre_8',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['séquence_20de_20niveaux_20démo_9',['La séquence de niveaux démo',['../guide-ecrans.html#autotoc_md67',1,'']]],
  ['séquence_20de_20niveaux_20en_20donnée_20de_20contenu_10',['TACHE-04 — Séquence de niveaux en donnée de contenu',['../lot-59-tache-04-sequence-en-donnee.html',1,'lot-59']]],
  ['séquence_20dont_20saut_20requis_20preuve_11',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['séquence_20et_20tests_20système_12',['TACHE-03 — Intégration séquence et tests système',['../lot-25-tache-03-integration-sequence-tests.html',1,'lot-25']]],
  ['séquencement_13',['4. Périmètre &amp;amp; séquencement',['../spec-decors.html#autotoc_md244',1,'']]],
  ['sérialisation_14',['TACHE-01 — *coreDecor* : modèle, couches et sérialisation',['../lot-49-tache-01-modele-decor.html',1,'lot-49']]],
  ['sérialisation_20json_20modèle_20d_20édition_20mutable_15',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['s_20insère_20dans_20la_20boucle_16',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md68',1,'']]],
  ['sa_20propre_20catégorie_17',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md123',1,'']]],
  ['salle_18',['TACHE-03 — Parallaxe et arbitrage avec la caméra par salle',['../lot-49-tache-03-parallaxe.html',1,'lot-49']]],
  ['salle_20en_20jeu_20coupure_20nette_19',['TACHE-02 — Caméra par salle en jeu (coupure nette)',['../lot-32-tache-02-camera-salle-jeu.html',1,'lot-32']]],
  ['salle_20visible_20',['TACHE-05 — Culling par salle visible',['../lot-40-tache-05-culling-salle.html',1,'lot-40']]],
  ['salles_20dans_20l_20éditeur_21',['TACHE-03 — Repère visuel de salles dans l&apos;éditeur',['../lot-32-tache-03-repere-editeur.html',1,'lot-32']]],
  ['salles_20façon_20celeste_22',['LOT-32 — Niveaux à salles (façon Celeste)',['../lot-32.html',1,'lots']]],
  ['salles_20lot_2032_23',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md257',1,'']]],
  ['salles_20roomgrid_20logique_20pure_24',['TACHE-01 — Partition en salles (`RoomGrid`, logique pure)',['../lot-32-tache-01-partition-salles.html',1,'lot-32']]],
  ['sanitizer_20et_20analyse_20statique_25',['LOT-58 — Vérification Release, sanitizer et analyse statique',['../lot-58.html',1,'lots']]],
  ['sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_26',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md87',1,'']]],
  ['sans_20enregistrer_27',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['sans_20jamais_20laisser_20de_20fichier_20tronqué_28',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['sans_20les_20confondre_20avec_20f8_20lot_2051_29',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['sans_20ligne_20de_20commande_30',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['sans_20pas_20de_20simulation_20et_20les_20entrées_31',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md49',1,'']]],
  ['sans_20pr_20ni_20push_32',['État de la vérification (LOT-58) — mode local, sans PR ni push',['../lot-58-tache-06-documentation-verification.html#autotoc_md2604',1,'']]],
  ['sans_20quitter_20l_20éditeur_33',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md89',1,'']]],
  ['sans_20re_20coder_20le_20moteur_34',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md79',1,'']]],
  ['sans_20repli_35',['TACHE-02 — Affichage isolé sans repli',['../lot-51-tache-02-affichage-isole.html',1,'lot-51']]],
  ['saut_36',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['saut_20_3a_20playerinput_20player_20physicsconfig_37',['TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig',['../lot-09-tache-01-donnees-saut.html',1,'lot-09']]],
  ['saut_20au_20sol_20hauteur_20variable_38',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['saut_20espace_20w_20→_20intention_39',['TACHE-02 — Mapping du saut (Espace/W → intention)',['../lot-09-tache-02-mapping-saut.html',1,'lot-09']]],
  ['saut_20et_20game_20feel_40',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md166',1,'']]],
  ['saut_20game_20feel_20et_20enchaînement_20de_20niveaux_41',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['saut_20requis_20preuve_42',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['saut_20sauts_20aériens_20rechargés_20au_20sol_43',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['saut_20wall_20jump_20dash_44',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['sauts_20aériens_20rechargés_20au_20sol_45',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['sauts_20dashs_20dans_20la_20physique_46',['TACHE-03 — Budget de sauts/dashs dans la physique',['../lot-12-tache-03-budget.html',1,'lot-12']]],
  ['scène_20_3a_20hmi_3a_3abitmapfont_20et_20hmi_3a_3atextrenderer_20lot_2052_47',['Le texte dans la scène : &lt;span class=&quot;tt&quot;&gt;hmi::BitmapFont&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::TextRenderer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-52&lt;/span&gt;)',['../guide-rendu.html#autotoc_md194',1,'']]],
  ['scène_20de_20démo_48',['TACHE-06 — Câblage du World dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['screenmanager_49',['TACHE-01 — Menu principal Qt + navigation (remplace `IScreen`/`ScreenManager`)',['../lot-38-tache-01-menu-navigation-qt.html',1,'lot-38']]],
  ['se_20lier_20à_20qui_50',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md81',1,'']]],
  ['se_20voit_20_3a_20le_20culling_20lot_2040_51',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md188',1,'']]],
  ['seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_52',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md102',1,'']]],
  ['secousse_20d_20écran_53',['TACHE-03 — Rendu des particules et secousse d&apos;écran',['../lot-53-tache-03-rendu-secousse.html',1,'lot-53']]],
  ['section_20«_20animations_20»_20du_20panneau_20«_20textures_20»_54',['TACHE-04 — Section « Animations » du panneau « Textures »',['../lot-47-tache-04-section-animations.html',1,'lot-47']]],
  ['section_20«_20décors_20»_20du_20panneau_20«_20textures_20»_55',['TACHE-04 — Section « Décors » du panneau « Textures »',['../lot-50-tache-04-section-decors.html',1,'lot-50']]],
  ['section_20«_20fond_20»_20et_20sélecteur_20de_20jeu_20de_20skins_56',['TACHE-03 — Section « Fond » et sélecteur de jeu de skins',['../lot-44-tache-03-section-fond.html',1,'lot-44']]],
  ['section_20«_20objets_20»_20et_20priorité_20de_20résolution_57',['TACHE-03 — Section « Objets » et priorité de résolution',['../lot-45-tache-03-section-objets-priorite.html',1,'lot-45']]],
  ['section_20skins_58',['TACHE-04 — Panneau Qt « Textures » (section Skins)',['../lot-42-tache-04-panneau-textures.html',1,'lot-42']]],
  ['segment_20orienté_20liens_20de_20mécanismes_20lot_2037_59',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md180',1,'']]],
  ['ses_20fichiers_20de_20niveaux_60',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['set_20core_3a_3acomponentpool_61',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md73',1,'']]],
  ['set_20typé_62',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['seuil_63',['TACHE-05 — Couverture étendue et seuil',['../lot-58-tache-05-couverture.html',1,'lot-58']]],
  ['seule_20cible_20_3a_20l_20application_20qt_64',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md108',1,'']]],
  ['seule_20paire_20annuler_20refaire_20deux_20cibles_65',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['seule_20source_20deux_20portées_20étanches_66',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md53',1,'']]],
  ['seulement_20l_20état_67',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md98',1,'']]],
  ['seulement_20l_20arrivée_68',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md155',1,'']]],
  ['shaders_20et_20échantillonnage_20nearest_69',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md179',1,'']]],
  ['si_20logique_70',['Tests (obligatoires si logique)',['../lot-05-tache-01-composant-sprite.html#autotoc_md518',1,'']]],
  ['signaux_71',['signaux',['../guide-ecrans.html#autotoc_md64',1,'Le principe : des pages empilées, pilotées par signaux'],['../guide-ecrans.html#autotoc_md65',1,'Qui déclenche les transitions : les signaux']]],
  ['silencieux_72',['TACHE-02 — Catalogue de sons et repli silencieux',['../lot-60-tache-02-catalogue-sons.html',1,'lot-60']]],
  ['silhouette_20du_20personnage_20dans_20l_20atlas_73',['TACHE-01 — Silhouette du personnage dans l&apos;atlas',['../lot-17-tache-01-silhouette-personnage.html',1,'lot-17']]],
  ['silhouettes_20et_20des_20blocs_20réduits_74',['TACHE-03 — Ombres des silhouettes et des blocs réduits',['../lot-55-tache-03-ombres-silhouettes.html',1,'lot-55']]],
  ['simples_20dans_20le_20cpp_75',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md230',1,'']]],
  ['simulation_76',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md50',1,'']]],
  ['simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_77',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md24',1,'']]],
  ['simulation_20↔_20rendu_78',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md205',1,'']]],
  ['simulation_20et_20les_20entrées_79',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md49',1,'']]],
  ['sinks_20_3a_20où_20finissent_20les_20messages_80',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md121',1,'']]],
  ['sinks_20différents_20en_20développement_20et_20en_20release_81',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md127',1,'']]],
  ['sinks_20enfichables_82',['TACHE-02 — Sinks enfichables',['../lot-02-tache-02-sinks.html',1,'lot-02']]],
  ['skin_20des_20tuiles_20_3a_20jeux_20de_20skins_20et_20raccords_20automatiques_83',['LOT-42 — Skin des tuiles : jeux de skins et raccords automatiques',['../lot-42.html',1,'lots']]],
  ['skin_20et_20animations_20depuis_20fichier_84',['LOT-48 — Personnage : skin et animations depuis fichier',['../lot-48.html',1,'lots']]],
  ['skins_85',['TACHE-04 — Panneau Qt « Textures » (section Skins)',['../lot-42-tache-04-panneau-textures.html',1,'lot-42']]],
  ['skins_86',['skins',['../lot-42-tache-01-skins-json.html',1,'TACHE-01 — `skins.json` : format versionné et jeux de skins'],['../lot-44-tache-03-section-fond.html',1,'TACHE-03 — Section « Fond » et sélecteur de jeu de skins']]],
  ['skins_20de_20tuiles_20animés_87',['TACHE-05 — Skins de tuiles animés',['../lot-46-tache-05-tuiles-animees.html',1,'lot-46']]],
  ['skins_20et_20raccords_20automatiques_88',['LOT-42 — Skin des tuiles : jeux de skins et raccords automatiques',['../lot-42.html',1,'lots']]],
  ['skins_20json_20_3a_20format_20versionné_20et_20jeux_20de_20skins_89',['TACHE-01 — `skins.json` : format versionné et jeux de skins',['../lot-42-tache-01-skins-json.html',1,'lot-42']]],
  ['slide_90',['slide',['../guide-physique.html#autotoc_md168',1,'6. Wall jump et wall slide'],['../lot-10-tache-04-wall-jump.html',1,'TACHE-04 — Wall jump + wall slide']]],
  ['socle_20applicatif_91',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md276',1,'']]],
  ['socle_20applicatif_20viewport_20d3d11_20embarqué_92',['LOT-34 — Refonte IHM (Qt) : socle applicatif &amp;amp; viewport D3D11 embarqué',['../lot-34.html',1,'lots']]],
  ['socle_20applicatif_20viewport_20direct3d_2011_93',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['socle_20de_20lecture_94',['TACHE-01 — Provisionnement de Qt Multimedia et socle de lecture',['../lot-60-tache-01-socle-qt-multimedia.html',1,'lot-60']]],
  ['socle_20de_20style_20_3a_20style_20qt_20palette_20applicative_20et_20jetons_20de_20design_95',['TACHE-01 — Socle de style : style Qt, palette applicative et jetons de design',['../lot-56-tache-01-socle-style.html',1,'lot-56']]],
  ['socle_20et_20bruitages_96',['LOT-60 — Audio : socle et bruitages',['../lot-60.html',1,'lots']]],
  ['sol_97',['sol',['../lot-10-tache-03-double-saut.html',1,'TACHE-03 — Double saut (sauts aériens rechargés au sol)'],['../lot-10-tache-05-dash.html',1,'TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)']]],
  ['sol_20hauteur_20variable_98',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['solide_99',['solide',['../guide-physique.html#autotoc_md160',1,'Pourquoi une pente (ou un arrondi) n&apos;est jamais solide'],['../lot-55-tache-01-quad-ombre.html',1,'TACHE-01 — Quad d&apos;ombre par tuile solide']]],
  ['solide_20→_20case_20de_20planche_100',['TACHE-02 — Raccords automatiques : voisinage solide → case de planche',['../lot-42-tache-02-raccords-automatiques.html',1,'lot-42']]],
  ['solidité_20partielle_20n_20est_20pas_20la_20solution_101',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2453',1,'']]],
  ['solution_102',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2453',1,'']]],
  ['solution_20_3a_20tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_103',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md155',1,'']]],
  ['sombre_104',['Thème clair/sombre',['../guide-design-ihm.html#autotoc_md58',1,'']]],
  ['sombre_20de_20l_20éditeur_105',['TACHE-06 — Thème clair et sombre de l&apos;éditeur',['../lot-56-tache-06-theme-clair-sombre.html',1,'lot-56']]],
  ['sommets_20shaders_20et_20échantillonnage_20nearest_106',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md179',1,'']]],
  ['son_20repli_20procédural_107',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md182',1,'']]],
  ['sondage_20manette_108',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]],
  ['sons_20et_20repli_20silencieux_109',['TACHE-02 — Catalogue de sons et repli silencieux',['../lot-60-tache-02-catalogue-sons.html',1,'lot-60']]],
  ['sortie_20liaison_20de_20mécanismes_20redimensionnement_110',['TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'lot-14']]],
  ['soumises_111',['TACHE-04 — *QuadRecorder* : capture des primitives soumises',['../lot-40-tache-04-quad-recorder.html',1,'lot-40']]],
  ['source_112',['Chemins complets depuis Source/',['../spec-conventions.html#autotoc_md223',1,'']]],
  ['source_20cpp_20hors_20source_20test_113',['État du triage (LOT-58, passe complète sur 129 fichiers &lt;span class=&quot;tt&quot;&gt;Source/*.cpp&lt;/span&gt; hors &lt;span class=&quot;tt&quot;&gt;Source/Test&lt;/span&gt;)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2581',1,'']]],
  ['source_20deux_20portées_20étanches_114',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md53',1,'']]],
  ['source_20elements_20assets_20_3a_20convention_20et_20régénération_115',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md183',1,'']]],
  ['source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_116',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md102',1,'']]],
  ['source_20test_117',['État du triage (LOT-58, passe complète sur 129 fichiers &lt;span class=&quot;tt&quot;&gt;Source/*.cpp&lt;/span&gt; hors &lt;span class=&quot;tt&quot;&gt;Source/Test&lt;/span&gt;)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2581',1,'']]],
  ['source_20unique_118',['TACHE-03 — Police embarquée et typographie à source unique',['../lot-56-tache-03-typographie-police.html',1,'lot-56']]],
  ['souris_119',['TACHE-01 — Entrées clavier &amp;amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['spécification_20navigables_20conventions_20incluses_120',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['spécifications_121',['Spécifications',['../specifications.html',1,'index']]],
  ['spécifications_20et_20exigences_20orphelines_122',['TACHE-03 — Statuts des spécifications et exigences orphelines',['../lot-66-tache-03-statuts-referentiel.html',1,'lot-66']]],
  ['spécifications_20et_20vérification_123',['TACHE-04 — Documentation, spécifications et vérification',['../lot-33-tache-04-documentation-verification.html',1,'lot-33']]],
  ['sparse_20set_20core_3a_3acomponentpool_124',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md73',1,'']]],
  ['sparse_20set_20typé_125',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['spawn_200_204×0_208_20sprite_126',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['spec_20à_20documenter_20dans_20l_20index_127',['Convention d&apos;insertion d&apos;une nouvelle spec (à documenter dans l&apos;index)',['../lot-04-tache-04-pages-specification.html#autotoc_md469',1,'']]],
  ['spirale_20de_20la_20mort_20»_128',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md47',1,'']]],
  ['sprite_129',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['sprite_20à_20la_20fois_130',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md177',1,'']]],
  ['sprite_20données_20pures_131',['TACHE-01 — Composant Sprite (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['sprite_20du_20personnage_20statique_132',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['spritequad_20_3a_20un_20rectangle_20texturé_133',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md178',1,'']]],
  ['sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_134',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md176',1,'']]],
  ['sprites_20caméra_135',['LOT-05 — Rendu 2D : atlas, sprites &amp;amp; caméra',['../lot-05.html',1,'lots']]],
  ['sprites_20ecs_20→_20écran_136',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['spritesheet_20chargé_20depuis_20un_20fichier_137',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md181',1,'']]],
  ['spritesheet_20externe_20et_20ancrage_20image_20hitbox_138',['TACHE-01 — Spritesheet externe et ancrage image/hitbox',['../lot-48-tache-01-spritesheet-externe.html',1,'lot-48']]],
  ['spritesheet_20externe_20et_20découplage_20image_20hitbox_139',['&lt;span class=&quot;tt&quot;&gt;LOT-48&lt;/span&gt; : spritesheet externe et découplage image/hitbox',['../guide-rendu.html#autotoc_md185',1,'']]],
  ['squelette_20première_20page_140',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['stables_20ancres_20doxygen_20lint_20ci_141',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['standard_142',['1. Langage &amp;amp; standard',['../spec-conventions.html#autotoc_md219',1,'']]],
  ['statique_143',['statique',['../lot-17.html',1,'LOT-17 — Sprite du personnage (statique)'],['../lot-58.html',1,'LOT-58 — Vérification Release, sanitizer et analyse statique']]],
  ['statuts_20des_20spécifications_20et_20exigences_20orphelines_144',['TACHE-03 — Statuts des spécifications et exigences orphelines',['../lot-66-tache-03-statuts-referentiel.html',1,'lot-66']]],
  ['stb_5fimage_20résolution_20d_20assets_20testable_145',['TACHE-01 — Loader image → texture D3D11 (`QImage`/`stb_image`) + résolution d&apos;assets testable',['../lot-39-tache-01-loader-image-assets.html',1,'lot-39']]],
  ['stockage_20_3a_20sparse_20set_20core_3a_3acomponentpool_146',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md73',1,'']]],
  ['stockage_20de_20composants_20sparse_20set_20typé_147',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['stricte_20est_20dangereuse_148',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md135',1,'']]],
  ['structurée_149',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['structurées_150',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['style_20_3a_20style_20qt_20palette_20applicative_20et_20jetons_20de_20design_151',['TACHE-01 — Socle de style : style Qt, palette applicative et jetons de design',['../lot-56-tache-01-socle-style.html',1,'lot-56']]],
  ['style_20qt_20palette_20applicative_20et_20jetons_20de_20design_152',['TACHE-01 — Socle de style : style Qt, palette applicative et jetons de design',['../lot-56-tache-01-socle-style.html',1,'lot-56']]],
  ['succès_20échec_153',['succès échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['suivant_20l_20outil_20actif_154',['TACHE-02 — Regroupement des panneaux, suivant l&apos;outil actif',['../lot-57-tache-02-panneaux-groupes.html',1,'lot-57']]],
  ['suivent_20l_20outil_155',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['suivi_156',['suivi',['../lot-26-tache-01-modele-physique-plafond.html',1,'TACHE-01 — Modèle de tuile et physique de suivi'],['../lot-64-tache-02-camera-suivi.html',1,'TACHE-02 — Caméra de suivi']]],
  ['suivi_20de_20pente_157',['TACHE-02 — Collision et suivi de pente',['../lot-22-tache-02-collision-suivi-pente.html',1,'lot-22']]],
  ['suivi_20de_20pente_20et_20d_20arrondi_20ex_20gp_20003_20ex_20gp_20004_158',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md159',1,'']]],
  ['suppression_20_3a_20swap_20and_20pop_159',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md74',1,'']]],
  ['suppression_20documentation_20vérification_160',['TACHE-03 — Panneau « Liens » (liste, surbrillance, suppression) ; documentation &amp;amp; vérification',['../lot-37-tache-03-panneau-liens-doc.html',1,'lot-37']]],
  ['suppression_20et_20détection_20des_20références_161',['TACHE-02 — Import, renommage, duplication, suppression et détection des références',['../lot-43-tache-02-gestion-fichiers.html',1,'lot-43']]],
  ['supprimer_20couche_20testable_162',['TACHE-02 — Opérations fichiers (créer/renommer/dupliquer/supprimer) + couche testable',['../lot-36-tache-02-operations-fichiers.html',1,'lot-36']]],
  ['sur_20129_20fichiers_20source_20cpp_20hors_20source_20test_163',['État du triage (LOT-58, passe complète sur 129 fichiers &lt;span class=&quot;tt&quot;&gt;Source/*.cpp&lt;/span&gt; hors &lt;span class=&quot;tt&quot;&gt;Source/Test&lt;/span&gt;)',['../lot-58-tache-03-clang-tidy.html#autotoc_md2581',1,'']]],
  ['sur_20atlas_20fichier_20interface_20conservée_20repli_20procédural_164',['TACHE-02 — `TextureAtlas` sur atlas fichier (interface conservée, repli procédural)',['../lot-39-tache-02-texture-atlas-fichier.html',1,'lot-39']]],
  ['sur_20clip_20manquant_165',['TACHE-02 — Transitions jouées une fois et repli sur clip manquant',['../lot-47-tache-02-transitions.html',1,'lot-47']]],
  ['sur_20les_20trois_20environnements_166',['TACHE-01 — Qt épinglé sur les trois environnements',['../lot-66-tache-01-qt-epingle.html',1,'lot-66']]],
  ['sur_20leveldraft_167',['TACHE-01 — Mutateurs de décors sur `LevelDraft`',['../lot-50-tache-01-mutateurs-decor.html',1,'lot-50']]],
  ['sur_20tampon_20de_20pixels_20et_20historique_20nommé_168',['TACHE-02 — Opérations sur tampon de pixels et historique nommé',['../lot-54-tache-02-operations-historique.html',1,'lot-54']]],
  ['sur_20un_20tampon_20de_20pixels_169',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['surbrillance_20suppression_20documentation_20vérification_170',['TACHE-03 — Panneau « Liens » (liste, surbrillance, suppression) ; documentation &amp;amp; vérification',['../lot-37-tache-03-panneau-liens-doc.html',1,'lot-37']]],
  ['surface_20de_20dessin_20_3a_20le_20viewport_20qt_20hmi_3a_3agameviewport_171',['La surface de dessin : le viewport Qt (&lt;span class=&quot;tt&quot;&gt;hmi::GameViewport&lt;/span&gt;)',['../guide-rendu.html#autotoc_md173',1,'']]],
  ['surface_20invariante_172',['TACHE-03 — Canevas : rendu net et surface invariante',['../lot-54-tache-03-canevas.html',1,'lot-54']]],
  ['surfaces_173',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md56',1,'']]],
  ['suspension_20du_20pas_20fixe_174',['TACHE-02 — Écran de pause et suspension du pas fixe',['../lot-59-tache-02-ecran-pause.html',1,'lot-59']]],
  ['swap_20and_20pop_175',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md74',1,'']]],
  ['swap_20chain_20back_20buffer_176',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md171',1,'']]],
  ['swept_20aabb_177',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md153',1,'']]],
  ['sync_20langue_20remappage_20jeu_20éditeur_20manette_178',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['synthèse_179',['TACHE-03 — Tableaux manquants et tableaux de synthèse',['../lot-65-tache-03-tableaux-manquants-syntheses.html',1,'lot-65']]],
  ['système_180',['système',['../lot-25-tache-03-integration-sequence-tests.html',1,'TACHE-03 — Intégration séquence et tests système'],['../lot-10-tache-06-niveau-parkour.html',1,'TACHE-06 — Niveau de démo « parkour » + preuve système']]],
  ['système_203_181',['Tests système (3)',['../cahiertest.html#autotoc_md29',1,'']]],
  ['système_20d_20animation_182',['TACHE-01 — Composant et système d&apos;animation',['../lot-18-tache-01-composant-systeme-animation.html',1,'lot-18']]],
  ['système_20de_20décors_183',['1. Système de décors',['../spec-decors.html#autotoc_md239',1,'']]],
  ['système_20de_20design_184',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md52',1,'']]],
  ['système_20de_20design_20de_20l_20ihm_20qt_185',['LOT-56 — Système de design de l&apos;IHM Qt',['../lot-56.html',1,'lots']]],
  ['système_20de_20design_20et_20architecture_20de_20l_20information_186',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['système_20de_20design_20et_20habillage_20lot_2056_187',['6. Système de design et habillage (LOT-56)',['../spec-interface-ihm.html#autotoc_md281',1,'']]],
  ['système_20de_20mouvement_20démo_188',['TACHE-06 — Composant Transform + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['système_20de_20rendu_20des_20sprites_20ecs_20→_20écran_189',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['système_20guide_20non_20codeur_20git_190',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['systèmes_191',['systèmes',['../spec-architecture.html#autotoc_md209',1,'8. Communication inter-systèmes'],['../guide-ecs.html',1,'ECS : entités, composants, systèmes']]],
  ['systèmes_20de_20coordonnées_20à_20ne_20pas_20confondre_192',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md138',1,'']]],
  ['systèmes_20et_20l_20ordre_20d_20exécution_193',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md77',1,'']]],
  ['systèmes_20world_20orchestration_20au_20pas_20fixe_194',['TACHE-05 — Systèmes &amp;amp; World (orchestration au pas fixe)',['../lot-03-tache-05-systemes-world.html',1,'lot-03']]]
];
