var searchData=
[
  ['jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_0',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md123',1,'']]],
  ['jamais_20de_20cadrage_1',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['jamais_20l_20inverse_2',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['jamais_20laisser_20de_20fichier_20tronqué_3',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['jamais_20solide_4',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md193',1,'']]],
  ['jetons_20_3a_20une_20seule_20source_20deux_20portées_20étanches_5',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['jetons_20de_20design_6',['TACHE-01 — Socle de style : style Qt, palette applicative et jetons de design',['../lot-56-tache-01-socle-style.html',1,'lot-56']]],
  ['jetons_20purs_20à_20une_20application_20habillée_7',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['jeu_8',['jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../spec-gameplay.html#autotoc_md321',1,'5. États de jeu'],['../manuel-jouer.html#autotoc_md3240',1,'Contrôles en jeu'],['../guide-ecrans.html#autotoc_md82',1,'Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu'],['../lot-30.html',1,'LOT-30 — Remappage manette (jeu)'],['../guide-boucle.html#autotoc_md54',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?'],['../manuel-telecharger.html',1,'Télécharger et lancer le jeu'],['../lot-30-tache-02-integration-jeu.html',1,'TACHE-02 — Intégration jeu'],['../lot-16-tache-03-camera-niveau-entier.html',1,'TACHE-03 — Caméra : englober tout le niveau (éditeur et jeu)']]],
  ['jeu_20éditeur_9',['jeu éditeur',['../lot-29.html',1,'LOT-29 — Remappage des touches (jeu + éditeur)'],['../lot-29-tache-02-integration-jeu-editeur.html',1,'TACHE-02 — Intégration jeu/éditeur']]],
  ['jeu_20éditeur_20manette_10',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['jeu_20complète_20_3a_20pause_20fin_20de_20niveau_20progression_11',['LOT-59 — Boucle de jeu complète : pause, fin de niveau, progression',['../lot-59.html',1,'lots']]],
  ['jeu_20contrôleurs_20résolution_20de_20fin_20de_20niveau_12',['TACHE-02 — Intégration jeu (contrôleurs, résolution de fin de niveau)',['../lot-31-tache-02-integration-jeu.html',1,'lot-31']]],
  ['jeu_20coupure_20nette_13',['TACHE-02 — Caméra par salle en jeu (coupure nette)',['../lot-32-tache-02-camera-salle-jeu.html',1,'lot-32']]],
  ['jeu_20décidée_14',['Mécanique de jeu (décidée)',['../spec-vision.html#autotoc_md346',1,'']]],
  ['jeu_20démo_20éditeur_20placeholder_15',['TACHE-06 — Écrans cibles (jeu démo + éditeur placeholder)',['../lot-06-tache-06-ecrans-cibles.html',1,'lot-06']]],
  ['jeu_20de_20skins_16',['TACHE-03 — Section « Fond » et sélecteur de jeu de skins',['../lot-44-tache-03-section-fond.html',1,'lot-44']]],
  ['jeu_20de_20visibilités_20par_20calque_17',['TACHE-01 — Jeu de visibilités par calque',['../lot-51-tache-01-visibilite-calques.html',1,'lot-51']]],
  ['jeu_20direct3d_2011_18',['LOT-01 — Fenêtre &amp;amp; boucle de jeu (Direct3D 11)',['../lot-01.html',1,'lots']]],
  ['jeu_20et_20pas_20de_20temps_20fixe_19',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['jeu_20f9_20',['Compteur de diagnostic en jeu (&lt;span class=&quot;tt&quot;&gt;F9&lt;/span&gt;)',['../guide-rendu.html#autotoc_md246',1,'']]],
  ['jeu_20hmi_21',['TACHE-02 — Intégration éditeur et jeu (HMI)',['../lot-21-tache-02-integration-editeur-jeu.html',1,'lot-21']]],
  ['jeu_20lot_2068_22',['8. Identité visuelle des écrans du jeu (LOT-68)',['../spec-interface-ihm.html#autotoc_md330',1,'']]],
  ['jeu_20mapping_20logique_23',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md264',1,'']]],
  ['jeu_20vidéo_24',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['jeux_20de_20skins_25',['TACHE-01 — `skins.json` : format versionné et jeux de skins',['../lot-42-tache-01-skins-json.html',1,'lot-42']]],
  ['jeux_20de_20skins_20et_20raccords_20automatiques_26',['LOT-42 — Skin des tuiles : jeux de skins et raccords automatiques',['../lot-42.html',1,'lots']]],
  ['job_20build_20test_20coverage_27',['4. Provisionnement CI (&lt;span class=&quot;tt&quot;&gt;.github/workflows/ci.yml&lt;/span&gt;, job &lt;span class=&quot;tt&quot;&gt;build-test-coverage&lt;/span&gt;)',['../lot-34-tache-01-provisionnement-qt-build.html#autotoc_md1706',1,'']]],
  ['job_20ci_20addresssanitizer_28',['TACHE-02 — Job CI AddressSanitizer',['../lot-58-tache-02-job-asan.html',1,'lot-58']]],
  ['job_20ci_20de_20vérification_20en_20configuration_20release_29',['TACHE-01 — Job CI de vérification en configuration Release',['../lot-58-tache-01-job-release.html',1,'lot-58']]],
  ['jouées_20une_20fois_20et_20repli_20sur_20clip_20manquant_30',['TACHE-02 — Transitions jouées une fois et repli sur clip manquant',['../lot-47-tache-02-transitions.html',1,'lot-47']]],
  ['jouable_20dans_20gamescreen_20cadrage_20fixe_20succès_20échec_31',['TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)',['../lot-08-tache-06-integration-jouable.html',1,'lot-08']]],
  ['jouable_20dans_20le_20viewport_20documentation_20vérification_32',['TACHE-04 — Niveau chargé/affiché/jouable dans le viewport ; documentation &amp;amp; vérification',['../lot-34-tache-04-niveau-jouable-doc.html',1,'lot-34']]],
  ['jouer_33',['Jouer',['../manuel-jouer.html',1,'manuel']]],
  ['jouer_20sans_20quitter_20l_20éditeur_34',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['jouer_20un_20niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_35',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['joueur_36',['joueur',['../manuel-partager-niveau.html#autotoc_md3249',1,'Choisir comment la caméra suit le joueur'],['../lot-59-tache-06-selection-niveau.html',1,'TACHE-06 — Sélection de niveau côté joueur']]],
  ['journalisation_37',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md284',1,'']]],
  ['journalisation_20diagnostics_38',['LOT-02 — Journalisation &amp;amp; diagnostics',['../lot-02.html',1,'lots']]],
  ['journalisation_20et_20assertions_39',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['journalisation_20fichier_40',['TACHE-01 — Puits de journalisation fichier',['../lot-61-tache-01-file-log-sink.html',1,'lot-61']]],
  ['journalisation_20par_20catégorie_41',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['journaliser_20dans_20un_20jeu_20vidéo_42',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['json_43',['JSON',['../guide-niveaux.html#autotoc_md169',1,'Chargement JSON'],['../lot-29-tache-01-modele-bindings.html',1,'TACHE-01 — Modèle de bindings et persistance JSON'],['../lot-07-tache-03-chargement-json.html',1,'TACHE-03 — Chargement du niveau (JSON)']]],
  ['json_44',['Niveau final combiné (&lt;span class=&quot;tt&quot;&gt;demo-final.json&lt;/span&gt;)',['../lot-25-tache-01-inventaire-conception.html#autotoc_md1403',1,'']]],
  ['json_20épinglé_45',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['json_20_3a_20format_20versionné_20et_20jeux_20de_20skins_46',['TACHE-01 — `skins.json` : format versionné et jeux de skins',['../lot-42-tache-01-skins-json.html',1,'lot-42']]],
  ['json_20_3a_20lecture_20et_20mise_20en_20cache_47',['TACHE-03 — Format `nom-asset.anim.json` : lecture et mise en cache',['../lot-46-tache-03-format-anim-json.html',1,'lot-46']]],
  ['json_20liste_20de_20tuiles_20objets_48',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md333',1,'']]],
  ['json_20modèle_20d_20édition_20mutable_49',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['json_20nettoyage_20et_20historique_50',['TACHE-01 — `TileTextureOverride` : modèle, JSON, nettoyage et historique',['../lot-45-tache-01-modele-override.html',1,'lot-45']]],
  ['json_20nlohmann_20json_20épinglé_51',['TACHE-01 — Dépendance JSON (nlohmann/json épinglé)',['../lot-07-tache-01-dependance-json.html',1,'lot-07']]],
  ['jump_20buffering_52',['TACHE-04 — Coyote time + jump buffering',['../lot-09-tache-04-coyote-buffering.html',1,'lot-09']]],
  ['jump_20dash_53',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['jump_20et_20wall_20slide_54',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md201',1,'']]],
  ['jump_20wall_20slide_55',['TACHE-04 — Wall jump + wall slide',['../lot-10-tache-04-wall-jump.html',1,'lot-10']]]
];
