var searchData=
[
  ['règles_20de_20fin_20de_20niveau_20succès_20échec_0',['TACHE-04 — Règles de fin de niveau (succès / échec)',['../lot-08-tache-04-regles-fin-niveau.html',1,'lot-08']]],
  ['rééquilibrage_20des_20niveaux_20preuves_20à_20la_20vraie_20taille_1',['TACHE-04 — Rééquilibrage des niveaux + preuves à la vraie taille',['../lot-11-tache-04-reequilibrage.html',1,'lot-11']]],
  ['réglages_20de_20feel_20taille_20placement_20du_20personnage_2',['TACHE-01 — Données : réglages de *feel* + taille/placement du personnage',['../lot-11-tache-01-donnees.html',1,'lot-11']]],
  ['réorganisation_20de_20l_20arborescence_20documentaire_3',['réorganisation de l arborescence documentaire',['../lot-04.html',1,'LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire'],['../lot-04-tache-01-reorganisation-arbo.html',1,'TACHE-01 — Réorganisation de l&apos;arborescence documentaire']]],
  ['r_4',['TACHE-02 — Boîte de dialogue de redimensionnement (Ctrl+R)',['../lot-16-tache-02-boite-dialogue-redimensionnement.html',1,'lot-16']]],
  ['raii_5',['TACHE-02 — Initialisation Direct3D 11 (RAII)',['../lot-01-tache-02-init-direct3d11.html',1,'lot-01']]],
  ['rechargés_20au_20sol_6',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['recharge_20au_20sol_7',['TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)',['../lot-10-tache-05-dash.html',1,'lot-10']]],
  ['rectangulaire_20sélection_20copier_20coller_8',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['redimensionnement_9',['redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement'],['../lot-01-tache-04-effacement-presentation.html',1,'TACHE-04 — Effacement écran, présentation &amp; redimensionnement']]],
  ['redimensionnement_20ctrl_20r_10',['TACHE-02 — Boîte de dialogue de redimensionnement (Ctrl+R)',['../lot-16-tache-02-boite-dialogue-redimensionnement.html',1,'lot-16']]],
  ['redimensionnement_20destructeur_20quitter_20sans_20enregistrer_11',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['refaire_12',['TACHE-04 — Historique annuler/refaire',['../lot-14-tache-04-undo-redo.html',1,'lot-14']]],
  ['remplissage_20rectangulaire_20sélection_20copier_20coller_13',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['rendu_14',['TACHE-02 — Images dans l&apos;atlas et intégration au rendu',['../lot-18-tache-02-frames-atlas-integration.html',1,'lot-18']]],
  ['rendu_202d_20_3a_20atlas_20sprites_20caméra_15',['LOT-05 — Rendu 2D : atlas, sprites &amp; caméra',['../lot-05.html',1,'lots']]],
  ['rendu_202d_20_3a_20de_20l_20ecs_20à_20l_20écran_16',['Rendu 2D : de l&apos;ECS à l&apos;écran',['../guide-rendu.html',1,'guide']]],
  ['rendu_20cible_20technique_17',['Rendu &amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['rendu_20de_20texte_20police_20bitmap_18',['TACHE-02 — Rendu de texte (police bitmap)',['../lot-06-tache-02-rendu-texte-bitmap.html',1,'lot-06']]],
  ['rendu_20des_20sprites_20ecs_20→_20écran_19',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['rendu_20du_20niveau_20intégration_20«_20charger_20niveau_20»_20',['TACHE-06 — Rendu du niveau + intégration « Charger niveau »',['../lot-07-tache-06-rendu-integration.html',1,'lot-07']]],
  ['renommage_20avertissement_20d_20écrasement_21',['TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'lot-15']]],
  ['repos_20course_20saut_22',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['requêtes_20vues_20multi_20composants_23',['TACHE-04 — Requêtes / vues multi-composants',['../lot-03-tache-04-vues-requetes.html',1,'lot-03']]],
  ['requis_20preuve_24',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['ressenti_20avancé_20_3a_20personnage_20humanoïde_20gravité_20asymétrique_20finitions_25',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['retour_20titre_26',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['robustesse_20et_20confort_20d_20édition_27',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]]
];
