var searchData=
[
  ['aériennes_20avancées_20_3a_20double_20saut_20wall_20jump_20dash_0',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['aériens_20rechargés_20au_20sol_1',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['aabb_20contre_20la_20grille_20géométrie_20pure_2',['TACHE-02 — Balayage AABB contre la grille (géométrie pure)',['../lot-08-tache-02-balayage-aabb.html',1,'lot-08']]],
  ['accordéon_20à_20trois_20niveaux_3',['TACHE-01 — Palette en accordéon à trois niveaux',['../lot-27-tache-01-palette-accordeon.html',1,'lot-27']]],
  ['accueil_20du_20projet_20mainpage_4',['TACHE-03 — Page d&apos;accueil du projet (mainpage)',['../lot-04-tache-03-page-accueil.html',1,'lot-04']]],
  ['actions_20logiques_5',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['actions_20logiques_20d_20entrée_20mapping_20touches_20→_20intention_6',['TACHE-05 — Actions logiques d&apos;entrée (mapping touches → intention)',['../lot-08-tache-05-actions-logiques.html',1,'lot-08']]],
  ['aide_20libellés_20liaisons_20lisibles_7',['TACHE-06 — Découvrabilité : barre d&apos;outils, aide, libellés, liaisons lisibles',['../lot-15-tache-06-decouvrabilite.html',1,'lot-15']]],
  ['ancres_20doxygen_20lint_20ci_8',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['animation_9',['TACHE-01 — Composant et système d&apos;animation',['../lot-18-tache-01-composant-systeme-animation.html',1,'lot-18']]],
  ['animation_20du_20personnage_20repos_20course_20saut_10',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['annuler_20refaire_11',['TACHE-04 — Historique annuler/refaire',['../lot-14-tache-04-undo-redo.html',1,'lot-14']]],
  ['apex_20hang_20fast_20fall_12',['TACHE-02 — Gravité asymétrique + apex hang + fast-fall',['../lot-11-tache-02-gravite-asymetrique.html',1,'lot-11']]],
  ['application_20écrans_13',['TACHE-04 — États d&apos;application (écrans)',['../lot-06-tache-04-etats-application.html',1,'lot-06']]],
  ['arborescence_20documentaire_14',['arborescence documentaire',['../lot-04.html',1,'LOT-04 — Documentation Doxygen &amp; réorganisation de l&apos;arborescence documentaire'],['../lot-04-tache-01-reorganisation-arbo.html',1,'TACHE-01 — Réorganisation de l&apos;arborescence documentaire']]],
  ['arch_20031_15',['TACHE-03 — Interpolation de rendu (EX-ARCH-031)',['../lot-33-tache-03-interpolation-rendu.html',1,'lot-33']]],
  ['architecture_20décisions_20dimensionnantes_16',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['arrondie_17',['LOT-23 — Collision arrondie',['../lot-23.html',1,'lots']]],
  ['arrondis_20concaves_18',['LOT-28 — Arrondis concaves',['../lot-28.html',1,'lots']]],
  ['arrondis_20de_20plafond_19',['LOT-26 — Pentes et arrondis de plafond',['../lot-26.html',1,'lots']]],
  ['art_20',['Décors &amp; pipeline pixel art',['../spec-decors.html',1,'specifications']]],
  ['assertions_21',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['assertions_20projectgaming_5fassert_22',['TACHE-04 — Assertions PROJECTGAMING_ASSERT',['../lot-02-tache-04-assertions.html',1,'lot-02']]],
  ['asymétrique_20apex_20hang_20fast_20fall_23',['TACHE-02 — Gravité asymétrique + apex hang + fast-fall',['../lot-11-tache-02-gravite-asymetrique.html',1,'lot-11']]],
  ['asymétrique_20finitions_24',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['atlas_25',['TACHE-01 — Silhouette du personnage dans l&apos;atlas',['../lot-17-tache-01-silhouette-personnage.html',1,'lot-17']]],
  ['atlas_20de_20textures_20procédural_26',['TACHE-03 — Atlas de textures procédural',['../lot-05-tache-03-atlas-procedural.html',1,'lot-05']]],
  ['atlas_20et_20intégration_20au_20rendu_27',['TACHE-02 — Images dans l&apos;atlas et intégration au rendu',['../lot-18-tache-02-frames-atlas-integration.html',1,'lot-18']]],
  ['atlas_20sprites_20caméra_28',['LOT-05 — Rendu 2D : atlas, sprites &amp; caméra',['../lot-05.html',1,'lots']]],
  ['au_20pas_20fixe_29',['TACHE-05 — Systèmes &amp; World (orchestration au pas fixe)',['../lot-03-tache-05-systemes-world.html',1,'lot-03']]],
  ['au_20rendu_30',['TACHE-02 — Images dans l&apos;atlas et intégration au rendu',['../lot-18-tache-02-frames-atlas-integration.html',1,'lot-18']]],
  ['au_20sol_31',['au sol',['../lot-10-tache-03-double-saut.html',1,'TACHE-03 — Double saut (sauts aériens rechargés au sol)'],['../lot-10-tache-05-dash.html',1,'TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)']]],
  ['au_20sol_20hauteur_20variable_32',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['auto_20avance_20retour_20titre_33',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['avancé_20_3a_20personnage_20humanoïde_20gravité_20asymétrique_20finitions_34',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['avancées_20_3a_20double_20saut_20wall_20jump_20dash_35',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['avancés_36',['LOT-31 — Blocs de danger avancés',['../lot-31.html',1,'lots']]],
  ['avance_20retour_20titre_37',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['avertissement_20d_20écrasement_38',['TACHE-03 — Nommage, renommage, avertissement d&apos;écrasement',['../lot-15-tache-03-nommage-renommage.html',1,'lot-15']]]
];
