var searchData=
[
  ['ui_0',['LOT-38 — Refonte IHM (Qt) : menus, options, remappage &amp;amp; retrait du legacy UI',['../lot-38.html',1,'lots']]],
  ['ui_20écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_1',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['ui_20de_20remappage_20et_20câblage_2',['TACHE-03 — UI de remappage et câblage',['../lot-29-tache-03-ui-remappage.html',1,'lot-29']]],
  ['ui_20de_20remappage_20manette_20et_20câblage_3',['TACHE-03 — UI de remappage manette et câblage',['../lot-30-tache-03-ui-remappage-manette.html',1,'lot-30']]],
  ['ultérieurs_4',['ultérieurs',['../lot-01.html#autotoc_md355',1,'Exclus (lots ultérieurs)'],['../lot-03.html#autotoc_md437',1,'Exclus (lots ultérieurs)'],['../lot-04.html#autotoc_md488',1,'Exclus (lots ultérieurs)'],['../lot-05.html#autotoc_md557',1,'Exclus (lots ultérieurs)'],['../lot-06.html#autotoc_md609',1,'Exclus (lots ultérieurs)'],['../lot-07.html#autotoc_md675',1,'Exclus (lots ultérieurs)'],['../lot-08.html#autotoc_md727',1,'Exclus (lots ultérieurs)'],['../lot-09.html#autotoc_md779',1,'Exclus (lots ultérieurs)'],['../lot-10.html#autotoc_md831',1,'Exclus (lots ultérieurs)'],['../lot-11.html#autotoc_md883',1,'Exclus (lots ultérieurs)'],['../lot-12.html#autotoc_md921',1,'Exclus (lots ultérieurs)'],['../lot-14.html#autotoc_md968',1,'Exclus (lots ultérieurs)']]],
  ['ultérieurs_20ou_20non_20retenus_5',['Exclus (lots ultérieurs ou non retenus)',['../lot-15.html#autotoc_md1020',1,'']]],
  ['un_20élément_20mobile_6',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md107',1,'']]],
  ['un_20état_20un_20contrôle_7',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md74',1,'']]],
  ['un_20aperçu_8',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md120',1,'']]],
  ['un_20arrondi_20n_20est_20jamais_20solide_9',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md193',1,'']]],
  ['un_20asset_20à_20une_20taille_20forcément_20conforme_10',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md43',1,'']]],
  ['un_20calque_20pour_20l_20audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_11',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md225',1,'']]],
  ['un_20changement_20de_20cible_12',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['un_20compromis_20de_20mémoire_20jamais_20de_20cadrage_13',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['un_20contenu_20plus_20grand_20que_20la_20fenêtre_20_3a_20fitzoom_20et_20hmi_3a_3aroomgrid_14',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md208',1,'']]],
  ['un_20contrôle_15',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md74',1,'']]],
  ['un_20fichier_16',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['un_20jeu_20vidéo_17',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['un_20même_20niveau_20mode_20«_20par_20salle_20»_18',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md3250',1,'']]],
  ['un_20niveau_19',['un niveau',['../manuel-partager-niveau.html#autotoc_md3248',1,'3. Créer un niveau'],['../manuel-jouer.html#autotoc_md3241',1,'Objectif d&apos;un niveau']]],
  ['un_20niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_20',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['un_20niveau_20plus_20grand_20que_20la_20fenêtre_21',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md114',1,'']]],
  ['un_20niveau_20qu_20on_20peut_20défaire_22',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : un niveau qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md101',1,'']]],
  ['un_20niveau_20sans_20ligne_20de_20commande_23',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['un_20niveau_20sans_20re_20coder_20le_20moteur_24',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['un_20outil_20différent_25',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a24ec0bff1ac1e68bdf8ac50376a41076&quot; title=&quot;PROJECTGAMING_ASSERT&quot;&gt;PROJECTGAMING_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md155',1,'']]],
  ['un_20pas_26',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md83',1,'']]],
  ['un_20pas_20résumé_27',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md202',1,'']]],
  ['un_20piège_28',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md104',1,'']]],
  ['un_20pixel_29',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['un_20pixel_20en_20case_30',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md105',1,'']]],
  ['un_20plan_20_3a_20le_20mode_20création_31',['Peindre un plan : le mode création',['../guide-rendu.html#autotoc_md232',1,'']]],
  ['un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_32',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['un_20point_20ou_20une_20direction_20dans_20le_20monde_33',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md157',1,'']]],
  ['un_20prédicat_20de_20solidité_20partielle_20n_20est_20pas_20la_20solution_34',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2502',1,'']]],
  ['un_20rectangle_20texturé_35',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['un_20repère_20géométrique_20pas_20un_20aperçu_36',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md120',1,'']]],
  ['un_20repli_20qui_20n_20invente_20rien_37',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['un_20segment_20orienté_20liens_20de_20mécanismes_20lot_2037_38',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['un_20sprite_20à_20la_20fois_39',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['un_20spritesheet_20chargé_20depuis_20un_20fichier_40',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['un_20système_20de_20design_41',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['un_20tampon_20de_20pixels_42',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['undo_20redo_20copier_20coller_43',['TACHE-03 — Barre d&apos;outils + peinture viewport → `LevelDraft` (undo/redo, copier/coller)',['../lot-35-tache-03-outils-peinture-viewport.html',1,'lot-35']]],
  ['une_20application_20habillée_44',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['une_20barre_20d_20état_20structurée_45',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md72',1,'']]],
  ['une_20boucle_20de_20jeu_46',['Qu&apos;est-ce qu&apos;une boucle de jeu ?',['../guide-boucle.html#autotoc_md54',1,'']]],
  ['une_20chaîne_20en_20quads_47',['TACHE-02 — *TextRenderer* : composition d&apos;une chaîne en quads',['../lot-52-tache-02-text-renderer.html',1,'lot-52']]],
  ['une_20couche_20d_20accès_20au_20gpu_20pas_20un_20changement_20de_20cible_48',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['une_20définition_20trois_20surfaces_49',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md68',1,'']]],
  ['une_20direction_20dans_20le_20monde_50',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md157',1,'']]],
  ['une_20donnée_51',['TACHE-01 — Le clip devient une donnée',['../lot-46-tache-01-modele-clip.html',1,'lot-46']]],
  ['une_20extrémité_52',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md196',1,'']]],
  ['une_20fenêtre_20qt_53',['Le viewport : Direct3D 11 dans une fenêtre Qt',['../guide-ihm-qt.html#autotoc_md136',1,'']]],
  ['une_20feuille_20de_20style_20ne_20sait_20pas_20faire_54',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md76',1,'']]],
  ['une_20fois_20de_20plus_55',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md47',1,'']]],
  ['une_20fois_20et_20repli_20sur_20clip_20manquant_56',['TACHE-02 — Transitions jouées une fois et repli sur clip manquant',['../lot-47-tache-02-transitions.html',1,'lot-47']]],
  ['une_20frame_57',['Le cycle d&apos;une frame',['../guide-entrees.html#autotoc_md126',1,'']]],
  ['une_20ligne_20_3a_20core_3a_3aformatlogline_20core_3a_3aformatlogline_58',['Le format d&apos;une ligne : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aafa85d91ee91c84b123fff01f147615e&quot; title=&quot;core::formatLogLine&quot;&gt;core::formatLogLine&lt;/a&gt;',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['une_20même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_59',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['une_20nouvelle_20spec_20à_20documenter_20dans_20l_20index_60',['Convention d&apos;insertion d&apos;une nouvelle spec (à documenter dans l&apos;index)',['../lot-04-tache-04-pages-specification.html#autotoc_md518',1,'']]],
  ['une_20pente_20ou_20un_20arrondi_20n_20est_20jamais_20solide_61',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md193',1,'']]],
  ['une_20police_20embarquée_20un_20repli_20qui_20n_20invente_20rien_62',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['une_20progression_20générale_20lot_2046_63',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md221',1,'']]],
  ['une_20règle_20de_20performance_20à_20respecter_64',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md151',1,'']]],
  ['une_20seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_65',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md129',1,'']]],
  ['une_20seule_20cible_20_3a_20l_20application_20qt_66',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md135',1,'']]],
  ['une_20seule_20paire_20annuler_20refaire_20deux_20cibles_67',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md45',1,'']]],
  ['une_20seule_20source_20deux_20portées_20étanches_68',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['une_20taille_20forcément_20conforme_69',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md43',1,'']]],
  ['une_20touche_20dans_20le_20gameplay_70',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md123',1,'']]],
  ['une_20version_20publiée_71',['LOT-61 — Diagnostics d&apos;une version publiée',['../lot-61.html',1,'lots']]],
  ['unification_72',['5. Menus, options, unification',['../spec-interface-ihm.html#autotoc_md327',1,'']]],
  ['unification_20des_20menus_20lot_2038_73',['Liens de mécanismes (LOT-37) et unification des menus (LOT-38)',['../guide-ihm-qt.html#autotoc_md142',1,'']]],
  ['unique_74',['unique',['../guide-design-ihm.html#autotoc_md71',1,'Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique'],['../lot-56-tache-03-typographie-police.html',1,'TACHE-03 — Police embarquée et typographie à source unique']]],
  ['unités_20—_20trois_20espaces_20distincts_75',['3. Coordonnées &amp;amp; unités — trois espaces distincts',['../spec-architecture.html#autotoc_md253',1,'']]],
  ['unités_20et_20de_20repère_76',['Conventions d&apos;unités et de repère',['../guide-maths.html#autotoc_md161',1,'']]],
  ['unités_20monde_20et_20pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_77',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_78',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md243',1,'']]],
  ['unitaire_79',['Vérification (visuelle, pas de test unitaire)',['../lot-08-tache-06-integration-jouable.html#autotoc_md772',1,'']]],
  ['unitaire_20—_20brique_20gpu_80',['Vérification (visuelle, pas de test unitaire — brique GPU)',['../lot-11-tache-03-personnage-humanoide.html#autotoc_md907',1,'']]],
  ['unitaires_201059_81',['Tests unitaires (1059)',['../cahiertest.html#autotoc_md4',1,'']]],
  ['utilisateur_82',['utilisateur',['../lot-15-tache-01-entrees-molette-texte.html#autotoc_md1034',1,'Ajustement post-livraison (essai utilisateur)'],['../lot-15-tache-04-camera-pan-zoom.html#autotoc_md1054',1,'Ajustement post-livraison (essai utilisateur)'],['../lot-15-tache-06-decouvrabilite.html#autotoc_md1071',1,'Ajustement post-livraison (essai utilisateur)'],['../manuel.html',1,'Manuel utilisateur']]],
  ['utilisateur_20ihm_83',['Interface utilisateur (IHM)',['../spec-interface-ihm.html',1,'specifications']]],
  ['utilisateur_20squelette_20première_20page_84',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]]
];
