var searchData=
[
  ['sélecteur_20de_20jeu_20de_20skins_0',['TACHE-03 — Section « Fond » et sélecteur de jeu de skins',['../lot-44-tache-03-section-fond.html',1,'lot-44']]],
  ['sélecteur_20de_20langue_1',['TACHE-08 — Sélecteur de langue',['../lot-06-tache-08-selecteur-langue.html',1,'lot-06']]],
  ['sélection_2',['TACHE-02 — Palette de tuiles `QTreeView` (taxonomie `LOT-27`) reliée à la sélection',['../lot-35-tache-02-palette-arbre.html',1,'lot-35']]],
  ['sélection_20copier_20coller_3',['TACHE-05 — Outils de zone : remplissage rectangulaire, sélection, copier/coller',['../lot-15-tache-05-outils-rectangle-selection.html',1,'lot-15']]],
  ['sélection_20poignées_20et_20aimantation_4',['TACHE-03 — Rendu de la sélection, poignées et aimantation',['../lot-50-tache-03-selection-poignees.html',1,'lot-50']]],
  ['séparés_20du_20canevas_5',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md61',1,'']]],
  ['séquence_20auto_20avance_20retour_20titre_6',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['séquence_20de_20niveaux_20démo_7',['La séquence de niveaux démo',['../guide-ecrans.html#autotoc_md43',1,'']]],
  ['séquence_20dont_20saut_20requis_20preuve_8',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['séquence_20et_20tests_20système_9',['TACHE-03 — Intégration séquence et tests système',['../lot-25-tache-03-integration-sequence-tests.html',1,'lot-25']]],
  ['séquencement_10',['4. Périmètre &amp;amp; séquencement',['../spec-decors.html#autotoc_md213',1,'']]],
  ['sérialisation_11',['TACHE-01 — *coreDecor* : modèle, couches et sérialisation',['../lot-49-tache-01-modele-decor.html',1,'lot-49']]],
  ['sérialisation_20json_20modèle_20d_20édition_20mutable_12',['TACHE-01 — Sérialisation JSON + modèle d&apos;édition mutable',['../lot-14-tache-01-serialisation-modele-edition.html',1,'lot-14']]],
  ['s_20insère_20dans_20la_20boucle_13',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md44',1,'']]],
  ['sa_20propre_20catégorie_14',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md96',1,'']]],
  ['salle_15',['TACHE-03 — Parallaxe et arbitrage avec la caméra par salle',['../lot-49-tache-03-parallaxe.html',1,'lot-49']]],
  ['salle_20en_20jeu_20coupure_20nette_16',['TACHE-02 — Caméra par salle en jeu (coupure nette)',['../lot-32-tache-02-camera-salle-jeu.html',1,'lot-32']]],
  ['salle_20visible_17',['TACHE-05 — Culling par salle visible',['../lot-40-tache-05-culling-salle.html',1,'lot-40']]],
  ['salles_20dans_20l_20éditeur_18',['TACHE-03 — Repère visuel de salles dans l&apos;éditeur',['../lot-32-tache-03-repere-editeur.html',1,'lot-32']]],
  ['salles_20façon_20celeste_19',['LOT-32 — Niveaux à salles (façon Celeste)',['../lot-32.html',1,'lots']]],
  ['salles_20lot_2032_20',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md226',1,'']]],
  ['salles_20roomgrid_20logique_20pure_21',['TACHE-01 — Partition en salles (`RoomGrid`, logique pure)',['../lot-32-tache-01-partition-salles.html',1,'lot-32']]],
  ['sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_22',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md63',1,'']]],
  ['sans_20enregistrer_23',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['sans_20ligne_20de_20commande_24',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['sans_20pas_20de_20simulation_20et_20les_20entrées_25',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['sans_20quitter_20l_20éditeur_26',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md65',1,'']]],
  ['sans_20re_20coder_20le_20moteur_27',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md55',1,'']]],
  ['sans_20repli_28',['TACHE-02 — Affichage isolé sans repli',['../lot-51-tache-02-affichage-isole.html',1,'lot-51']]],
  ['saut_29',['LOT-18 — Animation du personnage (repos, course, saut)',['../lot-18.html',1,'lots']]],
  ['saut_20_3a_20playerinput_20player_20physicsconfig_30',['TACHE-01 — Données du saut : PlayerInput, Player, PhysicsConfig',['../lot-09-tache-01-donnees-saut.html',1,'lot-09']]],
  ['saut_20au_20sol_20hauteur_20variable_31',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['saut_20espace_20w_20→_20intention_32',['TACHE-02 — Mapping du saut (Espace/W → intention)',['../lot-09-tache-02-mapping-saut.html',1,'lot-09']]],
  ['saut_20et_20game_20feel_33',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md139',1,'']]],
  ['saut_20game_20feel_20et_20enchaînement_20de_20niveaux_34',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['saut_20requis_20preuve_35',['TACHE-06 — Niveaux de démo (séquence, dont saut requis) + preuve',['../lot-09-tache-06-niveaux-demo.html',1,'lot-09']]],
  ['saut_20sauts_20aériens_20rechargés_20au_20sol_36',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['saut_20wall_20jump_20dash_37',['LOT-10 — Mécaniques aériennes avancées : double saut, wall jump, dash',['../lot-10.html',1,'lots']]],
  ['sauts_20aériens_20rechargés_20au_20sol_38',['TACHE-03 — Double saut (sauts aériens rechargés au sol)',['../lot-10-tache-03-double-saut.html',1,'lot-10']]],
  ['sauts_20dashs_20dans_20la_20physique_39',['TACHE-03 — Budget de sauts/dashs dans la physique',['../lot-12-tache-03-budget.html',1,'lot-12']]],
  ['scène_20de_20démo_40',['TACHE-06 — Câblage du World dans la boucle + scène de démo',['../lot-05-tache-06-cablage-world-demo.html',1,'lot-05']]],
  ['screenmanager_41',['TACHE-01 — Menu principal Qt + navigation (remplace `IScreen`/`ScreenManager`)',['../lot-38-tache-01-menu-navigation-qt.html',1,'lot-38']]],
  ['se_20lier_20à_20qui_42',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md57',1,'']]],
  ['se_20voit_20_3a_20le_20culling_20lot_2040_43',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md161',1,'']]],
  ['seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_44',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md77',1,'']]],
  ['secousse_20d_20écran_45',['TACHE-03 — Rendu des particules et secousse d&apos;écran',['../lot-53-tache-03-rendu-secousse.html',1,'lot-53']]],
  ['section_20«_20animations_20»_20du_20panneau_20«_20textures_20»_46',['TACHE-04 — Section « Animations » du panneau « Textures »',['../lot-47-tache-04-section-animations.html',1,'lot-47']]],
  ['section_20«_20décors_20»_20du_20panneau_20«_20textures_20»_47',['TACHE-04 — Section « Décors » du panneau « Textures »',['../lot-50-tache-04-section-decors.html',1,'lot-50']]],
  ['section_20«_20fond_20»_20et_20sélecteur_20de_20jeu_20de_20skins_48',['TACHE-03 — Section « Fond » et sélecteur de jeu de skins',['../lot-44-tache-03-section-fond.html',1,'lot-44']]],
  ['section_20«_20objets_20»_20et_20priorité_20de_20résolution_49',['TACHE-03 — Section « Objets » et priorité de résolution',['../lot-45-tache-03-section-objets-priorite.html',1,'lot-45']]],
  ['section_20skins_50',['TACHE-04 — Panneau Qt « Textures » (section Skins)',['../lot-42-tache-04-panneau-textures.html',1,'lot-42']]],
  ['segment_20orienté_20liens_20de_20mécanismes_20lot_2037_51',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md153',1,'']]],
  ['ses_20fichiers_20de_20niveaux_52',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md69',1,'']]],
  ['set_20core_3a_3acomponentpool_53',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md49',1,'']]],
  ['set_20typé_54',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['seule_20cible_20_3a_20l_20application_20qt_55',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md83',1,'']]],
  ['seulement_20l_20état_56',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md73',1,'']]],
  ['seulement_20l_20arrivée_57',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md128',1,'']]],
  ['shaders_20et_20échantillonnage_20nearest_58',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md152',1,'']]],
  ['si_20logique_59',['Tests (obligatoires si logique)',['../lot-05-tache-01-composant-sprite.html#autotoc_md485',1,'']]],
  ['signaux_60',['signaux',['../guide-ecrans.html#autotoc_md40',1,'Le principe : des pages empilées, pilotées par signaux'],['../guide-ecrans.html#autotoc_md41',1,'Qui déclenche les transitions : les signaux']]],
  ['silhouette_20du_20personnage_20dans_20l_20atlas_61',['TACHE-01 — Silhouette du personnage dans l&apos;atlas',['../lot-17-tache-01-silhouette-personnage.html',1,'lot-17']]],
  ['silhouettes_20et_20des_20blocs_20réduits_62',['TACHE-03 — Ombres des silhouettes et des blocs réduits',['../lot-55-tache-03-ombres-silhouettes.html',1,'lot-55']]],
  ['simples_20dans_20le_20cpp_63',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md199',1,'']]],
  ['simulation_64',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md38',1,'']]],
  ['simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_65',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md22',1,'']]],
  ['simulation_20↔_20rendu_66',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md174',1,'']]],
  ['simulation_20et_20les_20entrées_67',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['sinks_20_3a_20où_20finissent_20les_20messages_68',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md94',1,'']]],
  ['sinks_20différents_20en_20développement_20et_20en_20release_69',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md100',1,'']]],
  ['sinks_20enfichables_70',['TACHE-02 — Sinks enfichables',['../lot-02-tache-02-sinks.html',1,'lot-02']]],
  ['skin_20des_20tuiles_20_3a_20jeux_20de_20skins_20et_20raccords_20automatiques_71',['LOT-42 — Skin des tuiles : jeux de skins et raccords automatiques',['../lot-42.html',1,'lots']]],
  ['skin_20et_20animations_20depuis_20fichier_72',['LOT-48 — Personnage : skin et animations depuis fichier',['../lot-48.html',1,'lots']]],
  ['skins_73',['TACHE-04 — Panneau Qt « Textures » (section Skins)',['../lot-42-tache-04-panneau-textures.html',1,'lot-42']]],
  ['skins_74',['skins',['../lot-42-tache-01-skins-json.html',1,'TACHE-01 — `skins.json` : format versionné et jeux de skins'],['../lot-44-tache-03-section-fond.html',1,'TACHE-03 — Section « Fond » et sélecteur de jeu de skins']]],
  ['skins_20de_20tuiles_20animés_75',['TACHE-05 — Skins de tuiles animés',['../lot-46-tache-05-tuiles-animees.html',1,'lot-46']]],
  ['skins_20et_20raccords_20automatiques_76',['LOT-42 — Skin des tuiles : jeux de skins et raccords automatiques',['../lot-42.html',1,'lots']]],
  ['skins_20json_20_3a_20format_20versionné_20et_20jeux_20de_20skins_77',['TACHE-01 — `skins.json` : format versionné et jeux de skins',['../lot-42-tache-01-skins-json.html',1,'lot-42']]],
  ['slide_78',['slide',['../guide-physique.html#autotoc_md141',1,'6. Wall jump et wall slide'],['../lot-10-tache-04-wall-jump.html',1,'TACHE-04 — Wall jump + wall slide']]],
  ['socle_20applicatif_79',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md245',1,'']]],
  ['socle_20applicatif_20viewport_20d3d11_20embarqué_80',['LOT-34 — Refonte IHM (Qt) : socle applicatif &amp;amp; viewport D3D11 embarqué',['../lot-34.html',1,'lots']]],
  ['socle_20applicatif_20viewport_20direct3d_2011_81',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['sol_82',['sol',['../lot-10-tache-03-double-saut.html',1,'TACHE-03 — Double saut (sauts aériens rechargés au sol)'],['../lot-10-tache-05-dash.html',1,'TACHE-05 — Dash 8 directions (burst, durée, recharge au sol)']]],
  ['sol_20hauteur_20variable_83',['TACHE-03 — Saut au sol + hauteur variable',['../lot-09-tache-03-saut-hauteur-variable.html',1,'lot-09']]],
  ['solide_84',['solide',['../guide-physique.html#autotoc_md133',1,'Pourquoi une pente (ou un arrondi) n&apos;est jamais solide'],['../lot-55-tache-01-quad-ombre.html',1,'TACHE-01 — Quad d&apos;ombre par tuile solide']]],
  ['solide_20→_20case_20de_20planche_85',['TACHE-02 — Raccords automatiques : voisinage solide → case de planche',['../lot-42-tache-02-raccords-automatiques.html',1,'lot-42']]],
  ['solidité_20partielle_20n_20est_20pas_20la_20solution_86',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2387',1,'']]],
  ['solution_87',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2387',1,'']]],
  ['solution_20_3a_20tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_88',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md128',1,'']]],
  ['sommets_20shaders_20et_20échantillonnage_20nearest_89',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md152',1,'']]],
  ['son_20repli_20procédural_90',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['sondage_20manette_91',['TACHE-01 — Entrées nerveuses : fronts non perdus, focus, sondage manette',['../lot-33-tache-01-entrees-nerveuses.html',1,'lot-33']]],
  ['sortie_20liaison_20de_20mécanismes_20redimensionnement_92',['TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'lot-14']]],
  ['soumises_93',['TACHE-04 — *QuadRecorder* : capture des primitives soumises',['../lot-40-tache-04-quad-recorder.html',1,'lot-40']]],
  ['source_94',['Chemins complets depuis Source/',['../spec-conventions.html#autotoc_md192',1,'']]],
  ['source_20elements_20assets_20_3a_20convention_20et_20régénération_95',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_96',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md77',1,'']]],
  ['souris_97',['TACHE-01 — Entrées clavier &amp;amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['spécification_20navigables_20conventions_20incluses_98',['TACHE-04 — Pages de spécification navigables (conventions incluses)',['../lot-04-tache-04-pages-specification.html',1,'lot-04']]],
  ['spécifications_99',['Spécifications',['../specifications.html',1,'index']]],
  ['spécifications_20et_20vérification_100',['TACHE-04 — Documentation, spécifications et vérification',['../lot-33-tache-04-documentation-verification.html',1,'lot-33']]],
  ['sparse_20set_20core_3a_3acomponentpool_101',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md49',1,'']]],
  ['sparse_20set_20typé_102',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['spawn_200_204×0_208_20sprite_103',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['spec_20à_20documenter_20dans_20l_20index_104',['Convention d&apos;insertion d&apos;une nouvelle spec (à documenter dans l&apos;index)',['../lot-04-tache-04-pages-specification.html#autotoc_md436',1,'']]],
  ['spirale_20de_20la_20mort_20»_105',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md35',1,'']]],
  ['sprite_106',['TACHE-03 — Personnage humanoïde (spawn 0,4×0,8, sprite)',['../lot-11-tache-03-personnage-humanoide.html',1,'lot-11']]],
  ['sprite_20à_20la_20fois_107',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md150',1,'']]],
  ['sprite_20données_20pures_108',['TACHE-01 — Composant Sprite (données pures)',['../lot-05-tache-01-composant-sprite.html',1,'lot-05']]],
  ['sprite_20du_20personnage_20statique_109',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['spritequad_20_3a_20un_20rectangle_20texturé_110',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_111',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md149',1,'']]],
  ['sprites_20caméra_112',['LOT-05 — Rendu 2D : atlas, sprites &amp;amp; caméra',['../lot-05.html',1,'lots']]],
  ['sprites_20ecs_20→_20écran_113',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['spritesheet_20chargé_20depuis_20un_20fichier_114',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md154',1,'']]],
  ['spritesheet_20externe_20et_20ancrage_20image_20hitbox_115',['TACHE-01 — Spritesheet externe et ancrage image/hitbox',['../lot-48-tache-01-spritesheet-externe.html',1,'lot-48']]],
  ['spritesheet_20externe_20et_20découplage_20image_20hitbox_116',['&lt;span class=&quot;tt&quot;&gt;LOT-48&lt;/span&gt; : spritesheet externe et découplage image/hitbox',['../guide-rendu.html#autotoc_md158',1,'']]],
  ['squelette_20première_20page_117',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]],
  ['stables_20ancres_20doxygen_20lint_20ci_118',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['standard_119',['1. Langage &amp;amp; standard',['../spec-conventions.html#autotoc_md188',1,'']]],
  ['statique_120',['LOT-17 — Sprite du personnage (statique)',['../lot-17.html',1,'lots']]],
  ['stb_5fimage_20résolution_20d_20assets_20testable_121',['TACHE-01 — Loader image → texture D3D11 (`QImage`/`stb_image`) + résolution d&apos;assets testable',['../lot-39-tache-01-loader-image-assets.html',1,'lot-39']]],
  ['stockage_20_3a_20sparse_20set_20core_3a_3acomponentpool_122',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md49',1,'']]],
  ['stockage_20de_20composants_20sparse_20set_20typé_123',['TACHE-03 — Stockage de composants (sparse set typé)',['../lot-03-tache-03-stockage-composants.html',1,'lot-03']]],
  ['stricte_20est_20dangereuse_124',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md108',1,'']]],
  ['structurées_125',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['succès_20échec_126',['succès échec',['../lot-08-tache-04-regles-fin-niveau.html',1,'TACHE-04 — Règles de fin de niveau (succès / échec)'],['../lot-08-tache-06-integration-jouable.html',1,'TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)']]],
  ['suivi_127',['TACHE-01 — Modèle de tuile et physique de suivi',['../lot-26-tache-01-modele-physique-plafond.html',1,'lot-26']]],
  ['suivi_20de_20pente_128',['TACHE-02 — Collision et suivi de pente',['../lot-22-tache-02-collision-suivi-pente.html',1,'lot-22']]],
  ['suivi_20de_20pente_20et_20d_20arrondi_20ex_20gp_20003_20ex_20gp_20004_129',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md132',1,'']]],
  ['suppression_20_3a_20swap_20and_20pop_130',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md50',1,'']]],
  ['suppression_20documentation_20vérification_131',['TACHE-03 — Panneau « Liens » (liste, surbrillance, suppression) ; documentation &amp;amp; vérification',['../lot-37-tache-03-panneau-liens-doc.html',1,'lot-37']]],
  ['suppression_20et_20détection_20des_20références_132',['TACHE-02 — Import, renommage, duplication, suppression et détection des références',['../lot-43-tache-02-gestion-fichiers.html',1,'lot-43']]],
  ['supprimer_20couche_20testable_133',['TACHE-02 — Opérations fichiers (créer/renommer/dupliquer/supprimer) + couche testable',['../lot-36-tache-02-operations-fichiers.html',1,'lot-36']]],
  ['sur_20atlas_20fichier_20interface_20conservée_20repli_20procédural_134',['TACHE-02 — `TextureAtlas` sur atlas fichier (interface conservée, repli procédural)',['../lot-39-tache-02-texture-atlas-fichier.html',1,'lot-39']]],
  ['sur_20clip_20manquant_135',['TACHE-02 — Transitions jouées une fois et repli sur clip manquant',['../lot-47-tache-02-transitions.html',1,'lot-47']]],
  ['sur_20leveldraft_136',['TACHE-01 — Mutateurs de décors sur `LevelDraft`',['../lot-50-tache-01-mutateurs-decor.html',1,'lot-50']]],
  ['surbrillance_20suppression_20documentation_20vérification_137',['TACHE-03 — Panneau « Liens » (liste, surbrillance, suppression) ; documentation &amp;amp; vérification',['../lot-37-tache-03-panneau-liens-doc.html',1,'lot-37']]],
  ['surface_20de_20dessin_20_3a_20le_20viewport_20qt_20hmi_3a_3agameviewport_138',['La surface de dessin : le viewport Qt (&lt;span class=&quot;tt&quot;&gt;hmi::GameViewport&lt;/span&gt;)',['../guide-rendu.html#autotoc_md146',1,'']]],
  ['swap_20and_20pop_139',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md50',1,'']]],
  ['swap_20chain_20back_20buffer_140',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md144',1,'']]],
  ['swept_20aabb_141',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md126',1,'']]],
  ['sync_20langue_20remappage_20jeu_20éditeur_20manette_142',['TACHE-02 — Options Qt (V-Sync, langue) + remappage jeu/éditeur/manette',['../lot-38-tache-02-options-remappage-qt.html',1,'lot-38']]],
  ['système_143',['système',['../lot-25-tache-03-integration-sequence-tests.html',1,'TACHE-03 — Intégration séquence et tests système'],['../lot-10-tache-06-niveau-parkour.html',1,'TACHE-06 — Niveau de démo « parkour » + preuve système']]],
  ['système_203_144',['Tests système (3)',['../cahiertest.html#autotoc_md27',1,'']]],
  ['système_20d_20animation_145',['TACHE-01 — Composant et système d&apos;animation',['../lot-18-tache-01-composant-systeme-animation.html',1,'lot-18']]],
  ['système_20de_20décors_146',['1. Système de décors',['../spec-decors.html#autotoc_md208',1,'']]],
  ['système_20de_20mouvement_20démo_147',['TACHE-06 — Composant Transform + système de mouvement (démo)',['../lot-03-tache-06-transform-demo.html',1,'lot-03']]],
  ['système_20de_20rendu_20des_20sprites_20ecs_20→_20écran_148',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['système_20guide_20non_20codeur_20git_149',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['systèmes_150',['systèmes',['../spec-architecture.html#autotoc_md178',1,'8. Communication inter-systèmes'],['../guide-ecs.html',1,'ECS : entités, composants, systèmes']]],
  ['systèmes_20de_20coordonnées_20à_20ne_20pas_20confondre_151',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md111',1,'']]],
  ['systèmes_20et_20l_20ordre_20d_20exécution_152',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md53',1,'']]],
  ['systèmes_20world_20orchestration_20au_20pas_20fixe_153',['TACHE-05 — Systèmes &amp;amp; World (orchestration au pas fixe)',['../lot-03-tache-05-systemes-world.html',1,'lot-03']]]
];
