var searchData=
[
  ['ecs_20à_20l_20écran_0',['Rendu 2D : de l&apos;ECS à l&apos;écran',['../guide-rendu.html',1,'guide']]],
  ['ecs_20→_20écran_1',['TACHE-05 — Système de rendu des sprites (ECS → écran)',['../lot-05-tache-05-systeme-rendu-sprites.html',1,'lot-05']]],
  ['ecs_20_3a_20entités_20composants_20systèmes_2',['ECS : entités, composants, systèmes',['../guide-ecs.html',1,'guide']]],
  ['ecs_20mathématiques_20core_3',['LOT-03 — Fondation ECS &amp; mathématiques `Core`',['../lot-03.html',1,'lots']]],
  ['effacement_20écran_20présentation_20redimensionnement_4',['TACHE-04 — Effacement écran, présentation &amp; redimensionnement',['../lot-01-tache-04-effacement-presentation.html',1,'lot-01']]],
  ['en_20mémoire_20erreurs_20de_20validation_20structurées_5',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['enchaînement_20de_20niveaux_6',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['enchaînement_20de_20niveaux_20séquence_20auto_20avance_20retour_20titre_7',['TACHE-05 — Enchaînement de niveaux (séquence, auto-avance, retour titre)',['../lot-09-tache-05-enchainement-niveaux.html',1,'lot-09']]],
  ['enfichables_8',['TACHE-02 — Sinks enfichables',['../lot-02-tache-02-sinks.html',1,'lot-02']]],
  ['enregistrement_20validation_20essai_20immédiat_9',['TACHE-05 — Enregistrement, validation, essai immédiat',['../lot-14-tache-05-enregistrement-validation-essai.html',1,'lot-14']]],
  ['enregistrer_10',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['entités_20_3a_20handles_20générationnels_20cycle_20de_20vie_11',['TACHE-02 — Entités : handles générationnels &amp; cycle de vie',['../lot-03-tache-02-entites.html',1,'lot-03']]],
  ['entités_20composants_20systèmes_12',['ECS : entités, composants, systèmes',['../guide-ecs.html',1,'guide']]],
  ['entrée_13',['TACHE-01 — Composants du personnage &amp; intention d&apos;entrée',['../lot-08-tache-01-composants-personnage.html',1,'lot-08']]],
  ['entrée_20mapping_20touches_20→_20intention_14',['TACHE-05 — Actions logiques d&apos;entrée (mapping touches → intention)',['../lot-08-tache-05-actions-logiques.html',1,'lot-08']]],
  ['entrée_20sortie_20liaison_20de_20mécanismes_20redimensionnement_15',['TACHE-03 — Entrée/sortie, liaison de mécanismes, redimensionnement',['../lot-14-tache-03-entree-sortie-mecanismes-redimension.html',1,'lot-14']]],
  ['entrées_16',['Contrôles &amp; entrées',['../spec-controles.html',1,'specifications']]],
  ['entrées_20bas_20niveau_20_3a_20molette_20et_20texte_20tapé_17',['TACHE-01 — Entrées bas niveau : molette et texte tapé',['../lot-15-tache-01-entrees-molette-texte.html',1,'lot-15']]],
  ['entrées_20clavier_20souris_18',['TACHE-01 — Entrées clavier &amp; souris',['../lot-06-tache-01-entrees-clavier-souris.html',1,'lot-06']]],
  ['entrées_20et_20actions_20logiques_19',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['erreurs_20de_20validation_20structurées_20',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['espace_20w_20→_20intention_21',['TACHE-02 — Mapping du saut (`Espace`/`W` → intention)',['../lot-09-tache-02-mapping-saut.html',1,'lot-09']]],
  ['essai_20immédiat_22',['essai immédiat',['../lot-14.html',1,'LOT-14 — Éditeur de niveaux intégré : édition de tuiles, mécanismes, essai immédiat'],['../lot-14-tache-05-enregistrement-validation-essai.html',1,'TACHE-05 — Enregistrement, validation, essai immédiat']]],
  ['essai_20immédiat_20en_20mémoire_20erreurs_20de_20validation_20structurées_23',['TACHE-07 — Essai immédiat en mémoire, erreurs de validation structurées',['../lot-15-tache-07-essai-memoire-erreurs-structurees.html',1,'lot-15']]],
  ['et_20actions_20logiques_24',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['et_20assertions_25',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['et_20chargement_26',['LOT-07 — Niveaux : modèle et chargement',['../lot-07.html',1,'lots']]],
  ['et_20collisions_27',['LOT-08 — Gameplay personnage : déplacement, gravité et collisions',['../lot-08.html',1,'lots']]],
  ['et_20confort_20d_20édition_28',['LOT-15 — Éditeur de niveaux : robustesse et confort d&apos;édition',['../lot-15.html',1,'lots']]],
  ['et_20de_20niveau_29',['TACHE-02 — Modèle de tuiles et de niveau',['../lot-07-tache-02-modele-niveau.html',1,'lot-07']]],
  ['et_20enchaînement_20de_20niveaux_30',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['et_20lancer_20le_20jeu_31',['Télécharger et lancer le jeu',['../manuel-telecharger.html',1,'manuel']]],
  ['et_20partager_20un_20niveau_20sans_20ligne_20de_20commande_32',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['et_20pas_20de_20temps_20fixe_33',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['et_20texte_20tapé_34',['TACHE-01 — Entrées bas niveau : molette et texte tapé',['../lot-15-tache-01-entrees-molette-texte.html',1,'lot-15']]],
  ['et_20zoom_20manuels_35',['TACHE-04 — Caméra : pan et zoom manuels',['../lot-15-tache-04-camera-pan-zoom.html',1,'lot-15']]],
  ['exigences_20ids_20stables_20ancres_20doxygen_20lint_20ci_36',['TACHE-08 — Traçabilité des exigences (IDs stables, ancres Doxygen, lint CI)',['../lot-04-tache-08-tracabilite-exigences.html',1,'lot-04']]],
  ['exigences_20non_20fonctionnelles_37',['Exigences non fonctionnelles',['../spec-exigences.html',1,'specifications']]]
];
