var searchData=
[
  ['ui_0',['LOT-38 — Refonte IHM (Qt) : menus, options, remappage &amp;amp; retrait du legacy UI',['../lot-38.html',1,'lots']]],
  ['ui_20écrans_20maison_20fenêtre_20win32_20ancienne_20boucle_1',['TACHE-03 — Retrait du legacy UI (écrans maison, fenêtre Win32, ancienne boucle)',['../lot-38-tache-03-retrait-legacy-ui.html',1,'lot-38']]],
  ['ui_20de_20remappage_20et_20câblage_2',['TACHE-03 — UI de remappage et câblage',['../lot-29-tache-03-ui-remappage.html',1,'lot-29']]],
  ['ui_20de_20remappage_20manette_20et_20câblage_3',['TACHE-03 — UI de remappage manette et câblage',['../lot-30-tache-03-ui-remappage-manette.html',1,'lot-30']]],
  ['ultérieurs_4',['ultérieurs',['../lot-01.html#autotoc_md325',1,'Exclus (lots ultérieurs)'],['../lot-03.html#autotoc_md407',1,'Exclus (lots ultérieurs)'],['../lot-04.html#autotoc_md458',1,'Exclus (lots ultérieurs)'],['../lot-05.html#autotoc_md527',1,'Exclus (lots ultérieurs)'],['../lot-06.html#autotoc_md579',1,'Exclus (lots ultérieurs)'],['../lot-07.html#autotoc_md645',1,'Exclus (lots ultérieurs)'],['../lot-08.html#autotoc_md697',1,'Exclus (lots ultérieurs)'],['../lot-09.html#autotoc_md749',1,'Exclus (lots ultérieurs)'],['../lot-10.html#autotoc_md801',1,'Exclus (lots ultérieurs)'],['../lot-11.html#autotoc_md853',1,'Exclus (lots ultérieurs)'],['../lot-12.html#autotoc_md891',1,'Exclus (lots ultérieurs)'],['../lot-14.html#autotoc_md938',1,'Exclus (lots ultérieurs)']]],
  ['ultérieurs_20ou_20non_20retenus_5',['Exclus (lots ultérieurs ou non retenus)',['../lot-15.html#autotoc_md990',1,'']]],
  ['un_20état_20un_20contrôle_6',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md70',1,'']]],
  ['un_20arrondi_20n_20est_20jamais_20solide_7',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md175',1,'']]],
  ['un_20asset_20à_20une_20taille_20forcément_20conforme_8',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['un_20calque_20pour_20l_20audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_9',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['un_20contenu_20plus_20grand_20que_20la_20fenêtre_20_3a_20fitzoom_20et_20hmi_3a_3aroomgrid_10',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md190',1,'']]],
  ['un_20contrôle_11',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md70',1,'']]],
  ['un_20fichier_12',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md196',1,'']]],
  ['un_20jeu_20vidéo_13',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md132',1,'']]],
  ['un_20niveau_14',['un niveau',['../manuel-partager-niveau.html#autotoc_md2975',1,'3. Créer un niveau'],['../manuel-jouer.html#autotoc_md2968',1,'Objectif d&apos;un niveau']]],
  ['un_20niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_15',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md126',1,'']]],
  ['un_20niveau_20plus_20grand_20que_20la_20fenêtre_16',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md106',1,'']]],
  ['un_20niveau_20qu_20on_20peut_20défaire_17',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : un niveau qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['un_20niveau_20sans_20ligne_20de_20commande_18',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['un_20niveau_20sans_20re_20coder_20le_20moteur_19',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['un_20outil_20différent_20',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a24ec0bff1ac1e68bdf8ac50376a41076&quot; title=&quot;PROJECTGAMING_ASSERT&quot;&gt;PROJECTGAMING_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md142',1,'']]],
  ['un_20pas_21',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md76',1,'']]],
  ['un_20pas_20résumé_22',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md184',1,'']]],
  ['un_20piège_23',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md97',1,'']]],
  ['un_20pixel_24',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['un_20pixel_20en_20case_25',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_26',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['un_20point_20ou_20une_20direction_20dans_20le_20monde_27',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md144',1,'']]],
  ['un_20prédicat_20de_20solidité_20partielle_20n_20est_20pas_20la_20solution_28',['Un prédicat de solidité partielle n&apos;est pas la solution',['../lot-55-tache-03-ombres-silhouettes.html#autotoc_md2472',1,'']]],
  ['un_20rectangle_20texturé_29',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md193',1,'']]],
  ['un_20repli_20qui_20n_20invente_20rien_30',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['un_20segment_20orienté_20liens_20de_20mécanismes_20lot_2037_31',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md195',1,'']]],
  ['un_20sprite_20à_20la_20fois_32',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md192',1,'']]],
  ['un_20spritesheet_20chargé_20depuis_20un_20fichier_33',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md196',1,'']]],
  ['un_20système_20de_20design_34',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['un_20tampon_20de_20pixels_35',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md35',1,'']]],
  ['undo_20redo_20copier_20coller_36',['TACHE-03 — Barre d&apos;outils + peinture viewport → `LevelDraft` (undo/redo, copier/coller)',['../lot-35-tache-03-outils-peinture-viewport.html',1,'lot-35']]],
  ['une_20application_20habillée_37',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['une_20barre_20d_20état_20structurée_38',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md68',1,'']]],
  ['une_20boucle_20de_20jeu_39',['Qu&apos;est-ce qu&apos;une boucle de jeu ?',['../guide-boucle.html#autotoc_md50',1,'']]],
  ['une_20chaîne_20en_20quads_40',['TACHE-02 — *TextRenderer* : composition d&apos;une chaîne en quads',['../lot-52-tache-02-text-renderer.html',1,'lot-52']]],
  ['une_20définition_20trois_20surfaces_41',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['une_20direction_20dans_20le_20monde_42',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md144',1,'']]],
  ['une_20donnée_43',['TACHE-01 — Le clip devient une donnée',['../lot-46-tache-01-modele-clip.html',1,'lot-46']]],
  ['une_20extrémité_44',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md178',1,'']]],
  ['une_20fenêtre_20qt_45',['Le viewport : Direct3D 11 dans une fenêtre Qt',['../guide-ihm-qt.html#autotoc_md123',1,'']]],
  ['une_20fois_20de_20plus_46',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md43',1,'']]],
  ['une_20fois_20et_20repli_20sur_20clip_20manquant_47',['TACHE-02 — Transitions jouées une fois et repli sur clip manquant',['../lot-47-tache-02-transitions.html',1,'lot-47']]],
  ['une_20frame_48',['Le cycle d&apos;une frame',['../guide-entrees.html#autotoc_md113',1,'']]],
  ['une_20ligne_20_3a_20core_3a_3aformatlogline_20core_3a_3aformatlogline_49',['Le format d&apos;une ligne : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aafa85d91ee91c84b123fff01f147615e&quot; title=&quot;core::formatLogLine&quot;&gt;core::formatLogLine&lt;/a&gt;',['../guide-journalisation.html#autotoc_md139',1,'']]],
  ['une_20même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_50',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['une_20nouvelle_20spec_20à_20documenter_20dans_20l_20index_51',['Convention d&apos;insertion d&apos;une nouvelle spec (à documenter dans l&apos;index)',['../lot-04-tache-04-pages-specification.html#autotoc_md488',1,'']]],
  ['une_20pente_20ou_20un_20arrondi_20n_20est_20jamais_20solide_52',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md175',1,'']]],
  ['une_20police_20embarquée_20un_20repli_20qui_20n_20invente_20rien_53',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['une_20progression_20générale_20lot_2046_54',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md201',1,'']]],
  ['une_20règle_20de_20performance_20à_20respecter_55',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md138',1,'']]],
  ['une_20seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_56',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md116',1,'']]],
  ['une_20seule_20cible_20_3a_20l_20application_20qt_57',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md122',1,'']]],
  ['une_20seule_20paire_20annuler_20refaire_20deux_20cibles_58',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md41',1,'']]],
  ['une_20seule_20source_20deux_20portées_20étanches_59',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['une_20taille_20forcément_20conforme_60',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['une_20touche_20dans_20le_20gameplay_61',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md110',1,'']]],
  ['une_20version_20publiée_62',['LOT-61 — Diagnostics d&apos;une version publiée',['../lot-61.html',1,'lots']]],
  ['unification_63',['5. Menus, options, unification',['../spec-interface-ihm.html#autotoc_md299',1,'']]],
  ['unification_20des_20menus_20lot_2038_64',['Liens de mécanismes (LOT-37) et unification des menus (LOT-38)',['../guide-ihm-qt.html#autotoc_md129',1,'']]],
  ['unique_65',['unique',['../guide-design-ihm.html#autotoc_md67',1,'Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique'],['../lot-56-tache-03-typographie-police.html',1,'TACHE-03 — Police embarquée et typographie à source unique']]],
  ['unités_20—_20trois_20espaces_20distincts_66',['3. Coordonnées &amp;amp; unités — trois espaces distincts',['../spec-architecture.html#autotoc_md223',1,'']]],
  ['unités_20et_20de_20repère_67',['Conventions d&apos;unités et de repère',['../guide-maths.html#autotoc_md148',1,'']]],
  ['unités_20monde_20et_20pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_68',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md189',1,'']]],
  ['unitaire_69',['Vérification (visuelle, pas de test unitaire)',['../lot-08-tache-06-integration-jouable.html#autotoc_md742',1,'']]],
  ['unitaire_20—_20brique_20gpu_70',['Vérification (visuelle, pas de test unitaire — brique GPU)',['../lot-11-tache-03-personnage-humanoide.html#autotoc_md877',1,'']]],
  ['unitaires_20929_71',['Tests unitaires (929)',['../cahiertest.html#autotoc_md4',1,'']]],
  ['utilisateur_72',['utilisateur',['../lot-15-tache-01-entrees-molette-texte.html#autotoc_md1004',1,'Ajustement post-livraison (essai utilisateur)'],['../lot-15-tache-04-camera-pan-zoom.html#autotoc_md1024',1,'Ajustement post-livraison (essai utilisateur)'],['../lot-15-tache-06-decouvrabilite.html#autotoc_md1041',1,'Ajustement post-livraison (essai utilisateur)'],['../manuel.html',1,'Manuel utilisateur']]],
  ['utilisateur_20ihm_73',['Interface utilisateur (IHM)',['../spec-interface-ihm.html',1,'specifications']]],
  ['utilisateur_20squelette_20première_20page_74',['TACHE-06 — Manuel utilisateur (squelette + première page)',['../lot-04-tache-06-manuel-utilisateur.html',1,'lot-04']]]
];
