var searchData=
[
  ['généré_0',['TACHE-02 — Numéro de version généré',['../lot-66-tache-02-version-source-unique.html',1,'lot-66']]],
  ['générale_20lot_2046_1',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md221',1,'']]],
  ['généralisé_2',['TACHE-02 — `AnimationSystem` généralisé',['../lot-46-tache-02-systeme-generalise.html',1,'lot-46']]],
  ['généralisation_20des_20liaisons_3',['TACHE-01 — Modèle (types, format, généralisation des liaisons)',['../lot-31-tache-01-modele-dangers-avances.html',1,'lot-31']]],
  ['générationnels_20cycle_20de_20vie_4',['TACHE-02 — Entités : handles générationnels &amp;amp; cycle de vie',['../lot-03-tache-02-entites.html',1,'lot-03']]],
  ['générique_20piloté_20par_20données_5',['LOT-46 — Moteur d&apos;animation générique piloté par données',['../lot-46.html',1,'lots']]],
  ['géométrie_20d_20abord_20le_20widget_20ensuite_6',['Le canevas : la géométrie d&apos;abord, le widget ensuite',['../guide-atelier-pixel-art.html#autotoc_md41',1,'']]],
  ['géométrie_20des_20traits_20logique_20testable_7',['TACHE-01 — Primitive de ligne/flèche (pipeline) + géométrie des traits (logique testable)',['../lot-37-tache-01-primitive-ligne-geometrie.html',1,'lot-37']]],
  ['géométrie_20pure_8',['TACHE-02 — Balayage AABB contre la grille (géométrie pure)',['../lot-08-tache-02-balayage-aabb.html',1,'lot-08']]],
  ['géométrique_20pas_20un_20aperçu_9',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md120',1,'']]],
  ['gérer_20ses_20fichiers_20de_20niveaux_10',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md121',1,'']]],
  ['game_2048_11',['Game (48)',['../cahiertest.html#autotoc_md17',1,'']]],
  ['game_20feel_12',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md199',1,'']]],
  ['game_20feel_20—_20⚠️_20réglage_20fin_20reporté_20au_20delà_20de_200_201_200_13',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md318',1,'']]],
  ['game_20feel_20et_20enchaînement_20de_20niveaux_14',['LOT-09 — Saut, game feel et enchaînement de niveaux',['../lot-09.html',1,'lots']]],
  ['gamekeybindings_20hmi_3a_3aeditorkeybindings_20editorkeybindings_20lot_2029_20hmi_3a_3agamepadbindings_20gamepadbindings_20lot_2030_15',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md131',1,'']]],
  ['gamepadbindings_20lot_2030_16',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md131',1,'']]],
  ['gameplay_17',['Gameplay',['../spec-gameplay.html',1,'specifications']]],
  ['gameplay_18',['gameplay',['../spec-vision.html#autotoc_md347',1,'Boucle de gameplay'],['../guide-entrees.html#autotoc_md123',1,'Le principe : ne jamais coder « en dur » une touche dans le gameplay'],['../lot-48-tache-03-orientation-non-regression.html',1,'TACHE-03 — Orientation et non-régression du gameplay']]],
  ['gameplay_2053_19',['Gameplay (53)',['../cahiertest.html#autotoc_md8',1,'']]],
  ['gameplay_20livrés_20',['TACHE-02 — Clips couvrant les états de gameplay livrés',['../lot-48-tache-02-nouveaux-clips.html',1,'lot-48']]],
  ['gameplay_20personnage_20_3a_20déplacement_20gravité_20et_20collisions_21',['LOT-08 — Gameplay personnage : déplacement, gravité et collisions',['../lot-08.html',1,'lots']]],
  ['gamescreen_20cadrage_20fixe_20succès_20échec_22',['TACHE-06 — Intégration jouable dans GameScreen (cadrage fixe, succès / échec)',['../lot-08-tache-06-integration-jouable.html',1,'lot-08']]],
  ['gamescreen_20characterphysicssystem_20inchangé_23',['Décision retenue : composition côté &lt;span class=&quot;tt&quot;&gt;GameScreen&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;CharacterPhysicsSystem&lt;/span&gt; inchangé',['../lot-24-tache-02-collision-boite-boite.html#autotoc_md1370',1,'']]],
  ['gamescreen_20niveau_20demo4_20preuves_24',['TACHE-04 — Intégration GameScreen + niveau demo4 + preuves',['../lot-12-tache-04-integration-puzzle.html',1,'lot-12']]],
  ['garde_20fou_20d_20écrasement_25',['TACHE-05 — Ouvrir, créer, enregistrer et garde-fou d&apos;écrasement',['../lot-54-tache-05-ouvrir-enregistrer.html',1,'lot-54']]],
  ['garde_20fou_20de_20couverture_26',['TACHE-01 — Inventaire des mécaniques et garde-fou de couverture',['../lot-65-tache-01-inventaire-garde-fou.html',1,'lot-65']]],
  ['garde_20fou_20de_20couverture_20des_20mécaniques_20ex_20lvl_20015_20lot_2065_27',['Garde-fou de couverture des mécaniques (&lt;span class=&quot;tt&quot;&gt;EX-LVL-015&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md183',1,'']]],
  ['garde_20fou_20dirty_20indicateurs_20d_20état_20erreurs_20documentation_20vérification_28',['TACHE-03 — Ouverture avec garde-fou `dirty`, indicateurs d&apos;état/erreurs ; documentation &amp;amp; vérification',['../lot-36-tache-03-ouverture-garde-fou-doc.html',1,'lot-36']]],
  ['garde_20fous_20_3a_20redimensionnement_20destructeur_20quitter_20sans_20enregistrer_29',['TACHE-02 — Garde-fous : redimensionnement destructeur, quitter sans enregistrer',['../lot-15-tache-02-garde-fous-perte-donnees.html',1,'lot-15']]],
  ['garde_20fous_20contre_20la_20perte_20de_20travail_30',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md113',1,'']]],
  ['garde_20fous_20de_20profondeur_31',['TACHE-05 — Doctrine de conception et garde-fous de profondeur',['../lot-65-tache-05-doctrine-gardes-fous-profondeur.html',1,'lot-65']]],
  ['geometrie_20geste_20et_20canevas_32',['TACHE-04 — Outil « Parcours » : geometrie, geste et canevas',['../lot-67-tache-04-outil-parcours.html',1,'lot-67']]],
  ['geste_20d_20assignation_20de_20texture_33',['TACHE-02 — Outil et geste d&apos;assignation de texture',['../lot-45-tache-02-outil-assignation.html',1,'lot-45']]],
  ['geste_20et_20canevas_34',['TACHE-04 — Outil « Parcours » : geometrie, geste et canevas',['../lot-67-tache-04-outil-parcours.html',1,'lot-67']]],
  ['geste_20pur_20de_20manipulation_35',['TACHE-02 — Outil de décors et geste pur de manipulation',['../lot-50-tache-02-outil-geste.html',1,'lot-50']]],
  ['gestion_20des_20erreurs_36',['9. Gestion des erreurs',['../spec-conventions.html#autotoc_md283',1,'']]],
  ['gestion_20des_20niveaux_37',['3. Gestion des niveaux',['../spec-interface-ihm.html#autotoc_md325',1,'']]],
  ['gestion_20des_20niveaux_20liste_20recherche_20fichiers_38',['LOT-36 — Refonte IHM (Qt) : gestion des niveaux (liste, recherche, fichiers)',['../lot-36.html',1,'lots']]],
  ['gestion_20des_20niveaux_20lot_2036_39',['Gestion des niveaux (LOT-36)',['../guide-ihm-qt.html#autotoc_md141',1,'']]],
  ['gestion_20des_20ressources_40',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md259',1,'']]],
  ['git_41',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]],
  ['github_20workflows_20ci_20yml_20job_20build_20test_20coverage_42',['4. Provisionnement CI (&lt;span class=&quot;tt&quot;&gt;.github/workflows/ci.yml&lt;/span&gt;, job &lt;span class=&quot;tt&quot;&gt;build-test-coverage&lt;/span&gt;)',['../lot-34-tache-01-provisionnement-qt-build.html#autotoc_md1706',1,'']]],
  ['github_20workflows_20release_20yml_43',['5. Provisionnement Release (&lt;span class=&quot;tt&quot;&gt;.github/workflows/release.yml&lt;/span&gt;)',['../lot-34-tache-01-provisionnement-qt-build.html#autotoc_md1707',1,'']]],
  ['glyphes_20et_20métriques_44',['TACHE-01 — Police bitmap : atlas de glyphes et métriques',['../lot-52-tache-01-police-bitmap.html',1,'lot-52']]],
  ['gp_20003_20ex_20gp_20004_45',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md192',1,'']]],
  ['gp_20004_46',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md192',1,'']]],
  ['gp_20019_47',['Vitesse terminale newtonienne (EX-GP-019)',['../guide-physique.html#autotoc_md198',1,'']]],
  ['gp_20023_20lot_2063_48',['Clé et porte verrouillée (&lt;span class=&quot;tt&quot;&gt;EX-GP-023&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-63&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md175',1,'']]],
  ['gp_20026_20lot_2063_49',['Plateformes mobiles (&lt;span class=&quot;tt&quot;&gt;EX-GP-026&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-63&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md178',1,'']]],
  ['gpu_50',['Vérification (visuelle, pas de test unitaire — brique GPU)',['../lot-11-tache-03-personnage-humanoide.html#autotoc_md907',1,'']]],
  ['gpu_20pas_20un_20changement_20de_20cible_51',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['gpu_20swap_20chain_20back_20buffer_52',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md204',1,'']]],
  ['grand_20que_20la_20fenêtre_53',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md114',1,'']]],
  ['grand_20que_20la_20fenêtre_20_3a_20fitzoom_20et_20hmi_3a_3aroomgrid_54',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md208',1,'']]],
  ['grande_20taille_55',['LOT-16 — Niveaux de grande taille',['../lot-16.html',1,'lots']]],
  ['grande_20taille_20lot_2016_56',['7. Niveaux de grande taille (LOT-16)',['../spec-editeur.html#autotoc_md301',1,'']]],
  ['graphics_20278_57',['Graphics (278)',['../cahiertest.html#autotoc_md18',1,'']]],
  ['graphics_20test_5frender_5fbudget_20cpp_58',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md243',1,'']]],
  ['graphicsdevice_59',['TACHE-02 — Fenêtre Qt + viewport `QWindow` embarqué → `GraphicsDevice`',['../lot-34-tache-02-viewport-d3d11-embarque.html',1,'lot-34']]],
  ['graphiques_60',['Crédits graphiques',['../md__2home_2runner_2work_2ProjectGaming_2ProjectGaming_2Source_2Elements_2Assets_2CREDITS.html',1,'']]],
  ['gravité_20_3a_20core_3a_3aloglevel_20core_3a_3aloglevel_61',['Les niveaux de gravité : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aa9b5a444ee11933c91d5e3235aa5b5e3&quot; title=&quot;core::LogLevel&quot;&gt;core::LogLevel&lt;/a&gt;',['../guide-journalisation.html#autotoc_md146',1,'']]],
  ['gravité_20asymétrique_20apex_20hang_20fast_20fall_62',['TACHE-02 — Gravité asymétrique + apex hang + fast-fall',['../lot-11-tache-02-gravite-asymetrique.html',1,'lot-11']]],
  ['gravité_20asymétrique_20finitions_63',['LOT-11 — Ressenti avancé : personnage humanoïde, gravité asymétrique, finitions',['../lot-11.html',1,'lots']]],
  ['gravité_20déplacement_20collisions_64',['TACHE-03 — Physique du personnage (gravité + déplacement + collisions)',['../lot-08-tache-03-physique-personnage.html',1,'lot-08']]],
  ['gravité_20et_20collisions_65',['LOT-08 — Gameplay personnage : déplacement, gravité et collisions',['../lot-08.html',1,'lots']]],
  ['gravité_20et_20intégration_66',['3. Gravité et intégration',['../guide-physique.html#autotoc_md197',1,'']]],
  ['grille_67',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1TileMap.html&quot; title=&quot;core::TileMap&quot;&gt;core::TileMap&lt;/a&gt; : la grille',['../guide-niveaux.html#autotoc_md167',1,'']]],
  ['grille_20_3a_20hmi_3a_3aeditortool_20editortool_68',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['grille_20aux_20entités_20_3a_20core_3a_3abuildlevelscene_20buildlevelscene_69',['De la grille aux entités : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#a671cc58bea9439fdb3ea23009b0da54b&quot; title=&quot;core::buildLevelScene&quot;&gt;buildLevelScene&lt;/a&gt;',['../guide-niveaux.html#autotoc_md173',1,'']]],
  ['grille_20cliquable_20palette_20de_20tuiles_70',['TACHE-02 — Écran éditeur : grille cliquable + palette de tuiles',['../lot-14-tache-02-ecran-editeur-palette.html',1,'lot-14']]],
  ['grille_20géométrie_20pure_71',['TACHE-02 — Balayage AABB contre la grille (géométrie pure)',['../lot-08-tache-02-balayage-aabb.html',1,'lot-08']]],
  ['groupés_20et_20qui_20suivent_20l_20outil_72',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['groupes_73',['Ordre des groupes',['../spec-conventions.html#autotoc_md273',1,'']]],
  ['guide_74',['guide',['../guide.html#autotoc_md248',1,'Comment lire ce guide'],['../guide.html#autotoc_md250',1,'Plan du guide']]],
  ['guide_20du_20développeur_75',['Guide du développeur',['../guide.html',1,'index']]],
  ['guide_20non_20codeur_20git_76',['TACHE-06 — Intégration menu, tests système, guide non-codeur Git',['../lot-14-tache-06-integration-guide-non-codeur.html',1,'lot-14']]]
];
